### ISSUE TITLE
[bounty] fix windows self hosted build

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#1018]
https://github.com/mediar-ai/screenpipe/actions/runs/12417863942/job/34669798423

/bounty 100

**Comment by Neptune650** [comment]
@louis030195 The issue is that it's trying to look at the system32 folder when it should try look at the user folder, this is a configuration issue on the build server, can you provide me rdp access to fix it.

**Comment by louis030195** [comment]
/tip $100 @Neptune650 

thanks for fixing self hosted windows (by connecting on the machine etc.)
