### ISSUE TITLE
[bug] Buying 50 credits does not vend credits

### ISSUE THREAD

**Issue by hbnordin2** [mediar-ai/screenpipe#1036]
**describe the bug**
brief description of the bug.

I bought 50 credits and it says I have 0 credits?

**system info**
- os: MacOS Sonoma Version 14.5
- screenpipe version: Version 0.20.6 (20241221.154820)

**additional context**
I bought 50 credits, I don't have 50 credits.

**Comment by louis030195** [comment]
this is because you used a different email for authentication and paying, i fixed this by using your github email now 

<img width="157" alt="image" src="https://github.com/user-attachments/assets/7bac0e20-db86-4196-ba08-c10d0236cd05" />


fixed it now 

sorry about this, i wil make more intuitive
