### ISSUE TITLE
[feature]enable dev mode provide PS and CMD CLI options

### ISSUE THREAD

**Issue by pleabargain** [mediar-ai/screenpipe#1039]
**describe the feature**
![image](https://github.com/user-attachments/assets/894b25e4-f5fb-4369-8734-9e3815e5b7d9)

I see for bash (great for linux)
![image](https://github.com/user-attachments/assets/b234eaef-ce4c-4f8e-b874-63921f4f4465)

I would like to see the commands for PowerShell and CMD

**why is this needed?**
help in debugging

thank you

**Comment by louis030195** [comment]
cmd works - i use it on my windows

**Comment by pleabargain** [comment]
I just tested same and got an error.  Error: port already in use


```
C:\Users\denni>%LOCALAPPDATA%\screenpipe\screenpipe.exe --audio-transcription-engine deepgram --ocr-engine windows-native --monitor-id 65650 --audio-device "Microphone (HD Pro Webcam C920) (input)" --audio-device "SAMSUNG (NVIDIA High Definition Audio) (output)" --ignored-windows "bit" --ignored-windows "VPN" --ignored-windows "Trash" --ignored-windows "Private" --ignored-windows "Incognito" --ignored-windows "Wallpaper" --ignored-windows "Settings" --ignored-windows "Keepass" --ignored-windows "Recorder" --ignored-windows "Vaults" --ignored-windows "OBS Studio" --ignored-windows "Nvidia" --ignored-windows "Control Panel" --ignored-windows "System Properties" --deepgram-api-key "fa5ab34deecea374b9e61370650ef1766286242b" --fps 1 --enable-frame-cache
Error: port already in use
```

**Comment by divanshu-go** [comment]
@louis030195 I guess we just need to change `language: bash` to `langauge: powershell` (for windows only)
https://github.com/mediar-ai/screenpipe/blob/5cf86a5be664444e82ba25a472d854d8e89e8376/screenpipe-app-tauri/components/dev-mode-settings.tsx#L273

might need to change in other files too.

**Comment by pleabargain** [comment]
I would suggest you put all of the platforms you support, one line for each platform.

**Comment by divanshu-go** [comment]
@pleabargain bash commands work on both linux and mac          (or any distro of linux/unix)
while powershell commands are generally meant for windows.

can you specify your thoughts?

**Comment by pleabargain** [comment]
> @pleabargain bash commands work on both linux and mac (or any distro of linux/unix) while powershell commands are generally meant for windows.
> 
> can you specify your thoughts?

I was unaware the MAC used BASH. My apologies.

**Comment by divanshu-go** [comment]
@louis030195 can I raise a PR for this change ? 
https://github.com/mediar-ai/screenpipe/issues/1039#issuecomment-2559795624
