### ISSUE TITLE
Mac OS 13.6 Error to search Audio and Text message

### ISSUE THREAD

**Issue by GaneshKannusamy** [mediar-ai/screenpipe#107]
The streamable UI has been slow to update. This may be a bug or a performance issue or you forgot to call `.done()`.

**Comment by louis030195** [comment]
@GaneshKannusamy what did you run?

is it the vercel app?

my guess is that sometimes the AI tool call can be slow and the warning comes, nothing to worry about 

sometimes tool call fails for example if the context is too big for the LLM (unlikely, except if you use small local LLM)

or just openai error 

we're working on improving this, probably will ship embeddings in the coming time to speed up search and relevancy 

what did you try exactly?

what are you trying to do/build?

**Comment by louis030195** [comment]
@GaneshKannusamy any news on this?
