### ISSUE TITLE
[ux] search UX improve duplicate

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#110]
what we could do:

create a new OCR table which only contains unique new OCR texts

which reference the full ocr table

so our capture code in screenpipe-server would add to both table now

switch the search endpoint to this table

it would both make LLM answers much better, relevant, and faster search because of less data in this table

a v0.1 would be to embed the text for semantic search which would be an easy feature i think, directly in sqlite using vector extension at first and see if we face performance issue

we can probably offer different embedding engine, local first and also cloud

later v0.2 if we see that anyone wants to see the underlying "sub frames" we can figure out something but ideally nobody will want it and the search experience is just great

cc @m13v

**Comment by m13v** [comment]
table: "chunked_text_index", "chunked_text_entries",
