### ISSUE TITLE
Health Status Modal Log Location Incorrect

### ISSUE THREAD

**Issue by DmacMcgreg** [mediar-ai/screenpipe#121]
## Steps to Reproduce
1. Open Health Status Modal
2. `tail -f $HOME/Library/Application\ Support/screenpipe/screenpipe.log`

log doesn't exist.

Instead:
`tail -f Library/Application\ Support/screenpipe/screenpipe-app.log`

**Comment by louis030195** [comment]
thanks it depend where you run the --data-dir in the cli indeed can improve instructions
