### ISSUE TITLE
Ollama llama3.1 Bad Request

### ISSUE THREAD

**Issue by DmacMcgreg** [mediar-ai/screenpipe#122]
## Steps to Reproduce

1. `screenpipe`
2. `ollama run llama3.1`
3. run desktop app
4. "What was I last looking at on my screen"
5. Bad Request

![CleanShot 2024-08-07 at 12 28 37@2x](https://github.com/user-attachments/assets/1b8416cc-c50c-426a-b259-d46057d63b7c)

![CleanShot 2024-08-07 at 12 28 22@2x](https://github.com/user-attachments/assets/d82212f1-0c61-4e99-bc97-0bcccd52700e)

**Comment by louis030195** [comment]
can you right click and inspect and share logs?

keep in mind ollama is quite bad at function calling compared to openai,

**Comment by DmacMcgreg** [comment]
Yes likely that is the issue. I read today that they only recommend llama 70b **instruct**
Trying today on another task, I couldn't get 8b to work at all basically doing function calling.
70B instruct on the other hand seems to be pretty good.

**Comment by louis030195** [comment]
@DmacMcgreg would be good to try again, we did lot of improvement there
