### ISSUE TITLE
ai/ollama tool calling experimental support

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#167]
https://github.com/sgomez/ollama-ai-provider/blob/main/packages/ollama/src/generate-tool/infer-tool-calls-from-stream.ts

IDK

https://github.com/mlc-ai/web-llm works much better than ollama in my experience :) but dont think it works on microsoft edge browser

**Comment by louis030195** [comment]
https://github.com/sgomez/ollama-ai-provider/issues/22

**Comment by louis030195** [comment]
solved

ideally can use streamText only, providing all the tools to the LLM (query screenpipe, stream response, ask more details to the user, reason on the query results and discard context if not good query, etc.)

any contribution to the ollama-ai-provider will make screenpipe better for ollama integration!

**Comment by louis030195** [comment]
#184 related

ollama still makes lot of mistake 

updating recommended model to mistral-nemo which seem to perform better than llama3.1

**Comment by CharafChnioune** [comment]
can we change models and test our selfs in the Mac app?

**Comment by louis030195** [comment]
@CharafChnioune Yes you can use ollama in the Mac app and change models as you wish
