### ISSUE TITLE
automatic device switching

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#170]
>[2024-08-14T16:41:54Z ERROR screenpipe_audio::core] An error occurred on the audio stream: The requested device is no longer available. For example, it has been unplugged.

e.g. i turned off my airpods

kinda tricky, what if someone does want to use specific devices?

**Comment by louis030195** [comment]
seems like macos audio output audio becomes "disconnected" when closing the lid also:

```
[2024-08-20T09:26:04Z INFO  screenpipe_server::core] Finished record_and_transcribe for device Display 1 (output) (iteration 68)
[2024-08-20T09:26:04Z ERROR screenpipe_server::core] Error in record_and_transcribe for device Display 1 (output) (iteration 68): Audio device not found, stopping thread
[2024-08-20T09:26:04Z INFO  screenpipe_server::core] Exiting audio capture thread for device: Display 1 (output)
```

we should something so that when lip is up again it restart recording

**Comment by louis030195** [comment]
also learning:

i was recording iphone mic and that prevented me from listening to music (but i tihnk we cant do much here, its the native thing of apple) should prob implement an app at some point for more control

**Comment by louis030195** [comment]
should also work with monitor i guess?

say you work somewhere w second screen, unplug and go somewhere else, then it should automatically have swiched? (atm would crash)

**Comment by louis030195** [comment]
not sure how the UX would be

maybe user say

"always record these devices: x y z user can select even if disconnected now" and should only record when connected

**Comment by louis030195** [comment]
>It would be great if you could dynamically switch to whatever is the active sound source

**Comment by louis030195** [comment]
instead just make option to always record the default devices

**Comment by louis030195** [comment]
@m13v been thinking about this

my use case i think would be fine:
- say i want to record macbook mic + display + headphone + iphone whenever connected
- it would just poll for audio device every seconds and when a device is unplug just stop transcribing it and when another one in my list comes up it would start recording it 

i think this is the best balance of UX / easiest to implement (prob 1-2h for me)


(likely will be useful for use case where they record from server too)

**Comment by m13v** [comment]
sounds good, in the future we can listen to notifications instead from the
OS libraries
