### ISSUE TITLE
de-correlate frame encoding from OCR

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#173]
@m13v 

we should be able to save mp4 at frame rate we want and perform ocr at different frame rate

examples:

bob is a nerd that wants digital immortality and wants to see his .mp4 with high smoothness and containing plenty of information (not just text, like cursor moving, and other stuff that OCR does not see) but does not care so much about ocr

john is lawyer and does not care much about the mp4 files but wants to have high precision on text appearing on his screen

lisa have only 50 gb left on her laptop and thus wants low frame rate on mp4 while high ocr precision

lee dont give a shit about data privacy and wants everything recorded in the cloud and stored in the cloud 

e.g.

```
screenpipe --ocr-rate 1 # 1 ocr computed and saved to db every second (what about window stuff?)

screenpipe --screen-encoding-rate 5 # 5 frame pushed to the .mp4 every second (what about window stuff?)

# bob
screenpipe --screen-encoding-rate 30 --ocr-rate 0.2
```

what about window and monitor stuff here?

how do we make everyone happy and customisable?

**Comment by louis030195** [comment]
also found out a "bug that is a feature" i use fps 0.2 or my mac dies and video are now 2.30 instead of 0.30 (i actually prefer to see videos of 1-3m, probably it's around the ideal attention span of humans just seeing the length of videos on tiktok and yt clips)

**Comment by m13v** [comment]
It’s been on my list for a while, we should definitely separate those
streams. In fact some people don’t need any features other than mp4, or
they don’t want to record screen at all and just want to query data that is
already in db

**Comment by louis030195** [comment]
done
