### ISSUE TITLE
Please provide custom instruction for llama3.1 to work properly

### ISSUE THREAD

**Issue by ronaldeddings** [mediar-ai/screenpipe#184]
# Issue
llama3.1 (latest) cannot interpret requests properly -- specifically, responses are only slightly accurate when using UTC time. Please see examples below

## Without UTC time
User Message:
```show me what i was doing at 9:50 am```

Response
```
To show you what you were doing at 9:50 AM, I'll need to access the relevant video recording from your ScreenPipe system.

First, let's convert 9:50 AM in America/Chicago time zone to UTC by adding 5 hours: 2024-08-18T14:50:00Z

Now, I'll query the ScreenPipe recordings for this specific time range:

/users/query_screenpipe?start_time=2024-08-18T04:50:00Z&end_time=2024-08-18T05:00:00Z

Unfortunately, the tool call returned an empty result. It seems that I couldn't find any relevant recordings for your activity at 9:50 AM.

Would you like to try a more specific time or ask another question?
```

## With UTC Time

User Message
```show me what i was doing at 2:50 pm UTC```

Response
```At 2:50 pm UTC, you were likely watching a video guide on how to use Import Maps in Supabase. The OCR output shows that you were looking at a page titled "Managing dependencies | Supabase Docs" and reading about how to configure VSCode to understand imports correctly.

Here is a possible summary of what you were doing at 2:50 pm UTC:

Watching a video guide on using Import Maps in Supabase
Reading about configuring VSCode to understand imports correctly
Looking at a page titled "Managing dependencies | Supabase Docs"
Please note that this is an educated guess based on the provided output, and I may not have captured all the relevant information. If you would like me to clarify or provide more details, please let me know!
```

## Additional Request
I specifically ask the model to **show me** what I was doing yet it only responds with summary. I believe video should be displayed at this point.

**Comment by louis030195** [comment]
@ronaldeddings we moved most of the prompt in the settings that you can customise and by default it should work

we recommend using mistral-nemo though (or any newer, did not try the phi3.5 model yet but not sure it supports tools)

you can use quantized versions to reduce compute `ollama run mistral-nemo:12b-instruct-2407-q2_K` also (make sure to use the model name in settings `mistral-nemo:12b-instruct-2407-q2_K`)
