### ISSUE TITLE
fix video not rendering in markdown tables and sometimes fail to render in the chat?

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#191]
<img width="1312" alt="Screenshot 2024-08-21 at 14 46 11" src="https://github.com/user-attachments/assets/90d1fa4e-827f-4687-bc7c-6014f5cfb0ee">

i think its an issue with slashes and markdown parsing

sometimes also fail to render in chat (some prompt engineering tweak to do?)

definition of done:
- "what did i do in the last 5 min? format as a table with a column showing videos of what i did" works
- no more fail to render in the chat (idk how to reproduce)

/bounty 50

**Comment by Mubashirshariq** [comment]
@louis030195 i am running screenpipe currently with cli installation,so i am not able to see this thing,can you please tell me where to run this ,"is this the vercel ai chat bot or something else'  ,is there any specific proj inside examples folder that i need to run and also i think it required openai key for the chat

**Comment by louis030195** [comment]
@Mubashirshariq check instructions here https://github.com/mediar-ai/screenpipe/tree/main/examples/apps/screenpipe-app-tauri

**Comment by louis030195** [comment]
https://github.com/mediar-ai/screenpipe/blob/main/examples/apps/screenpipe-app-tauri/components/chat-message-v2.tsx

**Comment by louis030195** [comment]
seems fxied idk why
