### ISSUE TITLE
add building.md

### ISSUE THREAD

**Issue by thewh1teagle** [mediar-ai/screenpipe#192]
Write notes for how to build screen-pipe on linux/macos/windows.
I can't find it in main readme and I think it will be useful to write everything related to building in that file.

Inspiration: [BUILDING.md](https://github.com/thewh1teagle/vibe/blob/main/BUILDING.md)

**Comment by louis030195** [comment]
would love any contribution on this!

**Comment by louis030195** [comment]
@thewh1teagle yeah https://docs.screenpi.pe/docs/getting-started

i think we still could add stuff like nvidia stuff if you want to help!
