### ISSUE TITLE
permission asked at every app update on macos

### ISSUE THREAD

**Issue by ronaldeddings** [mediar-ai/screenpipe#195]
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/b54341f0-5a99-4585-8d03-f985b2bb85d9">

<img width="273" alt="image" src="https://github.com/user-attachments/assets/a4c2a6d0-772f-4177-bf28-79f4bbdb9541">

<img width="498" alt="image" src="https://github.com/user-attachments/assets/233dbee5-02fa-4942-801b-f4cd83378ff3">

<img width="411" alt="image" src="https://github.com/user-attachments/assets/d51de892-bf91-4d29-a701-44926b9f2563">

Screenpipe is not starting due to requiring Screen & System Audio recording even though it has the permission. I've removed and added screenpipe as a measure to get it working again but have been unsuccessful to get it started

@louis030195

**Comment by louis030195** [comment]
@ronaldeddings yes this is a known issue, you have to remove permission using the "-" at every app update unfortunately, we're going to look into this soon (only on macos)

**Comment by louis030195** [comment]
> ## 💎 $50 bounty [• Louis Beaumont](https://console.algora.io/org/louis030195)
> ### Steps to solve:
> 1. **Start working**: Comment `/attempt #195` with your implementation plan
> 2. **Submit work**: Create a pull request including `/claim #195` in the PR body to claim the bounty
> 3. **Receive payment**: 100% of the bounty is received 2-5 days post-reward. [Make sure you are eligible for payouts](https://docs.algora.io/bounties/payments#supported-countries-regions)
> 
> Thank you for contributing to louis030195/screen-pipe!
> 
> **[Add a bounty](https://console.algora.io/org/louis030195/bounties/community?fund=louis030195%2Fscreen-pipe%23195)** • **[Share on socials](https://twitter.com/intent/tweet?text=%2450+bounty%21+%F0%9F%92%8E+https%3A%2F%2Fgithub.com%2Flouis030195%2Fscreen-pipe%2Fissues%2F195&related=algoraio)**

e.g. definition of done:

1. user should only have to set permission once
2. we can control when the permission is requested for example when first time installing or permission is not here through a button or similar

**Comment by louis030195** [comment]
i solved it
