### ISSUE TITLE
return frames in /search endpoint result

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#201]
most of the code is here to do this https://github.com/jasonjmcghee/xrem/blob/122079b5441040816d94b336114eb43da35751f5/src-tauri/src/core/video.rs#L7

jsut need to do some plumbing

/bounty 50

**Comment by louis030195** [comment]
use cases: multimodal responses + multimodal processing after search results

**Comment by devashishTaneja** [comment]
Hi @louis030195, I was able to crack this but the frame returned in /search endpoint has a massive payload which significantly degrades the performance of the API.

**Comment by louis030195** [comment]
@devashishTaneja base64?

**Comment by louis030195** [comment]
@devashishTaneja can you make the frame return optional with a path param to avoid unnecessary slow down and then return base64 image

**Comment by louis030195** [comment]
also feel free to send pr so i can give feedback on code

**Comment by louis030195** [comment]
/bounty 100

@devashishTaneja any news?

**Comment by louis030195** [comment]
done myself
