### ISSUE TITLE
[example/app] Timeline generation

### ISSUE THREAD

**Issue by oxysoft** [mediar-ai/screenpipe#21]
This is just an intuition but if you spend your time on the computer all day, it would be great if you could get a flexible and granular breakdown of how you spent your time. It would be a brand new era in time management, just like that. Dunno if that's out of scope for the project, maybe the UI bit but the backend could be done here I think ?

**Comment by louis030195** [comment]
super interesting

i actually maintain on my own a timeline for my life in excalidraw but that would be interesting to see a day by day timeline generated by AI based on what you do

i'm sure it could be generated directly in excalidraw, i actually did a LLM that can use excalidraw recently: https://github.com/louis030195/excalidraw-gpt


no need to change the code of screenpipe, can be just an external app that query the data and update the timeline periodically 

example that come to my mind could be like

- code on vscode for 30 min
- scroll twitter for 20 min 
- send message on linkedin 20 min
- etc 

with more details and represented as a line on excalidraw eventually with links to the actual content if its possible 

what kind of timeline would you like to see?

**Comment by bhupesh-sf** [comment]
This is really a cool idea. Would like to know if we are thinking to prioritize this?

**Comment by louis030195** [comment]
> This is really a cool idea. Would like to know if we are thinking to prioritize this?

what kind of use case would you like?

would you be able to contribute? that would be great 🙂

**Comment by bhupesh-sf** [comment]
The initial use case is to see how I am spending my time but gradually it should be able to suggest also where I am wasting time and able to suggest steps as well.

Regarding my contribution, I am native JS stack not python so not sure how much I would be able to. But yeah I will give a look to it for sure.

**Comment by louis030195** [comment]
@bhupesh-sf thanks! we don't use python

you can look at example, i'd recommend trying to run one of these first and iterate from there

**Comment by bhupesh-sf** [comment]
sure, coming 2 weeks are busy after that I will check this out and will be happy to contribute anyways I can.

**Comment by louis030195** [comment]
@bhupesh-sf @oxysoft any news? would love feedback, we shipped plenty of new stuff!

**Comment by bhupesh-sf** [comment]
Hey @louis030195 , I apologise for the late response—I've been busy with projects lately. I'm glad to hear that the progress has been going well!

As for contributing, since I'm still new to Rust and my schedule is pretty hectic, I was thinking of focusing on the JS/TS stack instead. I noticed the roadmap mentioned a TypeScript SDK. If you could point me in the right direction, I'd love to take that on. I'm well-versed in the JS/TS stack, so I can get up to speed quickly. Or, if there's anything else in this stack that needs attention, I'd be happy to help out whenever I have some free time.

**Comment by louis030195** [comment]
@bhupesh-sf you don't need to write rust, there is an API you can interact with and we have some examples to run JS or TS inside of the CLI or app, we have a JS runtime that can execute your code inside it:

https://github.com/mediar-ai/screenpipe/tree/main/examples/typescript/pipe-tagging-activity

for example you could do things like:
- check if there are security risk on the user screen by querying the API every min and asking ollama model if there is a risk in the OCR text
- writing logs of what the user is doing 
- etc

let me know if you need help on this or join the discord: https://discord.gg/ywCgfGwD
