### ISSUE TITLE
implement cursor like UI in the app playground ($100 bounty)

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#219]
- resizable components
- chat history
- shortcuts
- shortcut to use "no context" vs "all codebase" (e.g. LLM makes function call to screenpipe like cursor)
- basic foundational code to use `@` and `#` to get specific context from screenpipe (because the UX is unclear yet, feel free to just write some basic code for this, doesn't have to work yet) (basic thought is that you can use `#tags` like in obsidian somehow, and `@` like `@today` `@john`, very unclear atm how to use this)
- small dropdown to switch model effortlessly
- bonus: be creative on the model output markdown parsing (for example when cursor answers with links you can click and it shows the file, atm we do this for .mp4 files, we tell the model that it can render video by using \`absolutepath.mp4\`)

rules:
- use same dependency that we use (shadcn, magicui, tailwind, framer-motion)
- use typescript
- in general aim for quality of code like https://github.com/vercel/ai-chatbot

how to work on app:
```
cd examples/apps/screenpipe-app-tauri
bun i
bun tauri dev
```

/bounty 100

**Comment by itsdheerajdp** [comment]
@louis030195 can i get it assigned so that i can start working on it?
