### ISSUE TITLE
integration test that build cli on windows & linux, run it and test it works 

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#225]
definition of done:
- when we push code it would build and run the CLI on windows and linux
- need to simulate audio and screen device in github action
- let it run for like 60 seconds and see if it crashes or not

bonus:
- display some images somehow and see ocr working
- add some voice in the audio and see transcription working 

/bounty 100

**Comment by daveads** [comment]
@onyedikachi-david you are already on an Okay track... leaving this to you.

**Comment by divanshu-go** [comment]
@louis030195 is this still open.
Hey you are not doing releases for linux and windows

**Comment by arivale-exe** [comment]
Could you clarify the bounty terms before implementation: contributor eligibility, whether the issue must be claimed/assigned and how, how competing submissions are handled, the bounty currency/payment asset and network, recipient requirements, and whether USDC on Solana to the specified KAST destination is accepted?
