### ISSUE TITLE
Is there a trial of desktop app available?

### ISSUE THREAD

**Issue by sammcj** [mediar-ai/screenpipe#229]
Is there a trail of the desktop app available somewhere?

I'd definitly like to try it out before shelling out $150(!)~ AUD per year.

Thanks,

**Comment by louis030195** [comment]
we don't offer trials right now but you can install the CLI for free:

```
brew tap mediar-ai/screenpipe https://github.com/mediar-ai/screenpipe.git
brew install screenpipe
```

or [build the app from source](https://github.com/mediar-ai/screenpipe/tree/main/examples/apps/screenpipe-app-tauri)(afraid this is not well documented / straightforward)

**Comment by louis030195** [comment]
```bash
export DYLD_LIBRARY_PATH=$(pwd)/screenpipe-vision/lib
cargo build --release --features metal
cd examples/apps/screenpipe-app-tauri
bun scripts/pre_build.js
bun tauri build
```

@sammcj prob these commands

**Comment by sammcj** [comment]
Ah ok thanks, that should get me going to try it out. Thanks

**Comment by saulide** [comment]
Setting up screenpipe bin for arm64...
Copied most recent arm64 screenpipe binary from ../../../../target/release/screenpipe
[cctools-port]: generating fake signature for './screenpipe-aarch64-apple-darwin'
[cctools-port]: generating fake signature for './screenpipe-aarch64-apple-darwin'
hard coded the FUCKING dylib
screenpipe for arm64 set up successfully.
Setting up screenpipe bin for x86_64...
No suitable x86_64 screenpipe binary found
screenpipe for x86_64 set up successfully.

-> m2 pro macbook. I suspect the "hard coded the FUCKING dylib
" is  the problem :D @louis030195 any ideas?
