### ISSUE TITLE
[app] add support for custom openai provider url 

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#235]
atm we only support openai or ollama 

add support for custom openai url 

definition of done:
- [ ] i can drop my url (say llamacpp or github models, or openrouter, or anthropic maybe?) and chat and it works (tool call etc.) on all messages in the empty screen, can still embed videos, etc. (does not fail at tool call)
- [ ] consistent UI 
- [ ] still uses vercel/ai lib (figure out how)

**Comment by eladrave** [comment]
You can just add a "BASE_URL" in the settings, and use litellm.
This will enable you to run any model. Either remote, or local, or both
@louis030195

**Comment by louis030195** [comment]
done
