### ISSUE TITLE
try/implement new voice activity detection model (silero-vad)

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#241]
https://github.com/huggingface/candle/blob/main/candle-examples/examples/silero-vad/main.rs

definition of done:
- [ ] can use either current vad or new one (use param in cli like ocr engine)
- [ ] some unit test that show some metrics performance diff

**Comment by itsdheerajdp** [comment]
@louis030195  can i get it assigned so that i'll start working on it

**Comment by louis030195** [comment]
@itsdheerajdp sure, you can start

**Comment by louis030195** [comment]
@itsdheerajdp priority changed and need to ship this soon, started branch here: 

https://github.com/mediar-ai/screenpipe/pull/250

it's still dirty unfinished, feel free to work on it

**Comment by itsdheerajdp** [comment]
@louis030195 can i use your changes and make new pr ?
