### ISSUE TITLE
some audio device not working on windows

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#277]
<img width="1187" alt="image" src="https://github.com/user-attachments/assets/f3658736-ffff-4db9-acf5-8fdd1e7b0cef">

also noticed some issues when audio device has 4+ channels

/bounty 50

**Comment by louis030195** [comment]
@yanisoln thx for this attempt, let me know how i can help anyhow!

**Comment by yanisoln** [comment]
Hi @louis030195 thanks for the kind words! I'll let you know if there's anything 👍

**Comment by yanisoln** [comment]
Hello again,

I tried to replicate the bug you described with audio devices having >= 4 channels, but I've not been able to reproduce the bug on my end. I am trying it on a Windows 11 environment (23H2), and I have already tested using various virtual audio devices, experimenting with different numbers of channels and several configurations, yet the issue does not show up for me.
![c1](https://github.com/user-attachments/assets/64cb6c51-6315-4e08-a983-b8766f3f80f2)
![c2](https://github.com/user-attachments/assets/535e0767-3560-4ff1-9a25-67196b544917)

Could you provide more detailed specifics of the audio setup and configurations you had in place when the issue occured? In particular, any settings or steps taken that may allow me to reproduce the problem would be most welcome. I am really keen on getting to the bottom of this and would appreciate any further details you can give me that will help replicate the issue and finally get it resolved.


Thanks again !

**Comment by louis030195** [comment]
https://github.com/mediar-ai/screenpipe/issues/311

**Comment by louis030195** [comment]
@yanisoln i get "aac too complex" when trying to read mp4 file and STT with Speakers/Headphones Realtek(R) Audio 24 bit 48000 Hz (output) on Windows
