### ISSUE TITLE
($100) new VAD model - cannot merge due to windows build failing

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#294]
https://github.com/mediar-ai/screenpipe/pull/289

**Comment by louis030195** [comment]
https://github.com/mediar-ai/screenpipe/actions/runs/10744885095/job/29802769847

basically need to make windows build work (in CI and local if possible)

**Comment by louis030195** [comment]
@varshith257 any news?

**Comment by varshith257** [comment]
Didn't patch up to this work due to other works. Anyhow seems it solved 😀

**Comment by louis030195** [comment]
> Didn't patch up to this work due to other works. Anyhow seems it solved 😀

in fact it's not https://github.com/mediar-ai/screenpipe/actions/runs/10816487185/job/30007781054

☹️

**Comment by varshith257** [comment]
@louis030195 Interesting! Ok I will try to patch it up if I can

**Comment by louis030195** [comment]
@varshith257 any idea whats the problem?
