### ISSUE TITLE
gpu, accelerated cpu support for STT & VAD

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#318]
- [x] gpu STT mac
- [ ] gpu silero vad mac ? not sure it works
- [ ] cuda silero vad windows ? not sure it works
- [ ] cuda silero vad linux ? not sure it works
- [ ] cuda STT windows (heard it worked for some people)
- [ ] cuda STT linux (heard it worked for some people)

**Comment by louis030195** [comment]
/bounty 50 

just for the mkl support, will add more bounties for others, typically just a few lines of change to change check cargo.toml and release-app.yml features

**Comment by onyedikachi-david** [comment]
@louis030195 The current benchmark is failing
