### ISSUE TITLE
make local STT better $200

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#322]
/bounty 200 

atm STT with whisper tiny or large produces ton of "thank you" and such

definition of done:
- can use local STT without the "thank you" and such noise just switching the `-a` arg
- must be rust obviously 
- can still compile the app / CLI without issue in github actions etc
- works on consumer hardware - users can still use their computer for normal work without having screenpipe destroy their CPU, GPU, RAM

references that might be helpful:
- https://github.com/snakers4/silero-models - https://github.com/snakers4/silero-models?tab=readme-ov-file#onnx
- https://github.com/fishaudio/fish-speech
- https://github.com/huggingface/candle

**Comment by louis030195** [comment]
some says better delimitation of the audio chunk processing

**Comment by louis030195** [comment]
solved myself

**Comment by jandremarais** [comment]
@louis030195 what was the solution? It looked like a problem with Whisper hallucinating on snippets with no speech in it.
