### ISSUE TITLE
timeline ui

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#343]
i have been reticent for a while on this feature because screenpipe is not intented to be a copy of rewind or things like this and more focused on infrastructure / devtools

but this is more intuitive

https://screenmemory.app/

https://www.rewind.ai/

<img width="1512" alt="Screenshot 2024-10-02 at 14 46 34" src="https://github.com/user-attachments/assets/cdfd6595-7bd5-4018-bb09-b45e156bdf94">

<img width="1512" alt="Screenshot 2024-10-02 at 14 46 21" src="https://github.com/user-attachments/assets/57b86a6e-ff67-4c58-a686-889397a2dd42">

<img width="1512" alt="Screenshot 2024-10-02 at 14 46 07" src="https://github.com/user-attachments/assets/abfd03a9-92cb-492a-8bde-c271f955fefc">

i guess all that is required is:
- [x] merge mp4 endpoint
- [ ] plumbing with audio
- [ ] global shortcut 
- [ ] (later) select part of your day to prompt AI
- [ ] maybe: annotate times with LLM/pipes
- [ ] eventually all pipes could be somehow integrated with this e.g. "enrich my CRM pipe" would show somewhere i had conversation with customer john and click bring to salesforce or idk
- [ ] ?

**Comment by louis030195** [comment]
https://github.com/tauri-apps/tauri/discussions/4810

**Comment by craftyshaun** [comment]
> but this is more intuitive

My 2c here is that this adds the ability to 'sense check' the LLM response, which is excellent. 
I'm using Reclaim and saw this as a near drop-in. I was just about to purchase it, but then I noticed that the timeline was missing.

Understanding the reclaim.ai has also pivoted to the pendant may create a market gap as well.

**Comment by louis030195** [comment]
bounty for a small part of this, e.g. just showing a scrollable timeline above current app i'm using even if it's full screen

definition of done:

- when i do specific shortcut from any app, it shows a scrollable timeline (can be fake data initially, i can do the plumbing with .mp4)
- works even if i'm in a full screen app
- works on macos and windows at least


/bounty 200

**Comment by Glavin001** [comment]
Timeline view with Rewind was one of my favourite and most used features. Made it super quick to look back in time to see my screen, copy text (you already have OCR ✅ ), etc.

**Comment by louis030195** [comment]
biggest blocker for this is how to show window on top of full screen app in tauri?

**Comment by craftyshaun** [comment]
> how to show window on top of full screen app in tauri?

If you're looking to emulate the Rewind.ai app then this Is understandable.

That said if I was to make a user story, I'd say:

_As a user, I want to view the mp4 history with the timestamp to align it with the AI responses. This will enable me to check the response and eyeball what's on the screen if the LLM provides a subpar result_.

As for the UX I would not mind if it were another window with the same ratio as my screen yet smaller (or even resizable), and I could zoom in if need be. As long as I can 'change to that window' and focus on it while viewing, I would not mind.

Tauri, as your platform, will have pros and cons. This may be a time when speed of development is prioritised over 'the perfect UI'.

@Glavin001, does the above resinate with you?

**Comment by louis030195** [comment]
<img width="1312" alt="Screenshot 2024-10-02 at 14 41 36" src="https://github.com/user-attachments/assets/f07af819-fd3a-4ed2-b515-a48f0367ddb9">

an idea i had also but kinda different is to allow user to scroll horizontally the video in results here
