### ISSUE TITLE
Cuda 12 Support

### ISSUE THREAD

**Issue by lucagervasi** [mediar-ai/screenpipe#348]
Cuda-12 is the default toolkit version on fedora 40. 
Trying to build the application on that platform fails:
`error: failed to run custom build command for `cudarc v0.11.9`

Caused by:
  process didn't exit successfully: `/home/luca.gervasi/GIT/Github/mediar-ai/screenpipe/target/release/build/cudarc-d53209869a46249a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CUDA_ROOT
  cargo:rerun-if-env-changed=CUDA_PATH
  cargo:rerun-if-env-changed=CUDA_TOOLKIT_ROOT_DIR

  --- stderr
  thread 'main' panicked at /home/luca.gervasi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cudarc-0.11.9/build.rs:82:14:
  Unsupported cuda toolkit version: `12.6`. Please raise a github issue.
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
`

Installed package:
`07:29 $ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Aug_14_10:10:22_PDT_2024
Cuda compilation tools, release 12.6, V12.6.68
Build cuda_12.6.r12.6/compiler.34714021_0
`

There will be a fix to this?
Thanks

**Comment by louis030195** [comment]
thanks, looking at this: https://github.com/huggingface/candle/issues/2478

**Comment by louis030195** [comment]
https://github.com/huggingface/candle/pull/2494

@lucagervasi could you confirm screenpipe now works with cuda 12.6?

**Comment by lucagervasi** [comment]
Sure, which branch has the fix?
