### ISSUE TITLE
Ignore non-existent devices (monitors or audio that is not connected)

### ISSUE THREAD

**Issue by stracker-phil** [mediar-ai/screenpipe#349]
I have two offices (home office and workplace) with different hardware but the same MacBook.

Screenpipe runs on the MacBook, but once configured to capture the home-office monitor and home-office headphones, the hardware list in the workplace office becomes invalid: Screenpipe tries to connect to the home-office monitor, which is not present, and throws an error in the console.

I'm not sure if the error indicates an actual launch failure, but I'd like to support this setup by simply ignoring hardware devices that are currently not connected to the MacBook.

**More Details:**

![image](https://github.com/user-attachments/assets/8f772e9b-8c8c-4f88-aff6-cb27089f1670)

![image](https://github.com/user-attachments/assets/3b55fa0e-78a8-4320-a00a-f48ad5404456)

**Comment by louis030195** [comment]
@stracker-phil thanks, not sure to understand the issue, one known issue is the following:
1. have two monitors, select 2 monitors to record
2. unplug one
3. screenpipe will still list 2 monitors in the app UI and try to use both, it will fail to capture one but this does not affect the rest of the program at all (just showing an error)

is it what you are facing? (same issue could happen with audio but didn't prioritize it yet as it is not causing many issues)

**Comment by stracker-phil** [comment]
@louis030195 yes, that's exactly what I mean. But as you mention, the error message is more a "debug level" error, and capturing the existing monitor(s) should work.

I'll do some more usage tests in the coming days; in case I notice capturing does not work, I'll let you know.
