### ISSUE TITLE
Getting segfault with latest brew version

### ISSUE THREAD

**Issue by jim-at-jibba** [mediar-ai/screenpipe#362]
Hey I just installed the latest version from brew but am getting the following error:

`[1]    78794 segmentation fault  screenpipe`

Im am not familier with rust so dont really know how to better debug it for you.

I have 1.79.0 of rust installed. 

It was running fine on the previous version and then I tried to setup the desktop app and started having the issues above. May not be related.

**Comment by jim-at-jibba** [comment]
Im not sure if I am supposed to have access to the link above but I dont.

**Comment by louis030195** [comment]
@jim-at-jibba there is a known issue with macos display audio (output) which implementation is quite hacky https://github.com/mediar-ai/screenpipe/issues/297 and can crash due to bad low level code

although i did not face this issue for days personally, i cannot explain why but it seems this is more likely to happen when it's not in release mode (eg `--release`)

what version of macos do you have? how do you run screenpipe?

**Comment by jim-at-jibba** [comment]
Hey,

Thanks for your quick reply. 

I am using MacOS 14.4. 

I have tried just running `screenpipe` and also specifying the audio device ` screenpipe --audio-device "Anker PowerConf C200 (input)"`, both of which worked until recently. 

I am assuming that the brew version will always be in `--release` mode.

I have pulled the repo and build it locally and get the same error.

**Comment by louis030195** [comment]
> Hey,
> 
> Thanks for your quick reply.
> 
> I am using MacOS 14.4.
> 
> I have tried just running `screenpipe` and also specifying the audio device ` screenpipe --audio-device "Anker PowerConf C200 (input)"`, both of which worked until recently.
> 
> I am assuming that the brew version will always be in `--release` mode.
> 
> I have pulled the repo and build it locally and get the same error.

can you share the logs?

is it happening instantly?

what mac do you have?

**Comment by jim-at-jibba** [comment]
Hey,

More than happy to help. If you mean the logs stored in the `./screenpipe` folder, they wont help as the program crashes before its has time to log anything.

Is there something I can set in the code to get more verbose logging? Or a flag that can be passed?

I have a M1 Max with 64GB ram.

**Comment by jim-at-jibba** [comment]
I moved the old `.screenpipe` folder and ran `screenpipe` again. It creates the `.screenpipe` folder with an empty log file and `data` folder but then crashes straight after

**Comment by louis030195** [comment]
you can try --debug

**Comment by jim-at-jibba** [comment]
Thanks, it crashes before anything is output.

**Comment by louis030195** [comment]
@jim-at-jibba what about `screenpipe --disable-vision --disable-audio` ?

then disable one or the other to see what's causing this

also maybe upgrading your macos version could help (never seen this issue before)

**Comment by jim-at-jibba** [comment]
Thanks. I will try this tomorrow and report back

**Comment by jim-at-jibba** [comment]
Updating MacOS seemed to do the trick. I runs fine now. 

But when I Ctrl-C to stop the process if freaks out. I have to kill the terminal pane to stop the process
<img width="1056" alt="Screenshot 2024-09-25 at 11 10 37" src="https://github.com/user-attachments/assets/0293add5-99e7-4130-832d-53bd95cddd70">

Thanks for our help
