### ISSUE TITLE
Log Size > 500GB in less than a month

### ISSUE THREAD

**Issue by DmacMcgreg** [mediar-ai/screenpipe#371]
Log File size has jumped to over 500GB in less than a month

**Comment by louis030195** [comment]
oh wow

louisbeaumont@louisbeemacbook:~$ du -sh ~/.screenpipe/screenpipe.log
1.5G    /Users/louisbeaumont/.screenpipe/screenpipe.log

mine 1.5gb weirdly but i heard someone saying 108 gb for him

i guess quick hack is to remove the top or something like this (not familiar with good practices)
