### ISSUE TITLE
i need help making audio transcription work well on windows (bounty size TBD yet)

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#374]
i need help making audio transcription work well on windows (bounty size TBD yet)

is audio transcription working on your windows machine?

if not you can help on this! and make money :)

**Comment by louis030195** [comment]
https://github.com/huggingface/candle/pull/2523/files

might be useful to try to resamble and other stuff directly in the `core.rs` audio instead of later in stt

**Comment by fxk0** [comment]
I'm still having issues with this for some reason. my audio for my microphone is scarlett 2i2 USB and for my speakers it's scarlett 2i2 USB I also use a routing audio software voicemeeter but have tried it without that installed and still no success

**Comment by EzraEllette** [comment]
Is this fixed now? @louis030195

**Comment by louis030195** [comment]
fixed
