### ISSUE TITLE
$400 - deno runtime crashes on macos when CLI is built in github action (does not happen on local builds)

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#375]
https://github.com/denoland/deno_core/issues/916

**Comment by louis030195** [comment]
/bounty 200

to make this work

**Comment by louis030195** [comment]
> @louis030195 Hi, Could you upload a sample mac binary from CI?

any news on this? upgraded to $300

i guess things to try:

use https://github.com/nektos/act to build in local ci 

tweak `pipes.rs`, try to set some memory thing

anything else?

**Comment by urbit-pilled** [comment]
not sure how complex this will be yet but I'll look into it.
/attempt #375

**Comment by louis030195** [comment]
update: this does not seem to happen on all macos, mine crashes:

crash: 14.5, mac book pro m3 max 32 gb ram

**Comment by louis030195** [comment]
@urbit-pilled 

btw most reliable way to reproduce:

- build app using the release-app.yml ci (in github runner or local runner somehow)

```
mkdir /tmp/rnd
echo "console.log('hi')" > /tmp/rnd/pipe.js
 /Applications/screenpipe.app/Contents/MacOS/screenpipe download /tmp/rnd
/Applications/screenpipe.app/Contents/MacOS/screenpipe enable rnd 
/Applications/screenpipe.app/Contents/MacOS/screenpipe
```

**Comment by louis030195** [comment]
what i tried:

- running the built CLI before the tauri app build https://github.com/mediar-ai/screenpipe/actions/runs/11169907285 (can download CLI here)
- it does not crash
- when i run the CLI built into the app it does crash (eg only different is [apple signing + other dark stuff idk](https://github.com/tauri-apps/tauri/blob/dev/crates/tauri-cli/src/signer/sign.rs))

**Comment by louis030195** [comment]
i fxied the issue (i dont know how 😂)

**Comment by urbit-pilled** [comment]
ok, great to see that it works now
