### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'selectedPipe.source.startsWith')

### ISSUE THREAD

**Issue by hurryhx** [mediar-ai/screenpipe#378]
Tauri app version: 0.2.79
System: MacOS 15.1
After I build tauri app and download pipe in pipe store, I select one pipe, then I get this error.
<img width="1199" alt="Screenshot 2024-09-30 at 12 54 45 AM" src="https://github.com/user-attachments/assets/675a66da-86ba-4b70-9b05-3c3c03836420">
<img width="1080" alt="Screenshot 2024-09-30 at 12 55 23 AM" src="https://github.com/user-attachments/assets/e7e17dd5-723b-4a9a-a9b9-8e0ac6f083eb">

**Comment by louis030195** [comment]
@hurryhx hey do you stil have this issue on new versions?
