### ISSUE TITLE
Changes in settings will visually flop back and forth in a loop - don't always stick after update

### ISSUE THREAD

**Issue by jeffhaskin** [mediar-ai/screenpipe#380]
https://github.com/user-attachments/assets/18490324-4aeb-4aaf-87a0-18640bc1a5d4

https://github.com/user-attachments/assets/985b1878-fdf9-4e5b-855f-d55f63e81373

MacOS: 14.6.1
Screenpipe Version: 0.2.79 (20240929.214614)

After making a change, the setting flip-flops visually. After clicking update and leaving the settings window and re-entering, the settings not always changed, I have to try several times before it sticks.

**Comment by louis030195** [comment]
@jeffhaskin sorry about that

`0.2.80` should have solved this issue
