### ISSUE TITLE
Unable to access Screenpipe server at 127.0.0.1:3030

### ISSUE THREAD

**Issue by QuincySan** [mediar-ai/screenpipe#381]
Unable to access Screenpipe server at 127.0.0.1:3030

**Description:**
After successfully building and running Screenpipe, I am unable to access the server at 127.0.0.1:3030. The server appears to be running, but I cannot interact with it as expected.

**Steps to reproduce:**
1. Built Screenpipe using `cargo build --release --features metal`
2. Ran Screenpipe using `./target/release/screenpipe`
3. Server logs indicate successful startup on 127.0.0.1:3030
4. Attempted to access via browser and curl, both unsuccessful

**Current behavior:**
- No response when accessing http://127.0.0.1:3030 via browser or curl
- lsof shows the process is listening on port 3030
- Google process has established connections to the Screenpipe process

**Expected behavior:**
- Able to access and interact with Screenpipe server via 127.0.0.1:3030

**Environment:**
- macOS (version: 15.0 (24A335))
- Rust version: default
- Screenpipe version: 0.1.93

**Additional information:**
- Firewall is disabled
- Network proxy software is turned off
- curl http://localhost:3030 returns no response

**Questions:**
1. Is there a specific client or method required to interact with the Screenpipe server?
2. Are there any additional configuration steps needed after running the server?
3. Is there documentation available on how to properly access and use the Screenpipe server once it's running?

Any guidance on how to properly access and interact with the Screenpipe server would be greatly appreciated.

**Comment by louis030195** [comment]
@QuincySan can you share CLI logs?

`cat ~/.screenpipe/screenpipe.log` | pbcopy

paste here then

1. no just curl
2. make sure to use `DYLD_LIBRARY_PATH=$(pwd)/screenpipe-vision/lib` on macos to link OCR lib to Rust
3. https://docs.screenpi.pe 

also, feel free to cmd+a + cmd+c + cmd +v [this file](https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-server/src/server.rs) in chatgpt and ask any questions to query the API "give me 50 ways to curl screenpipe"

same for the DB

https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-server/src/db.rs

"give me 50 ways to query screenpipe db at ~/.screenpipe/db.sqlite using sqlite CLI"

**Comment by Glavin001** [comment]
@QuincySan : I had the same issue when installed via `brew install screenpipe` method. I ended up building from source and also built the desktop app which allowed me to see the UI, not sure if that is what you intended or if you actually wanted only the API? If you also found yourself stuck and actually wanted the desktop app you can take a look at the install instructions: https://github.com/mediar-ai/screenpipe/pull/390

**Comment by QuincySan** [comment]
> @QuincySan can you share CLI logs?
> 
> `cat ~/.screenpipe/screenpipe.log` | pbcopy
> 
> paste here then
> 
> 1. no just curl
> 2. make sure to use `DYLD_LIBRARY_PATH=$(pwd)/screenpipe-vision/lib` on macos to link OCR lib to Rust
> 3. https://docs.screenpi.pe
> 
> also, feel free to cmd+a + cmd+c + cmd +v [this file](https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-server/src/server.rs) in chatgpt and ask any questions to query the API "give me 50 ways to curl screenpipe"
> 
> same for the DB
> 
> https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-server/src/db.rs
> 
> "give me 50 ways to query screenpipe db at ~/.screenpipe/db.sqlite using sqlite CLI"

@louis030195 Thanks for your reply! The CLI log is too long, and the log file is 397.1MB large, so that I cannot attach here. 

I'll try your other suggestions and see whether it work.

**Comment by QuincySan** [comment]
> @QuincySan : I had the same issue when installed via `brew install screenpipe` method. I ended up building from source and also built the desktop app which allowed me to see the UI, not sure if that is what you intended or if you actually wanted only the API? If you also found yourself stuck and actually wanted the desktop app you can take a look at the install instructions: #390

@Glavin001 Hi, Glavin, I tried the method you gives me, and it works! Thanks for the suggestion 🙌
