### ISSUE TITLE
Successfully built Macos ScreenPipe app here

### ISSUE THREAD

**Issue by 0smboy** [mediar-ai/screenpipe#382]
[this gist](https://gist.github.com/0smboy/7e421df804f96682ddfb490f51a5cc20)

**Comment by RobDiek** [comment]
no access to workspace, news doesn't work

**Comment by 0smboy** [comment]
@RobDiek try again

**Comment by RobDiek** [comment]
awesome, thank you. :) currently trying out the script

**Comment by RobDiek** [comment]
when just running the script I get this

se -h to get full help or, even better, run 'man ffmpeg'
./build_screenpipe.sh: line 63: ]: command not found
./build_screenpipe.sh: line 64: syntax error near unexpected token `}'
./build_screenpipe.sh: line 64: `    }'

**Comment by RobDiek** [comment]
can't you don't just drop a link to the dmg / pkg?

**Comment by akeslo** [comment]
> when just running the script I get this
> 
> se -h to get full help or, even better, run 'man ffmpeg' ./build_screenpipe.sh: line 63: ]: command not found ./build_screenpipe.sh: line 64: syntax error near unexpected token `}' ./build_screenpipe.sh: line 64: ` }'

Same error here

**Comment by 0smboy** [comment]
> had to do a bit of manual work to get this to work;
> 
> 1. bun isn't installed - had to install it manually by running curl -fsSL https://bun.sh/install | bash
> 2. installed Xcode command line tools just for being safe
> 3. under "ok lets build it" there has to be a "cd screenpipe" first
> 4. "bun i" misses a sudo before it
> 
> still getting error
> 
> error: failed to run custom build command for `screenpipe-app v0.2.79 (/Users/user/Desktop/screenpipe/screenpipe-app-tauri/src-tauri)`
> 
> Caused by: process didn't exit successfully: `/Users/robindieker/Desktop/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-b07c37cc2f7b5503/build-script-build` (exit status: 1) --- stdout cargo:rerun-if-env-changed=TAURI_CONFIG cargo:rerun-if-changed=tauri.conf.json cargo:rustc-check-cfg=cfg(desktop) cargo:rustc-cfg=desktop cargo:rustc-check-cfg=cfg(mobile) cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_APP_NAME=pe cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_PREFIX=screenpi cargo:rustc-check-cfg=cfg(dev) cargo:PERMISSION_FILES_PATH=/Users/robindieker/Desktop/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-e160e3b75eb0e726/out/app-manifest/**app**-permission-files cargo:rerun-if-changed=capabilities cargo:rustc-env=TAURI_ENV_TARGET_TRIPLE=aarch64-apple-darwin resource path `screenpipe-aarch64-apple-darwin` doesn't exist warning: build failed, waiting for other jobs to finish... Error failed to build app: failed to build app user@192-168-2-186 screenpipe-app-tauri %

Did you follow the steps? First, you need to install the `screenpipe` CLI.

```bash
cd screenpipe
cargo build --release --features metal
```

Then create the link:

```bash
ln -s ./target/release/screenpipe screenpipe-app-tauri/src-tauri/screenpipe-aarch64-apple-darwin
```"

**Comment by RobDiek** [comment]
Hi, no, I didn't. I thought it's a "one for all" installation script, must have misinterpreted. Just did the steps and trying it again, thanks! :)

**Comment by RobDiek** [comment]
hmm strange, still gives me an error 


   Compiling mac-notification-sys v0.6.2
   Compiling screenpipe-app v0.2.79 (/Users/robindieker/Desktop/spbuild/screenpipe/screenpipe-app-tauri/src-tauri)
   Compiling sentry v0.34.0
   Compiling tauri-plugin-autostart v2.0.0-rc.1
   Compiling fix-path-env v0.0.0 (https://github.com/tauri-apps/fix-path-env-rs#8481725b)
   Compiling tauri-plugin-cli v2.0.0-rc.1
   Compiling sysinfo v0.29.11
   Compiling tauri-plugin-process v2.0.0-rc.1
error: failed to run custom build command for `screenpipe-app v0.2.79 (/Users/robindieker/Desktop/spbuild/screenpipe/screenpipe-app-tauri/src-tauri)`

Caused by:
  process didn't exit successfully: `/Users/robindieker/Desktop/spbuild/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-b07c37cc2f7b5503/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-check-cfg=cfg(desktop)
  cargo:rustc-cfg=desktop
  cargo:rustc-check-cfg=cfg(mobile)
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_APP_NAME=pe
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_PREFIX=screenpi
  cargo:rustc-check-cfg=cfg(dev)
  failed to read plugin permissions: failed to read file: No such file or directory (os error 2)
warning: build failed, waiting for other jobs to finish...
    Error failed to build app: failed to build app


will dig up and try to see which file / directory he is missing.

**Comment by 0smboy** [comment]
@RobDiek @akeslo i update the script, you can just run the script.

**Comment by akeslo** [comment]
> > had to do a bit of manual work to get this to work;
> > 
> > 1. bun isn't installed - had to install it manually by running curl -fsSL https://bun.sh/install | bash
> > 2. installed Xcode command line tools just for being safe
> > 3. under "ok lets build it" there has to be a "cd screenpipe" first
> > 4. "bun i" misses a sudo before it
> > 
> > still getting error
> > error: failed to run custom build command for `screenpipe-app v0.2.79 (/Users/user/Desktop/screenpipe/screenpipe-app-tauri/src-tauri)`
> > Caused by: process didn't exit successfully: `/Users/robindieker/Desktop/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-b07c37cc2f7b5503/build-script-build` (exit status: 1) --- stdout cargo:rerun-if-env-changed=TAURI_CONFIG cargo:rerun-if-changed=tauri.conf.json cargo:rustc-check-cfg=cfg(desktop) cargo:rustc-cfg=desktop cargo:rustc-check-cfg=cfg(mobile) cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_APP_NAME=pe cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_PREFIX=screenpi cargo:rustc-check-cfg=cfg(dev) cargo:PERMISSION_FILES_PATH=/Users/robindieker/Desktop/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-e160e3b75eb0e726/out/app-manifest/**app**-permission-files cargo:rerun-if-changed=capabilities cargo:rustc-env=TAURI_ENV_TARGET_TRIPLE=aarch64-apple-darwin resource path `screenpipe-aarch64-apple-darwin` doesn't exist warning: build failed, waiting for other jobs to finish... Error failed to build app: failed to build app user@192-168-2-186 screenpipe-app-tauri %
> 
> Did you follow the steps? First, you need to install the `screenpipe` CLI.
> 
> ```shell
> cd screenpipe
> cargo build --release --features metal
> ```
> 
> Then create the link:
> 
> ```shell
> ln -s ./target/release/screenpipe screenpipe-app-tauri/src-tauri/screenpipe-aarch64-apple-darwin
> ```

Do you still need to run this @0smboy ? Maybe this is my issue...cargo build gives me a build error. 
error: failed to run custom build command for `libsamplerate-sys v0.1.12`

**Comment by 0smboy** [comment]
> > > had to do a bit of manual work to get this to work;
> 
> > > 
> 
> > > 1. bun isn't installed - had to install it manually by running curl -fsSL https://bun.sh/install | bash
> 
> > > 2. installed Xcode command line tools just for being safe
> 
> > > 3. under "ok lets build it" there has to be a "cd screenpipe" first
> 
> > > 4. "bun i" misses a sudo before it
> 
> > > 
> 
> > > still getting error
> 
> > > error: failed to run custom build command for `screenpipe-app v0.2.79 (/Users/user/Desktop/screenpipe/screenpipe-app-tauri/src-tauri)`
> 
> > > Caused by: process didn't exit successfully: `/Users/robindieker/Desktop/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-b07c37cc2f7b5503/build-script-build` (exit status: 1) --- stdout cargo:rerun-if-env-changed=TAURI_CONFIG cargo:rerun-if-changed=tauri.conf.json cargo:rustc-check-cfg=cfg(desktop) cargo:rustc-cfg=desktop cargo:rustc-check-cfg=cfg(mobile) cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_APP_NAME=pe cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_PREFIX=screenpi cargo:rustc-check-cfg=cfg(dev) cargo:PERMISSION_FILES_PATH=/Users/robindieker/Desktop/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-e160e3b75eb0e726/out/app-manifest/**app**-permission-files cargo:rerun-if-changed=capabilities cargo:rustc-env=TAURI_ENV_TARGET_TRIPLE=aarch64-apple-darwin resource path `screenpipe-aarch64-apple-darwin` doesn't exist warning: build failed, waiting for other jobs to finish... Error failed to build app: failed to build app user@192-168-2-186 screenpipe-app-tauri %
> 
> > 
> 
> > Did you follow the steps? First, you need to install the `screenpipe` CLI.
> 
> > 
> 
> > ```shell
> 
> > cd screenpipe
> 
> > cargo build --release --features metal
> 
> > ```
> 
> > 
> 
> > Then create the link:
> 
> > 
> 
> > ```shell
> 
> > ln -s ./target/release/screenpipe screenpipe-app-tauri/src-tauri/screenpipe-aarch64-apple-darwin
> 
> > ```
> 
> 
> 
> Do you still need to run this @0smboy ? Maybe this is my issue...cargo build gives me a build error. 
> 
> error: failed to run custom build command for `libsamplerate-sys v0.1.12`
maybe you should install xcode- select first
```bash
xcode-select --install

**Comment by akeslo** [comment]
Getting closer
<img width="638" alt="image" src="https://github.com/user-attachments/assets/7a5c7538-00e5-43ae-af4e-7cc978455127">

**Comment by 0smboy** [comment]
> > > had to do a bit of manual work to get this to work;
> > > 
> > > 1. bun isn't installed - had to install it manually by running curl -fsSL https://bun.sh/install | bash
> > > 2. installed Xcode command line tools just for being safe
> > > 3. under "ok lets build it" there has to be a "cd screenpipe" first
> > > 4. "bun i" misses a sudo before it
> > > 
> > > still getting error
> > > error: failed to run custom build command for `screenpipe-app v0.2.79 (/Users/user/Desktop/screenpipe/screenpipe-app-tauri/src-tauri)`
> > > Caused by: process didn't exit successfully: `/Users/robindieker/Desktop/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-b07c37cc2f7b5503/build-script-build` (exit status: 1) --- stdout cargo:rerun-if-env-changed=TAURI_CONFIG cargo:rerun-if-changed=tauri.conf.json cargo:rustc-check-cfg=cfg(desktop) cargo:rustc-cfg=desktop cargo:rustc-check-cfg=cfg(mobile) cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_APP_NAME=pe cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_PREFIX=screenpi cargo:rustc-check-cfg=cfg(dev) cargo:PERMISSION_FILES_PATH=/Users/robindieker/Desktop/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-e160e3b75eb0e726/out/app-manifest/**app**-permission-files cargo:rerun-if-changed=capabilities cargo:rustc-env=TAURI_ENV_TARGET_TRIPLE=aarch64-apple-darwin resource path `screenpipe-aarch64-apple-darwin` doesn't exist warning: build failed, waiting for other jobs to finish... Error failed to build app: failed to build app user@192-168-2-186 screenpipe-app-tauri %
> > 
> > 
> > Did you follow the steps? First, you need to install the `screenpipe` CLI.
> > ```shell
> > cd screenpipe
> > cargo build --release --features metal
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then create the link:
> > ```shell
> > ln -s ./target/release/screenpipe screenpipe-app-tauri/src-tauri/screenpipe-aarch64-apple-darwin
> > ```
> 
> Do you still need to run this @0smboy ? Maybe this is my issue...cargo build gives me a build error. error: failed to run custom build command for `libsamplerate-sys v0.1.12`

maybe you should install xcode- select first
```bash
xcode-select --install

**Comment by louis030195** [comment]
hey this shouldn't be that hard, check this:

https://github.com/mediar-ai/screenpipe/tree/main/screenpipe-app-tauri

**Comment by dmnkf** [comment]
@louis030195 

I am just struggling a bit letting the app access the cli, currently I have to manually start the cli, but then it works until I make any changes to the config.

Is this intended? I just followed the Readme and ensured that all dependencies are resolved.

**Comment by louis030195** [comment]
@dmnkf whats the error?

**Comment by torablien** [comment]
I was able to get the app to build and launch but status is red with video and audio in error. I confirmed the app has Screen and System Audio Recording permissions and restarted.

I tried manually starting the screenpipe backend but I see these error logs:
```sh
ERROR: dyld[79274]: Library not loaded: @rpath/../Frameworks/libscreenpipe_arm64.dylib
ERROR:   Referenced from: <73E3AAE5-DDA9-3F46-B0F9-EDB916F3A16C> /Applications/screenpipe.app/Contents/MacOS/screenpipe
ERROR:   Reason: no LC_RPATH's found
```

**Comment by akeslo** [comment]
> hey this shouldn't be that hard, check this:
> 
> https://github.com/mediar-ai/screenpipe/tree/main/screenpipe-app-tauri

This did it for me, thanks!

**Comment by Glavin001** [comment]
Successfully built screenpipe CLI and app (with only minor personal setup issues). Followed the getting started instructions including for the screenpipe-app-tauri as @louis030195 mentioned. Update to docs in https://github.com/mediar-ai/screenpipe/pull/390 

Hopefully this works for everyone, docs can be updated to be clear, and this issue can be resolved. 😃

**Comment by pannous** [comment]
Finished `release` profile [optimized] target(s) in 1m 21s
    
    script fails at `chmod: ./target/release/screenpipe: No such file or directory`

**Comment by XInTheDark** [comment]
> Both the shell script and the "getting started locally" instructions built and launch but the app shows status is red with video and audio in error. I confirmed the app has Screen and System Audio Recording permissions and restarted.
> 
> I tried manually starting the screenpipe backend but I see these error logs:
> 
> ```shell
> ERROR: dyld[79274]: Library not loaded: @rpath/../Frameworks/libscreenpipe_arm64.dylib
> ERROR:   Referenced from: <73E3AAE5-DDA9-3F46-B0F9-EDB916F3A16C> /Applications/screenpipe.app/Contents/MacOS/screenpipe
> ERROR:   Reason: no LC_RPATH's found
> ```

This exact same error also occurs for me! Anyone managed to fix?

**Comment by K4CZP3R** [comment]
> I fixed it manually by running
> 
> ```
> install_name_tool -add_rpath @executable_path/../Frameworks /Applications/screenpipe.app/Contents/MacOS/screenpipe
> ```
> 
> I noticed that the screenpipe-app has the proper links
> 
> ```
> ➜  MacOS otool -l ./screenpipe-app | grep -A2 LC_RPATH
>           cmd LC_RPATH
>       cmdsize 48
>          path @executable_path/../Frameworks (offset 12)
> ```
> 
> I am guessing it has something to do with the fact that we build screenpipe separately and the pre-install script copies it over. Not really sure though, OSX builds and deployable binaries is a little beyond me (already deeply relying on chatgpt here)

This solved my issue!

**Comment by louis030195** [comment]
if you guys see anything to add to the docs feel free to send a PR, i will send you a tip!

**Comment by yuanyowwu** [comment]
> > I fixed it manually by running
> > ```
> > install_name_tool -add_rpath @executable_path/../Frameworks /Applications/screenpipe.app/Contents/MacOS/screenpipe
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I noticed that the screenpipe-app has the proper links
> > ```
> > ➜  MacOS otool -l ./screenpipe-app | grep -A2 LC_RPATH
> >           cmd LC_RPATH
> >       cmdsize 48
> >          path @executable_path/../Frameworks (offset 12)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am guessing it has something to do with the fact that we build screenpipe separately and the pre-install script copies it over. Not really sure though, OSX builds and deployable binaries is a little beyond me (already deeply relying on chatgpt here)
> 
> This solved my issue!

FYI - I used llvm-install-name-tool instead. Honestly don't know why, but install_name_tool returned libc++abi: terminating due to uncaught exception of type std::runtime_error: codesign_failed: 0 for me.

Maybe due to clang vs llvm?
