### ISSUE TITLE
Selection of screens or audio devices rapidly toggles on its own in settings

### ISSUE THREAD

**Issue by meltiso** [mediar-ai/screenpipe#384]
Hey, I'm running into a bug when selecting screens or audio devices in the settings. When I try to select one, it automatically and rapidly toggles between selected and deselected on its own. This makes it really hard to set up the devices properly.
I'm on Windows 11.

https://github.com/user-attachments/assets/68b85b94-197a-4cb7-bedf-6b741b09deb5

**Comment by louis030195** [comment]
sorry about that, releasing fix now

**Comment by louis030195** [comment]
@meltiso please update to `0.2.80` it should be fixed 🙏

**Comment by meltiso** [comment]
@louis030195 Thanks I confirm it's fixed!
