### ISSUE TITLE
No chat interface in desktop gui

### ISSUE THREAD

**Issue by jeffhaskin** [mediar-ai/screenpipe#385]
Built from source on macos 14.

![image](https://github.com/user-attachments/assets/ed5a86cb-9967-4654-a966-87379a0e6a5a)

I don't see any way to open the chat interface, and it always opens to this "query" interface by default. How do I get to the chat interface?

**Comment by Glavin001** [comment]
Confirmed, after building the app from source and seeing this same page, I needed to search then successfully saw chat. I think this issue can be closed?

**Comment by louis030195** [comment]
yes

we're going to make it more AI first in the future but right now LLM are too drunk to make proper function calling
