### ISSUE TITLE
$100 - implement "update now" in tray menu using new icon 

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#386]
<img width="273" alt="image" src="https://github.com/user-attachments/assets/cef053ce-7261-4f28-bc79-7828b6d2d70d">

[Tray Icons Outlined Update 2.zip](https://github.com/user-attachments/files/17194998/Tray.Icons.Outlined.Update.2.zip)

/bounty 100

definition of done:
- when an update is available show the icon with down arrow 
- when i click on tray menu i see the menu "update now" which trigger the update using crabnebula api
- it works on macos, windows, no crash, or weird issues

**Comment by EzraEllette** [comment]
/attempt #386

1. On Tray open check if an update is available.
2. Add Update Now / "You are up to date" / "checking for updates" to tray (Maybe include version numbers?)
3. If update now is clicked: emit an event for `appUpdateRequested`.
4. In the event handler call `update.downloadAndInstall()`.
5. After successful download and install. Either prompt for restart, or restart automatically.
6. On launch after update, send update success notification.

**Comment by EzraEllette** [comment]
I have the functionality implemented with an initial update check on launch, and another check every hour. Updates work flawlessly on my m1 macbook. I'll have to write some tests, or manually test on linux and windows.

I am able to switch the icons in the dev environment, but release icon switching is failing.

I would appreciate some official icons to use.
