### ISSUE TITLE
Feature request: Ingest screen captures

### ISSUE THREAD

**Issue by DIGist** [mediar-ai/screenpipe#400]
While we wait for wayland support, I've been running obs to capture audio/video/my screen. It would be good if there was an option to ingest screen captures into screenpipe in the mean time. 

Thanks!

**Comment by DIGist** [comment]
An api call to upload the files in batch. It would allow programmatic access for people in the future as well. In my specific case, using OBS to capture screens would let me scope the audio/video notes to just the topic of interest instead of all desktop activity.

**Comment by louis030195** [comment]
nice yeah also would fix this #102 

and also allows syncing media from phone recording, wearables etc

**Comment by DIGist** [comment]
So thinking about it further, Yes, a CLI option to --ingest would work, for the desktop app you might have a upload button/control. Or you might have an api endpoint available from the CLI or desktop to allow other automations to or devices to push captures from.. As mentioned above Screencapture on Android could be used to capture and then sent for ingestion to allow people to summarize/search/parse capture information.

**Comment by louis030195** [comment]
#467 duplicate

**Comment by DIGist** [comment]
I see this was closed as duplicate/completed.. The little I can find on the feature is a command line switch that says:
"Add video files to existing screenpipe data (OCR only) - DOES NOT SUPPORT AUDIO"

Any advice to handle audio as well? transcribde on my own a port in?  splie the audio from the video file and upload for diarization? and other documentation i should look at to see if I'm missing any details?

**Comment by louis030195** [comment]
> I see this was closed as duplicate/completed.. The little I can find on the feature is a command line switch that says: "Add video files to existing screenpipe data (OCR only) - DOES NOT SUPPORT AUDIO"
> 
> Any advice to handle audio as well? transcribde on my own and port it in? split the audio from the video file and upload for diarization? Any other documentation i should look at to see if I'm missing any details?



we have an endpoint to add transcription here

https://github.com/mediar-ai/screenpipe/blob/a2c6ed3f47c51b5c88045fefd57b23caf306a7f9/screenpipe-server/src/server.rs#L1258

what kind of use case would you like?

send raw audio data?

send transcription?

would you use local or cloud?

let me know any details, i can create bounty for it
