### ISSUE TITLE
Email Spam

### ISSUE THREAD

**Issue by Wingysam** [mediar-ai/screenpipe#405]
Hi, I starred the repo then received marketing email at my GitHub address stating that I "opted-in to receive updates from Mediar, Inc". Starring a GitHub repo is not consent. If you would like a mailing list (which is a great idea, just make it actually opt-in), put a sign-up field on your website rather than harvesting emails from non-consenting GitHub Stargazers. Thank you.

**Comment by jniebuhr** [comment]
Had the same experience, immediately made me hate this project and should probably report them to Github for this weird practice

**Comment by bee-san** [comment]
Fairly certain this pratice is illegal in the EU. I have reported them, I suggest you do the same.

If anyone can find out how to report this spam to https://loops.so so they can forcibly stop this company from harvesting data (how funny an AI company would do that against your will) it would be much appreciated.

**Comment by jniebuhr** [comment]
Just by email to [help@loops.so](mailto:help@loops.so), i reported them on Github too

**Comment by m13v** [comment]
guys, sorry about this—we thought you liked the project and were okay with receiving newsletter since your email address was public on github. it was a misunderstanding on our part, and it won’t happen again

**Comment by Wingysam** [comment]
Thank you. I do like the project and want to receive announcements, but not unsolicited through email. I’m in your Discord so I’ll get any announcements there. Has everyone you added from the GitHub Stargazer list been removed?On Oct 2, 2024, at 11:07 AM, Matthew Diakonov ***@***.***> wrote:﻿
guys, sorry about this—we thought you liked the project and were okay with receiving newsletter since your email address was public on github. it was a misunderstanding on our part, and it won’t happen again

**Comment by Wingysam** [comment]
@m13v The email spam hasn't stopped. Can you please remove the people you non-consensually added from your email list? Thanks.

**Comment by sshahs** [comment]
> guys, sorry about this—we thought you liked the project and were okay with receiving newsletter since your email address was public on github. it was a misunderstanding on our part, and it won’t happen again

To the ICO we go

**Comment by gnorbsl** [comment]
"Sorry we got caught, we will not remove you from the spam list though"
