### ISSUE TITLE
Unable to add Ollama Model to Screenpipe App

### ISSUE THREAD

**Issue by ByteMirror** [mediar-ai/screenpipe#408]
I am trying to use llama3.1:latest as a model in Screenpipe on my Mac using the newest MacOS version.
I am running on a M1 Pro MacBook Pro.

I am getting this error when I try to prompt the AI:
<img width="416" alt="image" src="https://github.com/user-attachments/assets/c26057de-4ca7-44ce-ae1e-dfffe43274b7">
<img width="269" alt="image" src="https://github.com/user-attachments/assets/4969d112-3b47-4c7b-a662-0e0d98fad465">

Those are my settings

Am I doing something wrong or is this a bug?

**Comment by louis030195** [comment]
try llama3.1 in the ai model name

**Comment by ByteMirror** [comment]
> try `llama3.1` in the ai model name
> 
> and
> 
> `http://localhost:11434/api` in url

Sadly still getting the error. Also tried with OpenAI API and doesn't work either. Is there somewhere I can read out the specific error message?

Thanks in advance <3

**Comment by louis030195** [comment]
> > try `llama3.1` in the ai model name
> > and
> > `http://localhost:11434/api` in url
> 
> Sadly still getting the error. Also tried with OpenAI API and doesn't work either. Is there somewhere I can read out the specific error message?
> 
> Thanks in advance <3

yes

right click in the app background -> inspect -> console

**Comment by louis030195** [comment]
ups url is `http://localhost:11434/v1` it seem

**Comment by louis030195** [comment]
my settings 

<img width="1312" alt="Screenshot 2024-10-02 at 11 08 10" src="https://github.com/user-attachments/assets/5750e844-162f-4929-8157-f637f5675a5d">



<img width="1312" alt="Screenshot 2024-10-02 at 11 07 58" src="https://github.com/user-attachments/assets/6a553b02-78ec-4908-920e-ca634a47e270">

**Comment by ByteMirror** [comment]
<img width="736" alt="image" src="https://github.com/user-attachments/assets/402386bb-5079-4028-9fbe-e1a5835a8216">


In other apps I am using this URL for llama3.1 from ollama: http://localhost:11434


As you can see above even though I have this url without any path behind the port the frontend still seems to call the /chat/completions url and that results in a 404. 
Is it possible to change this behaviour?

**Comment by louis030195** [comment]
@ByteMirror you need to use `http://localhost:11434/v1` in the url

**Comment by ByteMirror** [comment]
Ah okay thanks. For some reason it does not seem to work however. However, I saw in your screenshot that you provided an API key for the local ollama model? 
Is that a necessity? Because I did not even know I could generate API keys for local ollama models

**Comment by louis030195** [comment]
no, it was just for openai, not necessary

**Comment by louis030195** [comment]
> Ah okay thanks. For some reason it does not seem to work however. However, I saw in your screenshot that you provided an API key for the local ollama model? Is that a necessity? Because I did not even know I could generate API keys for local ollama models

whats the error with the new URL?

**Comment by ByteMirror** [comment]
<img width="752" alt="image" src="https://github.com/user-attachments/assets/a2cf16cd-c354-4a12-b86a-45becad0b85e">
still the same sadly

**Comment by louis030195** [comment]
> <img alt="image" width="752" src="https://private-user-images.githubusercontent.com/96124427/372986277-a2cf16cd-c354-4a12-b86a-45becad0b85e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4OTM3MDQsIm5iZiI6MTcyNzg5MzQwNCwicGF0aCI6Ii85NjEyNDQyNy8zNzI5ODYyNzctYTJjZjE2Y2QtYzM1NC00YTEyLWI4NmEtNDViZWNhZDBiODVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE4MjMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZTNkMWExYTRlZWE2MTA1MTRkMDE4Mjk0NTY3NDhhZDZmMDAwYzFiZmI2MjcyNDZiMGMzMGYxZDk4YTZiNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4gZ5gWaxooEssWjinNZVnwUFWNeS1S340j2lNR_sPr8"> still the same sadly

can you share your ai settings?

**Comment by louis030195** [comment]
hmm
can you click on "new chat" and try again

**Comment by ByteMirror** [comment]
thanks for the quick troubleshooting! 
Really cool project!

**Comment by ianmiell** [comment]
I am having the same problems, but don't see a 'new chat' button?
