### ISSUE TITLE
$200 - embedded llama3.2 

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#409]
definition of done:
- can use llama3.2 in screenpipe through openai api compatible api (streaming or non streaming)
- behind "llm" feature flag
- more than 50 token per second
- works with metal, cuda

most of this i already done, just need some additional plumbing and also felt like llama3.2 was slow for some reason with candle 

/bounty 200

**Comment by EzraEllette** [comment]
Do you have a basis 50 tokens / second? I think it will take some serious work to get performance that high.

**Comment by EzraEllette** [comment]
I can set up the api, but the requirement of 50t/s might be unattainable without some magic. 

Here's a decent article about reducing decoding time.

https://arxiv.org/abs/2402.02057

**Comment by louis030195** [comment]
my benchmark was when i was using  https://github.com/mlc-ai/mlc-llm i had 50 token / s using llama3.1 in the browser

**Comment by EzraEllette** [comment]
I'm getting 60/second using `meta-llama/Llama-3.2-1B-Instruct`. I didn't consider to use a 1B model, but if that's fine, I'll run some more tests and see just how fast we can make it.

**Comment by louis030195** [comment]
> I'm getting 60/second using `meta-llama/Llama-3.2-1B-Instruct`. I didn't consider to use a 1B model, but if that's fine, I'll run some more tests and see just how fast we can make it.

great

**Comment by EzraEllette** [comment]
Can you confirm which model to use? For example we might not want to use instruct for conversation. I have a good balance of quality and performance with a quantized 3B model.

"Make it work. Make it right. Make it fast."

**Comment by louis030195** [comment]
> Can you confirm which model to use? For example we might not want to use instruct for conversation. I have a good balance of quality and performance with a quantized 3B model.
> 
> "Make it work. Make it right. Make it fast."


hmm idk

i think we will use a lot for small tasks not necessarily streaming and less likely conversation 

quantize would be good, idk how to quantize models for candle usage atm, shouldnt be too hard 

btw we need this feature for today for this https://youtube.com/shorts/O28f9z0aZVk

**Comment by EzraEllette** [comment]
Given that context, it would be best for us to use `meta-llama/Llama-3.2-1B-Instruct` since it is fine tuned to complete tasks and follow instructions. I'll set up the API and make a PR

**Comment by EzraEllette** [comment]
I want to make sure you know I am actively working on this. I'm putting a lot of effort into ensuring that the solution is extensible.

**Comment by EzraEllette** [comment]
<img width="957" alt="Screenshot 2024-10-05 at 6 29 29 PM" src="https://github.com/user-attachments/assets/efb64ea0-c6bc-4e84-9477-0bf97fd82a0d">

**Comment by EzraEllette** [comment]
Not streaming

**Comment by EzraEllette** [comment]
I'm adding a `tps` property to the usage details.

**Comment by EzraEllette** [comment]
<img width="914" alt="Screenshot 2024-10-05 at 6 33 03 PM" src="https://github.com/user-attachments/assets/d113f6f2-cbf1-4397-8d1d-6c11023ed472">
