### ISSUE TITLE
[Windows Install/FFMPEG Issue] Failed to Build ffmpeg-sys-next with Cargo on Windows 10

### ISSUE THREAD

**Issue by Fayehung** [mediar-ai/screenpipe#41]
Let me preface this post by sharing how insanely captivating this project was to see, I ain't going to lie, I'm a newbie probably delving into something way out of my knowledge base, I'm not even sure if this application will run on my current system, but it's too enticing not to try. Sorry for the wall of text, I've spent the last 12 hours trying to overcome this, and I am willing to spend another week if necessary. 

#### System Information:
- **Operating System:** Windows 10
- **Development Tools:**
  - Visual Studio 2022 Build Tools
  - vcpkg package manager
  - Cargo (Rust package manager)
  - FFmpeg (2 different sources attempted)
  - CUDA installed dependencies installed.
- **Hardware Specs:**
  - **CPU:** AMD Ryzen 5 5600
  - **RAM:** 16GB @ 3200MHz
  - **GPU:** NVIDIA RTX 2060 Super

#### Problem Description:
Attempting to build a Rust project with the `ffmpeg-sys-next` crate using Cargo results in the following error:

```
error: failed to run custom build command for `ffmpeg-sys-next v7.0.0`

Caused by:
  process didn't exit successfully: `D:\Pothon Projects\screen-pipe\target\release\build\ffmpeg-sys-next-50830d51493a5d18\build-script-build` (exit code: 101)
```

#### Steps Taken to Troubleshoot and Resolve the Issue:

1. **Installed Visual Studio Build Tools:**
   - Installed Visual Studio Build Tools with the necessary components for C++ development.
   - Confirmed the installation path for `cl.exe` (Visual C++ compiler).

2. **Set Up Environment Variables:**
   - Set up environment variables for the Visual C++ tools.
   - Added the necessary paths to the system `Path` variable.

3. **Installed vcpkg and FFmpeg:**
   - Installed vcpkg and set it up.
   - Used vcpkg to install FFmpeg:
     ```shell
     .\vcpkg.exe install ffmpeg
     .\vcpkg.exe integrate install
     ```
   - Confirmed that FFmpeg was installed via vcpkg and available in the `x64-windows` triplet.

4. **Configured Environment Variables for FFmpeg:**
   - Set the `VCPKG_ROOT` and `PKG_CONFIG_PATH` environment variables:
     ```powershell
     $env:VCPKG_ROOT="D:\vcpkg"
     $env:PKG_CONFIG_PATH="D:\vcpkg\installed\x64-windows\lib\pkgconfig"
     ```

5. **Attempted to Build the Project Again:**
   - Ran the build command in PowerShell:
     ```powershell
     cargo build --release --features cuda
     ```

6. **Encountered the Same Error:**
   Despite the steps above, the build failed with the same error message. The output indicated that the build script could not find the `ffmpeg` libraries, despite `vcpkg` confirming the installation of FFmpeg.

#### Additional Details:
- The `vcpkg` installation path is `D:\vcpkg`.
- The `ffmpeg` libraries are located in `D:\vcpkg\installed\x64-windows\lib\pkgconfig`.
- Environment variables were set in the PowerShell session before running the build command, and permanently through Environment Vars. 
- Changed from the FFMPEG source mentioned in the readme for Windows to the latest version found here https://github.com/BtbN/FFmpeg-Builds/releases, but no cigar.

#### Error Message:
```
error: failed to run custom build command for `ffmpeg-sys-next v7.0.0`

Caused by:
  process didn't exit successfully: `D:\Pothon Projects\screen-pipe\target\release\build\ffmpeg-sys-next-50830d51493a5d18\build-script-build` (exit code: 101)
```

#### Request for Assistance:
---

Again, I'm a noob but this application lit a fire for me regarding ideas, and I'm eager to make it work. I've tried changing the FFmpeg release, and the specs I've shared as well. Looking for guidance on how to resolve the issue where the `ffmpeg-sys-next` build script cannot find the `ffmpeg` libraries installed via `vcpkg`. Any insights or suggestions for further troubleshooting steps would be greatly appreciated.
If I'm missing something absurd or any other info is necessary, let me know, and again, congrats on an amazing project, hope I'm not wasting anyone's time. 
---

**Comment by louis030195** [comment]
Hey @Fayehung thanks a lot for the enthusiasm, really appreciate the effort as we're trying to make this easier to install for all OSes!

I am not super familiar with windows but I'm not sure you need visual studio code c++ etc.

Did you try to install ffmpeg based on the official website?

https://www.ffmpeg.org/download.html#build-windows

I think then the `ffmpeg` command should be available in the terminal so that `ffmpeg-sys-next` would detect it. On Linux / Mac it's PATH which I think is similar on windows.

What about we have a call so I can help you install screenpipe?
This is my calendar scheduler:
https://cal.com/louis030195/screenpipe

**Comment by Fayehung** [comment]
That sounds amazing @louis030195, let me clear my environment and dig a bit more on this next week, just so I can have an outline of what the issue is in its essence to streamline the call, I'm pretty sure I'm doing something wrong, especially not being super familiar with rust. Thanks for the prompt response dude, I'll get back to you as soon as possible. Cheers.

**Comment by louis030195** [comment]
@Fayehung any news? would appreciate feedback, to simplify install on windows or screenpipe itself 🙏

**Comment by Fayehung** [comment]
@louis030195 first of all, my apologies for leaving you hanging, had a few projects on the backburner and had to do a whole shift of environment, will reattempt the install on a clean windows machine this week, and report back to ya, if I mess it up somehow, I'll take you up on that offer for the 15 mins sesh, next week, you have my word!

**Comment by Fayehung** [comment]
Also, it was most likely an issue with my environment variables regarding the path for FFMPEG, since I was able to use it in a different scenario in A111 and batch editing.

**Comment by louis030195** [comment]
@Fayehung hey FYI we released a windows desktop app -> https://screenpi.pe/onboarding
