### ISSUE TITLE
$200 - make a youtube video about screenpipe and get > 5000 views

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#410]
$200 - make a youtube video about screenpipe and get > 5000 views

here's how you can get more views usually:

- show face with camera
- sound is clear
- screenpipe app used
- minimum length 5-15 minutes
- show website if more for non technical people, otherwise the repository
- share on different places
- have already a channel with subscribers

this is repeatable bounty, you will be rewarded through @algora-pbc when commenting your video link matching the criterias

ideas of videos:
- non technical: presentation of the product, use cases, etc.
- technical: explain how to [build pipes](https://docs.screenpi.pe/), build one and show the value ...

/bounty 200

**Comment by twilwa** [comment]
/attempt #410

Sounds like fun to me! If you or Matt want to come on stream sometime and chat about how you made it happen, I did that once with the Sweep guys and it went pretty well. I'm smol on yt but I keep tryin. :)
