### ISSUE TITLE
Coreaudio fails building on mac

### ISSUE THREAD

**Issue by jsinge97** [mediar-ai/screenpipe#411]
error: failed to run custom build command for `coreaudio-sys v0.2.16`

Caused by:
  process didn't exit successfully: `/Users/js/consulting_work/clients/trilogy/screenpipe/target/release/build/coreaudio-sys-c47eb2829d5a82bb/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=COREAUDIO_SDK_PATH
  cargo:rustc-link-lib=framework=AudioUnit
  cargo:rustc-link-lib=framework=CoreAudio
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  thread 'main' panicked at /Users/js/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.70.1/lib.rs:622:27:
  Unable to find libclang: "the `libclang` shared library at /opt/homebrew/Cellar/llvm/18.1.8/lib/libclang.dylib could not be opened: dlopen(/opt/homebrew/Cellar/llvm/18.1.8/lib/libclang.dylib, 0x0005): tried: '/opt/homebrew/Cellar/llvm/18.1.8/lib/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/llvm/18.1.8/lib/libclang.dylib' (no such file), '/opt/homebrew/Cellar/llvm/18.1.8/lib/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by louis030195** [comment]
@jsinge97 macos version? hardware?

**Comment by louis030195** [comment]
@jsinge97 any news?
