### ISSUE TITLE
$200 - (typescript/react only) create proper onboarding

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#412]
when the user open the app for the first time it should explain a few things about screenpipe and what to be careful with, what is experimental, how to get started quickly

definition of done:
- when the user first open the app it should guide it through setting up API keys if user wants to use the chat or just leave empty if just using search without AI
- also should mention does not need API key when using ollama or such, also should guide through using ollama clearly
- maybe some screenshot or something to show use cases of search 

requirements are mostly unclear atm, be creative, bring great experience, if necessary do a video or write a good script and i can do the video based on this script and we'll embed in the app

should be typescript/react only 

/bounty 200

**Comment by louis030195** [comment]
plz make suggestion first before shipping if possible, like excalidraw or something (take inspiration on great onboarding experiences)

**Comment by nitikabaghel** [comment]
I'd like to work on this; will update in sometime with a workable prototype
/attempt #412

**Comment by tribhuwan-kumar** [comment]
Here's what I'd like to implement, when the user first time opens the app, it'll show an intro video discussing about features and uses of screenpipe in first slide & in the second slide it'll explain the user how is he like to use screenpipe with AI or without AI then it'll guide it through setting up api keys, it'll also explain if user wants to use ollama, I'm thinking to add these kind of [pop ups](https://blog-static.userpilot.com/blog/wp-content/uploads/2018/12/interactive-walkthrough-free-trial-conversion-rate.gif) for first time users explaining about use case of search, status options, or in anything which is explainable.

/attempt #412

**Comment by hunxjunedo** [comment]
@louis030195 this is what I've started working on, this is nothing but a basic UI, media and video are yet to be added. I'm constantly working on adding these things. Also the introduction to searching, and chatting etc. are yet to be added. 

[Screencast from 2024-10-03 19-48-51.webm](https://github.com/user-attachments/assets/11acdab9-d0de-4fe3-bff7-5036a0f18a84)


for the introduction, I'd prefer either popups once the onboarding window is closed, or use GIFs to guide through the steps to perform simple tasks. What think would be best for the video is that we take general use case and guide through the video how the user can easily achieve that.

It will  require further collaboration with you, I'd appreciate connecting on Discord and getting assigned.

**Comment by tribhuwan-kumar** [comment]
@hunxjunedo dude just copied my idea, never mind!

**Comment by hunxjunedo** [comment]
Lol it was too general to be unique. Literally app nowadays does that 😀

**Comment by tribhuwan-kumar** [comment]
> Lol it was too general to be unique. Literally every app nowadays follows the dame design 😀 . It's cool, I'd be more than happy collaborating on this.

me too, i'd also love to collaborate!

**Comment by tribhuwan-kumar** [comment]
[here](https://excalidraw.com/#json=eAPZJ7pA4OpBwbR0YFhQX,XK3q4ilxy5RLxZ2vwRPVmQ) is the workflow, I'd like to follow 
@louis030195 what do you think ?

**Comment by tribhuwan-kumar** [comment]
@louis030195 
<details>

  <summary>3 slides are done as the figma design, a PR will open soon</summary>
  
  ![image](https://github.com/user-attachments/assets/00a64d3a-ea60-4ec4-96e8-cb8f73c546dc)
  ![image](https://github.com/user-attachments/assets/817434ca-c89a-4fc4-a60c-90d12ba89804)
  ![image](https://github.com/user-attachments/assets/dd986514-6cfe-4b94-8f2b-f0c58f32caa1)
  
</details>
