### ISSUE TITLE
windows install screenpipe didnt work

### ISSUE THREAD

**Issue by arghunter** [mediar-ai/screenpipe#416]
When i run the cargo build I get this error. I'm not sure where to get cl.exe.  How do I fix this?
![image](https://github.com/user-attachments/assets/2b490a55-1681-4e33-8d76-e8b92ed98c94)

**Comment by andreivettor** [comment]
@arghunter I got past that. You just have to link cl.exe from your local Visual Studio install. Mine was at: 

> C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64

Unfortunately it's not the only path you need to configure along the way.
I spent 2 hours trying to build this on windows only to get stuck on the last pre_build.js script messing up and I can't work it out.

**Comment by arghunter** [comment]
is it the tesseract step failing?

Thanks, I'll try it soon

**Comment by andreivettor** [comment]
Actually yes. Do you know how to fix it?

**Comment by arghunter** [comment]
https://github.com/mediar-ai/screenpipe/issues/387#issuecomment-2384614244

This person appeared to run into a similar error ad got past it.

**Comment by arghunter** [comment]
@andreivettor I think if figured it out so if its telling u it already has tesseract setup go to V:\projects\screenpipe\screenpipe-app-tauri\src-tauri  and delete `tesseract-setup.exe`  (also uninstall tesseract if u manually installed it). Then run the prebuild as admin. it seems to work and is compiling the final exe now. Warning it hangs for a while

**Comment by andreivettor** [comment]
Cool. I updated the solution above and compiled the exe too.
