### ISSUE TITLE
[bug] Desktop app only supports debian based 

### ISSUE THREAD

**Issue by tonybenoy** [mediar-ai/screenpipe#419]
**describe the bug**
As the desktop app is build it used apt get to install dependencies. This breaks in other distros like Arch or Fedora

**to reproduce**
steps to reproduce the behavior:

Building the desktop app fails as following
``` 07 packages installed [31.58s]
cwd /home/user/src/screenpipe/screenpipe-app-tauri/src-tauri
sudo: apt-get: command not found
 95 | 	cmake: 'C:\\Program Files\\CMake\\bin',
 96 | }
 97 | 
 98 | /* ########## Linux ########## */
 99 | if (platform == 'linux') {
100 | 	// Install APT packages
                     ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "sudo: apt-get: command not found\n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at module code (/home//user/src/screenpipe/screenpipe-app-tauri/scripts/pre_build.js:100:10)

Bun v1.1.29 (Linux x64)
```

**expected behavior**
Ideally it should work independent of distro

**system information:**
 - os: [linux]
 - os version: [Arch Linux]

**Comment by louis030195** [comment]
thanks for the issue @tonybenoy would love any help to make this work on other distros!

**Comment by tonybenoy** [comment]
> thanks for the issue @tonybenoy would love any help to make this work on other distros!

Sure! Just to understand why do you want to hard code the dependencies in the pre_build.js rather than having the user install them manually? In the case of Arch you could package it as a [pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=screenpipe#n9) with dependencies and have instructions on how to install for distros. If not then maybe splitting it like this based on the repos (you'd still have to maintain separate list of packages for different distos in `screenpipe/screenpipe-app-tauri/src-tauri/tauri.linux.conf.json` are the package names differ) 
```async function installPackages(packageManager, packages) {
	if (packageManager === 'apt') {
		await $`sudo apt-get update`;
		for (const pkg of packages) {
			await $`sudo apt-get install -y ${pkg}`;
		}
	} else if (packageManager === 'dnf' || packageManager === 'yum') {
		for (const pkg of packages) {
			await $`sudo ${packageManager} install -y ${pkg}`;
		}
	} else if (packageManager === 'pacman') {
		await $`sudo pacman -Syu`;
		for (const pkg of packages) {
			await $`sudo pacman -S --noconfirm ${pkg}`;
		}
	}
}
````

**Comment by louis030195** [comment]
> > thanks for the issue @tonybenoy would love any help to make this work on other distros!
> 
> Sure! Just to understand why do you want to hard code the dependencies in the pre_build.js rather than having the user install them manually? In the case of Arch you could package it as a [pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=screenpipe#n9) with dependencies and have instructions on how to install for distros. If not then maybe splitting it like this based on the repos (you'd still have to maintain separate list of packages for different distos in `screenpipe/screenpipe-app-tauri/src-tauri/tauri.linux.conf.json` are the package names differ)
> 
> ```
> 	if (packageManager === 'apt') {
> 		await $`sudo apt-get update`;
> 		for (const pkg of packages) {
> 			await $`sudo apt-get install -y ${pkg}`;
> 		}
> 	} else if (packageManager === 'dnf' || packageManager === 'yum') {
> 		for (const pkg of packages) {
> 			await $`sudo ${packageManager} install -y ${pkg}`;
> 		}
> 	} else if (packageManager === 'pacman') {
> 		await $`sudo pacman -Syu`;
> 		for (const pkg of packages) {
> 			await $`sudo pacman -S --noconfirm ${pkg}`;
> 		}
> 	}
> }
> ```

am not sure to understand 

ideally it's just a one liner for everyone to install and the script figure out whatever is your config and set things up automatically 

not sure how to do this, only familiar with ubuntu

i guess the pre_build.js can overwrite the `screenpipe/screenpipe-app-tauri/src-tauri/tauri.linux.conf.json` based on your setup

**Comment by louis030195** [comment]
we officially only support debian/ubuntu, don't have the bandwidth to support others, other distros should be supported by community

**Comment by tonybenoy** [comment]
Ok. So as this is closed it's pointless for me to create a PR with other distros? I'll make a pkgbuild for AUR then :)
