### ISSUE TITLE
[bug] Pipes are not working as expected on MacOS

### ISSUE THREAD

**Issue by qiqiWav** [mediar-ai/screenpipe#422]
#### The issue is occurring:

The pipe-focus-notification-buddy is not working as expected. The application is unable to load the pipe, resulting in an error: "No pipe.js/pipe.ts found in the pipe/dist directory". I've tried every pipe, and all of them are encountering the same problem.

#### System Information:

```
OS: macOS
OS Version: macOS Sonoma 14.5
Device: MacBook Pro (16-inch, 2019)
Processor: 2.4 GHz 8-Core Intel Core i9
Graphics: Radeon Pro Vega 20 4 GB, Intel UHD Graphics 630 1536 MB
Memory: 32 GB 2400 MHz DDR4
```

#### Log output for pipe error:
```
2024-10-03T22:15:29.728754Z  INFO screenpipe_core::pipes::pipes: Input appears to be a local path. Attempting to canonicalize...
2024-10-03T22:15:29.729022Z  INFO screenpipe_core::pipes::pipes: Pipe directory: "/Users/wangqi/.screenpipe/pipes/pipe-focus-notification-buddy-ref-main"
2024-10-03T22:15:29.729730Z  INFO screenpipe: pipe completed: Err(No pipe.js/pipe.ts found in the pipe/dist directory)
```

#### File structure of the pipe directory:
```
total 16
drwxr-xr-x   4 wangqi  staff   128 Sep 30 20:27 .
drwxr-xr-x  14 wangqi  staff   448 Oct  3 18:08 ..
-rw-r--r--@  1 wangqi  staff  2931 Sep 30 20:27 main.js
-rw-r--r--@  1 wangqi  staff    71 Oct  3 18:09 pipe.json
```

**Comment by louis030195** [comment]
@qiqiWav can you use recent ones, old ones are not supported, (see time changed)

**Comment by louis030195** [comment]
also pipes will crash unless you build from source, refer to #375

**Comment by louis030195** [comment]
@qiqiWav should work in latest version

**Comment by qiqiWav** [comment]
> @qiqiWav should work in latest version

thx, i rebuilt it and it is working in my terminal

**Comment by louis030195** [comment]
https://github.com/mediar-ai/screenpipe/tree/main/examples/typescript/pipe-meeting-summary-by-email

this one works well 

@qiqiWav 

you need a google app specific password for it
