### ISSUE TITLE
windows install screenpipe didnt work - tauri private key not found

### ISSUE THREAD

**Issue by arghunter** [mediar-ai/screenpipe#424]
![image](https://github.com/user-attachments/assets/6e2cda4b-85e3-47b3-b479-eaa1351c687e)

How do I get around this?

**Comment by andreivettor** [comment]
I have the same issue. Could it be linked to https://github.com/mediar-ai/screenpipe/issues/321 ??

**Comment by andreivettor** [comment]
The generated exe (\screenpipe\screenpipe-app-tauri\src-tauri\target\release\bundle\nsis) ran manually works though

![image](https://github.com/user-attachments/assets/66e3a5eb-e01d-4609-ba6c-592e518350fe)

**Comment by louis030195** [comment]
it shows error but still work, dont worry

**Comment by arghunter** [comment]
thank you!
