### ISSUE TITLE
[bug] GPU needed?

### ISSUE THREAD

**Issue by baseadinho** [mediar-ai/screenpipe#427]
I'm using a Windows notebook without a GPU. Is there a way to work? 

When i'm running the command in powershell (cargo build --release --features cuda), i receive the following error.

(base) PS C:\Users\User001\Documents\Projetos\screenpipe> cargo build --release --features cuda
   Compiling candle-kernels v0.7.2
   Compiling fdeflate v0.3.5
   Compiling zune-inflate v0.2.54
   Compiling futures-executor v0.3.30
   Compiling avif-serialize v0.8.1
   Compiling swc_ecma_transforms_macros v0.5.5
   Compiling swc_config_macro v0.1.4
   Compiling anyhow v1.0.89
error: failed to run custom build command for `candle-kernels v0.7.2`

Caused by:
  process didn't exit successfully: `C:\Users\User001\Documents\Projetos\screenpipe\target\release\build\candle-kernels-bbe061176415e285\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=src/compatibility.cuh
  cargo:rerun-if-changed=src/cuda_utils.cuh
  cargo:rerun-if-changed=src/binary_op_macros.cuh
  cargo:info=["/usr", "/usr/local/cuda", "/opt/cuda", "/usr/lib/cuda", "C:/Program Files/NVIDIA GPU Computing Toolkit", "C:/CUDA"]
  cargo:rerun-if-env-changed=CUDA_COMPUTE_CAP

  --- stderr
  thread 'main' panicked at C:\Users\User001\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen_cuda-0.1.5\src\lib.rs:489:18:
  `nvidia-smi` failed. Ensure that you have CUDA installed and that `nvidia-smi` is in your PATH.: Error { kind: NotFound, message: "program not found" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by louis030195** [comment]
@baseadinho plz use `cargo build --release` without the `--features cuda`

**Comment by baseadinho** [comment]
tks, it worked
