### ISSUE TITLE
[bug] example pipe-focus-notification-buddy crashes frequently during runtime

### ISSUE THREAD

**Issue by goodpeter-sun** [mediar-ai/screenpipe#440]
**describe the bug**
After download and enable this pipe, it crashes quite frequently during runtime.

**to reproduce**
steps to reproduce the behavior:
1. cd ${YOURPATHTOSCREENPIPE}/
2. ./target/release/screenpipe pipe download https://github.com/mediar-ai/screenpipe/tree/main/examples/typescript/pipe-focus-notification-buddy
3. ./target/release/screenpipe pipe enable https://github.com/mediar-ai/screenpipe/tree/main/examples/typescript/pipe-focus-notification-buddy
4. ./target/release/screenpipe

**expected behavior**

**screenshots**
[pipe][pipe-focus-notification-buddy][info]: "AI answer:" {"model":"phi3.5","created_at":"2024-10-06T16:43:27.433069Z","message":{"role":"assistant","content":"{\n    \"work\": false,\n    \"title\": \"Don't Dabble in Distractions!\",\n    \"body\": \"Time to focus bro! Swipe left on social media and games for work mode.\"\n}\n"},"done_reason":"stop","done":true,"total_duration":5602886208,"load_duration":14073000,"prompt_eval_count":1026,"prompt_eval_duration":3541665000,"eval_count":53,"eval_duration":2045278000}
thread 'main' panicked at /Users/petersun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.311.0/runtime/op_driver/futures_unordered_driver.rs:307:22:
already borrowed: BorrowMutError
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::cell::panic_already_borrowed
   3: <deno_core::runtime::op_driver::futures_unordered_driver::FuturesUnorderedDriver<C> as deno_core::runtime::op_driver::OpDriver<C>>::submit_op_fallible
   4: screenpipe_core::pipes::pipes::op_set_timeout::op_set_timeout::v8_fn_ptr
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x105eafec4 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h243268f17d714c7f
   1:        0x105ed28f0 - core::fmt::write::hb3cfb8a30e72d7ff
   2:        0x105eab928 - std::io::Write::write_fmt::hfb2314975de9ecf1
   3:        0x105eb1238 - std::panicking::default_hook::{{closure}}::h14c7718ccf39d316
   4:        0x105eb0e5c - std::panicking::default_hook::hc62e60da3be2f352
   5:        0x105eb1cfc - std::panicking::rust_panic_with_hook::h09e8a656f11e82b2
   6:        0x105eb1624 - std::panicking::begin_panic_handler::{{closure}}::h1230eb3cc91b241c
   7:        0x105eb0350 - std::sys::backtrace::__rust_end_short_backtrace::hc3491307aceda2c2
   8:        0x105eb1314 - _rust_begin_unwind
   9:        0x105f4f25c - core::panicking::panic_nounwind_fmt::h91ee161184879b56
  10:        0x105f4f2d4 - core::panicking::panic_nounwind::heab7ebe7a6cd845c
  11:        0x105f4f3c0 - core::panicking::panic_cannot_unwind::hedc43d82620205bf
  12:        0x103f4bbdc - screenpipe_core::pipes::pipes::op_set_timeout::op_set_timeout::v8_fn_ptr::he4ac6453187c3709
thread caused non-unwinding panic. aborting.
zsh: abort      RUST_BACKTRACE=1 ./target/release/screenpipe

**system information:**
 - os: [macos]
 - os version: [Sequoia V15.0.1]
 - application version: built from the latest main branch

**additional context**
N/A

**Comment by louis030195** [comment]
@goodpeter-sun hmm, been a while i did not test this pipe, can you try latest ones? (check time of commit)

this is known error https://github.com/denoland/deno_core/issues/898

IDK how to fix atm, the workaround seems to be to avoid using too regularly Promises in JS code for some reason, but in my experience recent pipes don't have this crash issue
