### ISSUE TITLE
[bug] Can't build v0.1.93 on NixOS 

### ISSUE THREAD

**Issue by SomethingGeneric** [mediar-ai/screenpipe#442]
**describe the bug**
Trying to build with `cargo build`, see the following error

**to reproduce**
steps to reproduce the behavior:
1. Try to `cargo build` on NixOS
2. (I'm not really a rust user, happy to update with other relevant information)

**expected behavior**
The project builds

**screenshots**
![image](https://github.com/user-attachments/assets/f114bc2d-e042-41d9-98a9-ec4699bf2377)

**system information:**
 - os: NixOS
 - os version: 24.05
 - application version: v0.1.93 (but same traceback on `main` branch)

**additional context**
Trrying to update the screenpipe NixOS package to v0.1.93 (See: https://github.com/NixOS/nixpkgs/pull/345912 )

Reported the issue to WebRTC-vad (which is the library at fault, as best I can tell), but it does not seem to be anywhere near active) -> https://github.com/kaegi/webrtc-vad/issues/8

**Comment by louis030195** [comment]
thanks working to support nixos!

i honestly don't know what's the issue, i don't think anybody use webrtc anymore and we could probably either remove the code or ignore under nixos or linux for example, would you be able to contribute those changes?

**Comment by SomethingGeneric** [comment]
Not sure I know enough about rust or this project's structure to do it well. Especially given that webrtc-vad isn't a direct dependency? I think some other library you import pulls it, but I have yet to figure out which

**Comment by SomethingGeneric** [comment]
`cargo tree` says that `webrtc-vad` is a dep of `vad-rs`.

**Comment by SomethingGeneric** [comment]
wait,  nevermind. seems to come directly from `screenpipe-core`

**Comment by louis030195** [comment]
<bot> today louis looked a the nixos issue and started removing webrtc which is old unused anyway
