### ISSUE TITLE
[bug] screenpipe logo doesn't have any bg color

### ISSUE THREAD

**Issue by tribhuwan-kumar** [mediar-ai/screenpipe#447]
screenpipe logo have not any background color, this is happening in arch linux with DE kde plasma 6 and windows 11

kde plasma system tray:
<img src="https://github.com/user-attachments/assets/0af15442-90d6-4f69-b50f-5ae1d69acadd" width="200px"/>

windows 11 system tray:

<img src="https://github.com/user-attachments/assets/ef39b816-78d9-4a3a-ba3b-02ca816f6c95" width="200px"/>

it should be something like this:

<img src="https://github.com/user-attachments/assets/2a6cc42d-ce7f-4521-baca-a89500ae9ed4" width="200px"/>

this is just a logo issue, logos should be replaced with correct ones

**Comment by louis030195** [comment]
macos:

<img width="273" alt="image" src="https://github.com/user-attachments/assets/1f7eeb3a-f460-442e-baa9-be984e5cd9cb">


why isnt it white on other oses?

**Comment by tribhuwan-kumar** [comment]
kde plasma system tray in light mode:

<img src="https://github.com/user-attachments/assets/37f3c02c-6bd7-439e-a841-837690fcaef2" width="200px"/>

windows 11 system tray in light mode:

<img src="https://github.com/user-attachments/assets/1dec2e25-0592-4ea2-ab74-32879c7a999d" width="200px"/>

it isn't changing the color of logo in dark mode to white but for light mode they seems fine!

**Comment by EzraEllette** [comment]
I'll look at this @louis030195

**Comment by EzraEllette** [comment]
The tray logo is a template

**Comment by EzraEllette** [comment]
# Update

## Solution
Make sure to switch the logos when theme changes.
