### ISSUE TITLE
[bug] transcription does not work for arabic - $100 bounty

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#451]
/bounty 100

someone said transcription does not work for arabic

**Comment by EzraEllette** [comment]
إن ربنا يحب أن يثنى عليه ففي كل شأنك احمد الله تعالى على ما آتاك حتى وإن كان قليلا الحمد لله على كل حال إن أصابتك مصيبة قلت الحمد لله أن الله قدرها ليأجرني عليها وإن جاءتك نعمة قل الحمد لله الذي أكرمني بها فلا يحمد على المكروه والمحمود إلا الله تعالى لأنه جل وعلا لا يقدر شرا محظى فهو يحب الحمد سبحانه وتعالى

**Comment by EzraEllette** [comment]
this is from my language selection branch with --language arabic flag added to CLI

**Comment by EzraEllette** [comment]
Testing something else, but I think I can close this out soon.

**Comment by EzraEllette** [comment]
Without specifying the language, The speech is translated into english...

**Comment by EzraEllette** [comment]
<img width="1899" alt="image" src="https://github.com/user-attachments/assets/96e70046-fcf4-4c82-9d14-64afdfe7ac00">

**Comment by EzraEllette** [comment]
Deepgram is not compatible
