### ISSUE TITLE
ignore all useless windows by default in CLI / app args 

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#454]
we record all windows and apps and for some apps/windows are not very useful to record:

<img width="1312" alt="Screenshot 2024-10-09 at 18 55 14" src="https://github.com/user-attachments/assets/f00c1402-4e44-48e6-887f-815d02b4614c">

like control centre, window manager etc

same equiv on windows

definition of done:
- add list of ignored windows by default in CLI/app settings for each OS that are not providing useful information (Control Centre, Window Manager, etc. on Macos)
- make the input field in the app to select ignored or included window properly autocomplete from possible values and multiple add/remove (like in the search UI the autocomplete for app/window)

/bounty 100

**Comment by tribhuwan-kumar** [comment]
@louis030195, i'll take a look

/attempt #454

**Comment by tribhuwan-kumar** [comment]
> * make the input field in the app to select ignored or included window properly autocomplete from possible values and multiple add/remove (like in the search UI the autocomplete for app/window)

@louis030195  there are already input fields for including and excluding windows in the app settings. is it necessary to have extra input fields for the same purpose in app's home page ?

**Comment by tribhuwan-kumar** [comment]
ignored windows list on every os
- settings
- keepass
- vpn
- private
- incognito
- wallpaper
- backup
- recorder
- vaults
- obs studio

especially on linux (kde, gnome)
- info center
- discover
- parted

on windows 11
- system properties
- control panel
- nvidia

i'll add more useless windows in this list for each os specifically. I need suggestions for mac os :)

**Comment by louis030195** [comment]
@tribhuwan-kumar cool!

do you mind sending a PR?


check how i did on macos: https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-app-tauri/lib/hooks/use-settings.tsx

**Comment by tribhuwan-kumar** [comment]
> do you mind sending a PR?

sure, i'll send a pr soon!

> check how i did on macos: https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-app-tauri/lib/hooks/use-settings.tsx

thank you, but what about ignoring windows by default in cli ?

**Comment by louis030195** [comment]
> > do you mind sending a PR?
> 
> sure, i'll send a pr soon!
> 
> > check how i did on macos: https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-app-tauri/lib/hooks/use-settings.tsx
> 
> thank you, but what about ignoring windows by default in cli ?

hmm if you can yeah, you can set defaults in `cli.rs` i guess that and maybe need to check `sidecar.rs` defaults

**Comment by tribhuwan-kumar** [comment]
there is an issue with ignoring windows and including windows in app. a same window can be in ignored list & included list at the same time. which is conflicting 

<details>
<summary>at frontend</summary>

![image](https://github.com/user-attachments/assets/ca4d38e2-665d-402a-b2b4-c76b07e37ef5)
</details>


`store.bin`
 ```
{
  "dataDir": "",
  "installedPipes": [],
  "usePiiRemoval": false,
  "aiUrl": "https://api.openai.com/v1",
  "port": 3030,
  "ignoredWindows": [
    "Incognito",
    "Wallpaper",
    "Settings",
    "Keepass",
    "Recorder",
    "Vaults",
    "OBS Studio",
    "Info center",
    "Discover"
  ],
  "userId": "7c8ca368-722b-4057-aa9f-219299c3e2df",
  "restartInterval": 0,
  "includedWindows": ["Incognito"],
  "ocrEngine": "tesseract",
  "openaiApiKey": "",
  "vadSensitivity": "high",
  "deepgramApiKey": "7ed2a159a094337b01fd8178b914b7ae0e77822d",
  "languages": [],
  "useChineseMirror": false,
  "audioChunkDuration": 30,
  "monitorIds": ["default"],
  "enableBeta": false,
  "embeddedLLM": {
    "enabled": false,
    "model": "llama3.2:1b-instruct-q4_K_M",
    "port": 11438
  },
```

**Comment by louis030195** [comment]
> i fix that conflict! & where should i add those input fields for ignoring and including windows ? @louis030195
> 
> i added it in "advance search" dialog (maybe change later)

i dont get it

this is for recording

we dont have feature to exclude window in api (except if you implemented it)

**Comment by tribhuwan-kumar** [comment]
i'm talking about recording, these flags `--ignored-windows` and `--included-windows`



```bash
 screenpipe  main  ./target/release/screenpipe -h | grep ignore
      --ignored-windows <IGNORED_WINDOWS>
          List of windows to ignore (by title) for screen recording - we use contains to match, example: --ignored-windows "Spotify" --ignored-windows "Bit" will ignore both "Bitwarden" 
and "Bittorrent" --ignored-windows "porn" will ignore "pornhub" and "youporn"
 screenpipe  main  ./target/release/screenpipe -h | grep include
      --included-windows <INCLUDED_WINDOWS>
          List of windows to include (by title) for screen recording - we use contains to match, example: --included-windows "Chrome" will include "Google Chrome" --included-windows "Wha
tsApp" will include "WhatsApp"
```

as you said in "definition of done", "make input field with autocomplete"
then, where should i make it ?

**Comment by louis030195** [comment]
<img width="891" alt="image" src="https://github.com/user-attachments/assets/869db2bc-2fa8-4883-a483-ecb796e242eb">

@tribhuwan-kumar here

**Comment by louis030195** [comment]
but it should suggest items like this:
<img width="688" alt="image" src="https://github.com/user-attachments/assets/c1bcb716-d0e2-4440-b560-90ddc66c0ffa">
