### ISSUE TITLE
[bug] Syntax Error on Windows when running bun tauri build

### ISSUE THREAD

**Issue by InfernalDread** [mediar-ai/screenpipe#461]
**describe the bug**
When I attempt to run the final command for building the app, "bun tauri build", the process begins just fine, but am hit with a syntax error as shown in the screenshot below.

**to reproduce**
steps to reproduce the behavior:
1. follow the instructions on the main website for windows installation
2. run the final command
3. Syntax error

**expected behavior**
To build the application and be ready for use.

**screenshots**
<img width="571" alt="Capture" src="https://github.com/user-attachments/assets/d3ae166d-f4b5-4726-a24a-64601c178ac2">

**system information:**
 - os: Windows 10
 - os version: Latest Windows 10 update
 - application version: Latest Version (Unsure where the number is, but I am positive it is the latest)

This is my first report on this repo, am very excited for this project, I hope someone can help with this issue, so I can try this app out with local models!

Thank you for your time!

**Comment by tribhuwan-kumar** [comment]
@InfernalDread can you send full error ? cause I just build it without any cause!

**Comment by louis030195** [comment]
yes key error is more like a warning
