### ISSUE TITLE
add language setting for STT and OCR

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#469]
basically we should be able to force language(s) for STT and OCR

whisper often uses french for me because of my accent even if i speak in english

same for OCR i noticed chinese characters sometimes appear since we supported apple native OCR for chinese

i think it can improve data quality by 10-20%

definition of done:
- i have a multi select drop down in the app settings to pick languages i use
- it is used in CLI as an arg 
- it is passed to OCR (apple, windows, tesseract)
- it is passed to STT (whisper, deepgram)

/bounty 100

**Comment by jerry-xon** [comment]
@louis030195 I have installed CLI in my mac using home brew but I am unable start the development part help me out of if so that I can fix the issue !

**Comment by EzraEllette** [comment]
Stt portion is complete

Need to implement:
OCR language support
UI

**Comment by EzraEllette** [comment]
Testing OCR and building UI

**Comment by EzraEllette** [comment]
@louis030195 

The selection of language is narrows down a lot if we consider that we're using OCR and ASR from the same settings for example, Tesseract and whisper's intersection only has ~76 languages available and Apple and Windows native base the available languages on system settings.

**Comment by EzraEllette** [comment]
To clarify Apple native OCR was using a predefined list of English and Chinese, but I made an update to base the available languages on system settings. Windows OCR already had this implemented.

**Comment by EzraEllette** [comment]
@louis030195 How should we handle the intersection of language support across the technologies?

For example: Deepgram doesn't support arabic, while whisper and tesseract do.

## Some solutions:
- filter available OCR and ASR technologies based on selected languages. Certain combinations of languages may not be possible. (expose a method to get available languages from system to determine native OCR compatibility.)
- something else...?

**Comment by louis030195** [comment]
let's just fallback to english if not supported and write in the UI or somewhere which is not supported (until more people ask for arabic)

**Comment by louis030195** [comment]
/tip $50 @EzraEllette 

great work!
