### ISSUE TITLE
[docs] provide simplified chinese translations

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#474]
**describe the issue or improvement**

there is growing users coming from China and we'd like translation of README.md and docs 

**suggested changes**

- [ ] translate README.md 
- [ ] translate `content/docs/pages` folder - can you make it a toggle or something to switch between languages?

/bounty 50

**Comment by mrkirthi-24** [comment]
i would like to work on this if @varshith257 drops it

**Comment by varshith257** [comment]
@mrkirthi-24 I have done most of work except toggle will push changes by EOD
