### ISSUE TITLE
[bug] macos bug at start

### ISSUE THREAD

**Issue by HarrytheOrange** [mediar-ai/screenpipe#486]
**describe the bug**
2024-10-12 14:35:20.631 screenpipe[51543:1615869] -[SCWindow isActive]: unrecognized selector sent to instance 0x600000239040
thread 'main' panicked at /Users/runner/.cargo/git/checkouts/screencapturekit-rs-a404cd3ea7290c6e/ad366ed/screencapturekit-sys/./src/shareable_content.rs:71:18:
Uncaught exception <NSException: 0x600002f2d830>
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**to reproduce**
1. macbook air m1 homebrew install
2. start screenpipe

**system info**
- os: MacBook Air (M1, 2020) MacOS 12.4
- screenpipe version: screenpipe 0.1.90

**Comment by louis030195** [comment]
> **describe the bug** 2024-10-12 14:35:20.631 screenpipe[51543:1615869] -[SCWindow isActive]: unrecognized selector sent to instance 0x600000239040 thread 'main' panicked at /Users/runner/.cargo/git/checkouts/screencapturekit-rs-a404cd3ea7290c6e/ad366ed/screencapturekit-sys/./src/shareable_content.rs:71:18: Uncaught exception <NSException: 0x600002f2d830> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> **to reproduce**
> 
> 1. macbook air m1 homebrew install
> 2. start screenpipe
> 
> **system info**
> 
> * os: MacBook Air (M1, 2020) MacOS 12.4
> * screenpipe version: screenpipe 0.1.90

please update your macos version, too old

alternatively you can try:

`screenpipe --list-audio-device`

then 

`screenpipe --audio-device <your audio device 1> --audio-device <your audio device 2>` and avoid selecting the "Display" audio which is not supported feature on old version of macos
