### ISSUE TITLE
[question] screenpipe-app-tauri run bun install failed in china.

### ISSUE THREAD

**Issue by wqlxx** [mediar-ai/screenpipe#487]
I tried using the HTTP_PRXOY environment variable and then running bun install. But it still fails to download the packages.

```
wqlxx@wqlxx_pc:~/screenpipe/screenpipe-app-tauri$ bun install
bun install v1.1.30 (7996d06b)
  🔍 Resolving [1/1] 
```

I also try to change bunfig.toml to
```
wqlxx@wqlxx_pc:~/screenpipe/screenpipe-app-tauri$ cat bunfig.toml 
[install]
registry = "http://registry.npm.taobao.org"
```
but this change did not take effect

**Comment by peanut996** [comment]
Not `HTTP_PRXOY` 

 instead of `HTTP_PROXY`
 
 Maybe try proxy tool.

**Comment by louis030195** [comment]
> I tried using the HTTP_PRXOY environment variable and then running bun install. But it still fails to download the packages.
> 
> ```
> wqlxx@wqlxx_pc:~/screenpipe/screenpipe-app-tauri$ bun install
> bun install v1.1.30 (7996d06b)
>   🔍 Resolving [1/1] 
> ```
> 
> I also try to change bunfig.toml to
> 
> ```
> wqlxx@wqlxx_pc:~/screenpipe/screenpipe-app-tauri$ cat bunfig.toml 
> [install]
> registry = "http://registry.npm.taobao.org"
> ```
> 
> but this change did not take effect

you need to use a vpn for setting up dev i guess

funny to see this as im reading Alibaba biography right now (taobao)

**Comment by wqlxx** [comment]
> Not `HTTP_PRXOY`
> 
> instead of `HTTP_PROXY`
> 
> Maybe try proxy tool.

Sorry, I made a spelling mistake when describing the problem.

**Comment by wqlxx** [comment]
> > I tried using the HTTP_PRXOY environment variable and then running bun install. But it still fails to download the packages.
> > ```
> > wqlxx@wqlxx_pc:~/screenpipe/screenpipe-app-tauri$ bun install
> > bun install v1.1.30 (7996d06b)
> >   🔍 Resolving [1/1] 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also try to change bunfig.toml to
> > ```
> > wqlxx@wqlxx_pc:~/screenpipe/screenpipe-app-tauri$ cat bunfig.toml 
> > [install]
> > registry = "http://registry.npm.taobao.org"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but this change did not take effect
> 
> you need to use a vpn for setting up dev i guess
> 
> funny to see this as im reading Alibaba biography right now (taobao)
` registry = "http://registry.npm.taobao.org"`  is effective when installed with npm install, and can help me speed up downloads.However, it is invalid when using the bun install command.
