### ISSUE TITLE
[bug] Library not loaded when start desktop app which is build from source.

### ISSUE THREAD

**Issue by peanut996** [mediar-ai/screenpipe#489]
**describe the bug**
when in vscode terminal build the desktop app, the env var `DYLD_LIBRARY_PATH` always empty.

So start the app, the core process screenpipe can not start,because of the dynamic lib not loaded.

**to reproduce**
just start as documentation to start build app. Success on my M1 mbp, failed on x64 mbp. 

**expected behavior**
should set `DYLD_LIBRARY_PATH` successfully within `screenpipe-vision/lib`

**system info**
- os: macos 15.0.1 
- screenpipe version: 0.1.95

**additional context**
```
ERROR: dyld[33173]: Library not loaded: screenpipe-vision/lib/libscreenpipe_x86_64.dylib
ERROR:   Referenced from: <7D948E25-9BDD-33B0-B0CD-5C07B511636D> /Applications/screenpipe.app/Contents/MacOS/screenpipe
ERROR:   Reason: tried: 'screenpipe-vision/lib/libscreenpipe_x86_64.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSscreenpipe-vision/lib/libscreenpipe_x86_64.dylib' (no such file), 'screenpipe-vision/lib/libscreenpipe_x86_64.dylib' (no such file)
```

**Comment by peanut996** [comment]
Maybe mac OS SIP cause this?

**Comment by louis030195** [comment]
you probably did not follow instructions here https://docs.screenpi.pe/docs/getting-started#option-1-build-from-source-for-advanced-users

**Comment by peanut996** [comment]
until step 5, everything is ok 

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/89dcc3bc-f72e-4fd3-a516-6725144bfde3">

then I add the settings.json 

<img width="1326" alt="image" src="https://github.com/user-attachments/assets/5818e6f1-2a34-42a9-84bf-87fb9d8d4d08">

then run these command in vscode terminal:
```
cd screenpipe-app-tauri
bun install
bun scripts/pre_build.js # <- this is important to copy the CLI into the app
bun tauri build
```

**Comment by louis030195** [comment]
did it work?

**Comment by peanut996** [comment]
not work yet
