### ISSUE TITLE
windows install screenpipe didnt work

### ISSUE THREAD

**Issue by gptzm** [mediar-ai/screenpipe#493]
Installation Command Not Directly Executable on Windows

I encountered an issue when trying to execute the official installation command on Windows:

```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

This command cannot be directly run in Windows Command Prompt or PowerShell. It would be helpful to provide installation instructions specific to the Windows platform or clearly indicate in the documentation that this command requires using the Windows Subsystem for Linux (WSL) or another method.

Thank you!

**Comment by louis030195** [comment]
@gptzm can you try updated instructions? https://docs.screenpi.pe/docs/getting-started#windows-installation-experimental
