### ISSUE TITLE
windows install screenpipe didnt work - cant get around wget issue

### ISSUE THREAD

**Issue by Samarth-8836** [mediar-ai/screenpipe#494]
Im trying to install Screenpipe and build the program from scratch but I'm stuck at the following script line -
`bun scripts\pre_build.js # (you might wget not retriving error, if so use '-O' flag)`

I tried to use the -O flag option but no change.

Any help would be appreciated. Thanks!

**Comment by louis030195** [comment]
you need to install bun and run the command

**Comment by Samarth-8836** [comment]
This does not solve it. I've tried with different versions of bun too.

**Comment by louis030195** [comment]
can you share what is the error you are facing please? i cannot help without more details

**Comment by JuxtDigital** [comment]
download wget from https://eternallybored.org/misc/wget/ and place it in system32. 

add it to the path in variables, just in case.
