### ISSUE TITLE
[bug] pipe can't run after building from the latest main

### ISSUE THREAD

**Issue by goodpeter-sun** [mediar-ai/screenpipe#496]
**describe the bug**
Pipe can be downloaded and enabled normally, however, it can not run due to the below error.

```
2024-10-14T09:45:39.962936Z  INFO screenpipe_core::pipes::pipes: executing pipe: "/Users/petersun/.screenpipe/pipes/pipe-email-daily-log/pipe.ts"
2024-10-14T09:45:39.964578Z  INFO screenpipe: pipe completed: Err(No such file or directory (os error 2))
```

**to reproduce**
1.  screenpipe pipe download ...
2.  screenpipe pipe enable ...
3.  screenpipe

**expected behavior**
what should happen?

**system info**
- os: macos 15.0.1 
- screenpipe version: latest main as when this report is filed

**additional context**
add any other context, screenshots, or error logs here.

**Comment by louis030195** [comment]
Can you share the full command and log ? (Not partial one)

**Comment by louis030195** [comment]
Download sub command should be used on the directory not the typescript file

**Comment by goodpeter-sun** [comment]
[screenpipe.2024-10-14.log](https://github.com/user-attachments/files/17365600/screenpipe.2024-10-14.log)
will this file help?

yes, the download sub command is used on the directory. All I did is download, enable and restart screenpipe.

**Comment by louis030195** [comment]
@goodpeter-sun what is `.cognixcore`? it seems you moved dir or something like this, screenpipe is supposed to be in `$HOME/.screenpipe` otherwise won't work

**Comment by cparish312** [comment]
Also getting this error. To clarify the screenpipe code base is supposed to be in `$HOME/.screenpipe`? My pipes are correctly located under `$HOME/.screenpipe`

**Comment by cparish312** [comment]
Updating the homebrew cli commands resolved the issue

**Comment by goodpeter-sun** [comment]
Great to hear. What action should I exactly take to fix this?

**Comment by goodpeter-sun** [comment]
The issue is still there when everything is placed under .screenpipe.

**Comment by cparish312** [comment]
Running:

`brew tap mediar-ai/screenpipe https://github.com/mediar-ai/screenpipe.git
brew install screenpipe`

Should get it done. You will also need to re-download the pipes cause otherwise the `deno.json` file will be missing

**Comment by goodpeter-sun** [comment]
But I compiled from the source. I didn’t use brew install.

**Comment by cparish312** [comment]
Yeah I also compiled from source. I think the issue is with the installation of `deno` (which the brew install seems to resolve)

**Comment by goodpeter-sun** [comment]
Ah, I see.
But which version is actually getting installed then? From local compiled
files or remote repo? I am confused.

**Comment by cparish312** [comment]
So I'm still running screenpipe from the local build using `./target/release/screenpipe` but not sure about the deno install.

Could try running `deno --version`

**Comment by louis030195** [comment]
oh you did not install deno? @goodpeter-sun 

`curl -fsSL https://deno.land/install.sh | sh`

then try again

**Comment by goodpeter-sun** [comment]
@louis030195 deno is installed vis scripts/pre_build.js

**Comment by goodpeter-sun** [comment]
@louis030195 deno is installed via scripts/pre_build.js

**Comment by goodpeter-sun** [comment]
@louis030195 deno is installed via scripts/pre_build.js. it is so weird.

**Comment by goodpeter-sun** [comment]
@cparish312 If I only use screenpipe cli, the issue is gone. However, it still exists if I use pipe through tauri app. @louis030195 But I am closing this for now. If anyone else runs into the same issue, please reopen this.
