### ISSUE TITLE
[bounty] $150 make embedded LLM feature works on windows and linux 

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#507]
i created a new feature which allows you to run ollama, embedded in screenpipe, in a click, so there is no need to worry about running an LLM yourself and also to power some new features i'm thinking of + less friction with pipes

atm it works on macos but windows and linux seems to have bunch of files (like always) so just need to move these during build time correctly

i guess to resources tauri folder 

https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-app-tauri/scripts/pre_build.js
https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-app-tauri/src-tauri/tauri.windows.conf.json
https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-app-tauri/src-tauri/tauri.linux.conf.json

also if this works, i'm guessing it would solve our CUDA issue, meaning everyone will have CUDA-enabled whisper etc without having to worry about installing those files 

<img width="1242" alt="Screenshot 2024-10-15 at 17 48 51" src="https://github.com/user-attachments/assets/8aea6811-4a63-4c4f-b8fe-02b1dba2111a">
<img width="1242" alt="Screenshot 2024-10-15 at 17 49 02" src="https://github.com/user-attachments/assets/019aa3fd-79c3-4b54-b8fd-f0dd5f4aa7b8">

definition of done:
- [ ] `release-app.yml` builds on windows with ollama installation in [pre_build.js
](https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-app-tauri/scripts/pre_build.js) (currently commented out)
- [ ] `release-app.yml` builds on linux with ollama installation in [pre_build.js
](https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-app-tauri/scripts/pre_build.js) (currently commented out)
- [ ] windows users can enable and start and stop the LLM sidecar through the UI, it works [(this is already done, just need to remove the "macos" if)](https://github.com/mediar-ai/screenpipe/blob/8fd51d44bbf2475a52ae2e602b832846e8172ad5/screenpipe-app-tauri/components/settings.tsx#L414)
- [ ] linux users can enable and start and stop the LLM sidecar through the UI, it works [(this is already done, just need to remove the "macos" if)](https://github.com/mediar-ai/screenpipe/blob/8fd51d44bbf2475a52ae2e602b832846e8172ad5/screenpipe-app-tauri/components/settings.tsx#L414)

to be clear this is mostly fixing the pre_build and testing it works on these OS, the pre build is currently downloading ollama from releases, and moving files to the app, but need to properly move the libs to the resources

/bounty 150

**Comment by louis030195** [comment]
PS: if necessary i can split into two bounties if you can only do one OS

**Comment by varshith257** [comment]
Sure

**Comment by Abiji-2020** [comment]
@varshith257 can i know currenlty you are working on which os?

**Comment by varshith257** [comment]
@Abiji-2020 Thanks for in! I have worked on both just a few quick fixes and will wrap up the work

**Comment by Abiji-2020** [comment]
> @Abiji-2020 Thanks for in! I have worked on both just a few quick fixes and will wrap up the work

oh okayy

**Comment by varshith257** [comment]
@louis030195 Do I submit  a new PR or should I collaborate on @Neptune650 PR?

**Comment by Neptune650** [comment]
@louis030195 I apologize, but wasn't it listed as $150?

**Comment by louis030195** [comment]
/tip $50 @Neptune650 

sorry didn't see the bounty was incorrect

**Comment by Neptune650** [comment]
> /tip $50 @Neptune650 
> 
> sorry didn't see the bounty was incorrect

Much appreciated!
