### ISSUE TITLE
[bug] embedded ai on macos

### ISSUE THREAD

**Issue by ianmiell** [mediar-ai/screenpipe#511]
**describe the bug**
Embedded AI not starting

**to reproduce**
1. Start embedded API

**expected behavior**
It should start without error

**system info**
Mac: 14.3.1 (23D60)
Version 0.4.7 (20241016.011619)
<img width="1052" alt="Screenshot 2024-10-16 at 09 50 38" src="https://github.com/user-attachments/assets/d87b6f0f-6f1a-44a7-83bb-59a666430d49">
<img width="1095" alt="Screenshot 2024-10-16 at 09 50 46" src="https://github.com/user-attachments/assets/7a4b27bd-9037-4b7c-8422-742403d06b8a">
<img width="1198" alt="Screenshot 2024-10-16 at 09 51 07" src="https://github.com/user-attachments/assets/a834b66d-879e-45ca-b087-569dbd9fd83e">
<img width="1196" alt="Screenshot 2024-10-16 at 09 51 30" src="https://github.com/user-attachments/assets/d90b2135-481e-433a-b7c1-e577cd0b36dc">

**additional context**
add any other context, screenshots, or error logs here.

**Comment by louis030195** [comment]
@ianmiell can you share the logs from the file plz?
<img width="1312" alt="Screenshot 2024-10-16 at 07 56 48" src="https://github.com/user-attachments/assets/3ce73f3d-0109-4f4f-a55e-3488eb5cff73">

**Comment by louis030195** [comment]
ah also i guess you are building from source? this shouldn't happen on the paid app, make sure to follow instructions here again
https://docs.screenpi.pe/docs/getting-started

**Comment by neophonic** [comment]
I am getting the same issue, with paid desktop app. 

Used tail -n 1000 /Users/<your username>/Library/Application\ Support/screenpipe/screenpipe-app.log to send the log I believe :-)

**Comment by louis030195** [comment]
> I am getting the same issue, with paid desktop app.
> 
> Used tail -n 1000 /Users//Library/Application\ Support/screenpipe/screenpipe-app.log to send the log I believe :-)

Can you share the log? I can't help without any details

Mac M or Intel?

Any program running on port 11418?

Internet on?

**Comment by neophonic** [comment]
Louis I am sending you the log by mail. Thx.

**Comment by ianmiell** [comment]
Have upgraded since (still compiling by code) and it appears to work now.
Ian
