### ISSUE TITLE
[bounty] $150 tray menu buttons to stop/start recording + shortcut

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#515]
**describe the definition of done**

/bounty 150

- [ ] i can click stop or start in the tray menu to stop / start recording (just stop/start the sidecar)

<img width="231" alt="image" src="https://github.com/user-attachments/assets/a5c6dece-2195-420e-98cd-5d73ad3d26ed">

- [ ] i can press a global shortcut to stop/start

**Comment by louis030195** [comment]
@neo773 

btw

related bounty after this:

https://github.com/mediar-ai/screenpipe/issues/1035

**Comment by neo773** [comment]
Will start work today
