### ISSUE TITLE
set a black background ui

### ISSUE THREAD

**Issue by Serendipity-hjn** [mediar-ai/screenpipe#520]
I want a black background ui，or how to set？I did not find it。

**Comment by tribhuwan-kumar** [comment]
@Serendipity-hjn, dark mode isn't implemented yet, maybe it'll be available in future!

**Comment by tribhuwan-kumar** [comment]
@Serendipity-hjn, dark mode isn't implemented yet, maybe it'll be available in future!

**Comment by tribhuwan-kumar** [comment]
i'm working on it, it will implement soon!

**Comment by SmartManoj** [comment]
How should one enable it?
