### ISSUE TITLE
[bug] Custom URL is broken

### ISSUE THREAD

**Issue by DmacMcgreg** [mediar-ai/screenpipe#523]
**describe the bug**
Clicking Custom Url does not work

**to reproduce**
1. Open AI Settings, choose custom url
2. Try to type in the box
3. box disappears

**expected behavior**
It should allow you to type a custom url

**system info**
- os: [macos 10.15.7]
- screenpipe version: Version 0.5.6 (20241017.030846)

**additional context**
![CleanShot 2024-10-17 at 14 39 15@2x](https://github.com/user-attachments/assets/11b5a330-f4b0-4036-a875-8eee4e5e252e)
![CleanShot 2024-10-17 at 14 39 22@2x](https://github.com/user-attachments/assets/40af984a-a325-44dd-96f5-4f67de3ee949)

**Comment by louis030195** [comment]
@DmacMcgreg should be fix on main, trying to release but have last issue on my side

**Comment by louis030195** [comment]
@DmacMcgreg any news?

**Comment by louis030195** [comment]
@DmacMcgreg yes

we can add support for gemini and anthropic indeed
