### ISSUE TITLE
 Error: Read-only file system (os error 30)

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#527]
macos app stopped working when using without dev mode, sidecar just does not start with `Error: Read-only file system (os error 30)`

**Comment by EzraEllette** [comment]
@louis030195 The only issues I have are with the sidecar starting when developing and building the application because I never have the build for the x86_64 target. I'll try to replicate this error and debug it

**Comment by EzraEllette** [comment]
I don't see the error message anywhere. I tried using the debug executable to build screenpipe-app, and the logging just stops at initializing logging. It works as expected when I update through the app. I'm attempting a bisect

**Comment by EzraEllette** [comment]
😵‍💫 Now that I recall, I have never successfully built screenpipe-app and ran without using devmode unless through the updater.

**Comment by louis030195** [comment]
@EzraEllette i fixed this, it was so random hard to debug ....

basically the --data-dir was set to `.` in the app for some reason which is read only in mac app dir 

i just removed the code, we dont allow changing data dir for now

**Comment by louis030195** [comment]
> 😵‍💫 Now that I recall, I have never successfully built screenpipe-app and ran without using devmode unless through the updater.

same never managed to build app for weeks locally, dev mode works though 

https://github.com/mediar-ai/screenpipe/issues/531
