### ISSUE TITLE
error: failed to run custom build command for `screenpipe-app v0.5.6 (/home/tensor/screenpipe/screenpipe-app-tauri/src-tauri)`

### ISSUE THREAD

**Issue by Shalender24** [mediar-ai/screenpipe#536]
Error: failed to run custom build command for `screenpipe-app v0.5.6 (/home/tensor/screenpipe/screenpipe-app-tauri/src-tauri)`

Caused by:
  process didn't exit successfully: `/home/tensor/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-2c8958203972bd94/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-check-cfg=cfg(desktop)
  cargo:rustc-cfg=desktop
  cargo:rustc-check-cfg=cfg(mobile)
  cargo:rerun-if-changed=/home/tensor/screenpipe/screenpipe-app-tauri/src-tauri/tauri.linux.conf.json
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_APP_NAME=pe
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_PREFIX=screenpi
  cargo:rustc-check-cfg=cfg(dev)
  cargo:PERMISSION_FILES_PATH=/home/tensor/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-3f3d4f260652d130/out/app-manifest/__app__-permission-files
  cargo:rerun-if-changed=capabilities
  cargo:rustc-env=TAURI_ENV_TARGET_TRIPLE=x86_64-unknown-linux-gnu
  resource path `screenpipe-x86_64-unknown-linux-gnu` doesn't exist
failed to build app: failed to build app
    Error failed to build app: failed to build app
error: script "tauri" exited with code 1

**Comment by louis030195** [comment]
https://docs.screenpi.pe/docs/getting-started#option-1-build-from-source

```
git clone https://github.com/mediar-ai/screenpipe
cd screenpipe
cargo build --release
cd screenpipe-app-tauri
bun install
bun scripts/pre_build.js # <- this is important to copy the CLI into the app
bun tauri build
```

**Comment by louis030195** [comment]
@Shalender24 any news?
