### ISSUE TITLE
[question] Why do I have to install Ollama again when building the tauri app

### ISSUE THREAD

**Issue by chikobara** [mediar-ai/screenpipe#537]
So as the title said, I have Ollama installed on my machine, but when tried to run `bun scripts/pre_build.js ` the scripts is redownloading Ollama.

Shouldn't it scan for any installed package? or there is another specific version for the Screenpipe?

**Comment by louis030195** [comment]
it's just packaging ollama in the app:

<img width="929" alt="image" src="https://github.com/user-attachments/assets/9d25b00a-4599-4ed4-aab7-4d380a6daad5">

you don't have to worry about it it's just a file

**Comment by chikobara** [comment]
> it's just packaging ollama in the app:

the ollama app? when I tried to run the `pre_build.js` script it was downloading more than nearly 1.6GB, so are you sure you mean the ollama app or the llama model? 

but anyway my question is why do I have to reinstall all that again?
I have Ollama installed on my machine configured with llama and other models, i don't want to download anything from that script, right?

**Comment by louis030195** [comment]
> > it's just packaging ollama in the app:
> 
> the ollama app? when I tried to run the `pre_build.js` script it was downloading more than nearly 1.6GB, so are you sure you mean the ollama app or the llama model?
> 
> but anyway my question is why do I have to reinstall all that again? I have Ollama installed on my machine configured with llama and other models, i don't want to download anything from that script, right?

if you want you can change the script to check this, we wrote this script to build the app in CI first and foremost

**Comment by chikobara** [comment]
> if you want you can change the script to check this, we wrote this script to build the app in CI first and foremost

IK, but again my first question was about the script. Isn't the script supposed to automatically recognize it, or at least ask the user if he wants it in another env?

**Comment by louis030195** [comment]
@chikobara no we implemented the script for app build in CI

would love any contribution to make it work for your use case too
