### ISSUE TITLE
[question] CLI installation not successful - error: failed to run custom build command for `esaxx-rs v0.1.10`

### ISSUE THREAD

**Issue by rff-hso** [mediar-ai/screenpipe#538]
**context**
I'm on a MacBook Pro, Apple M1 Max, macOS 15.0.1 (24A348), Kernel Version: Darwin 24.0.0. 
Coreutils installed with homebrew.
How come that cstdint cant be found?

Following the cli install instructions and running  the screenpipe command  resulted in 

% cargo build --release --features metal

cargo build --release --features metal
   Compiling esaxx-rs v0.1.10
   Compiling webrtc-vad v0.4.0
   Compiling rayon-cond v0.3.0
   Compiling reqwest v0.12.8
   Compiling libsqlite3-sys v0.27.0
   Compiling ort v2.0.0-rc.6
   Compiling digest v0.10.7
   Compiling derive_builder v0.20.2
   Compiling samplerate v0.2.4
   Compiling chrono-tz v0.8.6
The following warnings were emitted during compilation:

warning: esaxx-rs@0.1.10: src/esaxx.cpp:620:10: fatal error: 'cstdint' file not found
warning: esaxx-rs@0.1.10:   620 | #include <cstdint>
warning: esaxx-rs@0.1.10:       |          ^~~~~~~~~
warning: esaxx-rs@0.1.10: 1 error generated.

error: failed to run custom build command for `esaxx-rs v0.1.10`

**caused by**
Caused by:
  process didn't exit successfully: `/Users/macbook-XXX/screenpipe/target/release/build/esaxx-rs-21e7b2384200c3ff/build-script-build` (exit status: 1)
  --- stdout
  OUT_DIR = Some(/Users/macbook-XXX/screenpipe/target/release/build/esaxx-rs-4cb1d1e722e0f490/out)
  TARGET = Some(aarch64-apple-darwin)
  OPT_LEVEL = Some(3)
  HOST = Some(aarch64-apple-darwin)
  cargo:rerun-if-env-changed=CXX_aarch64-apple-darwin
  CXX_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CXX_aarch64_apple_darwin
  CXX_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
  MACOSX_DEPLOYMENT_TARGET = None
  cargo:rerun-if-env-changed=CXXFLAGS_aarch64-apple-darwin
  CXXFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CXXFLAGS_aarch64_apple_darwin
  CXXFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:warning=src/esaxx.cpp:620:10: fatal error: 'cstdint' file not found
  cargo:warning=  620 | #include <cstdint>
  cargo:warning=      |          ^~~~~~~~~
  cargo:warning=1 error generated.

  --- stderr

  error occurred: Command env -u IPHONEOS_DEPLOYMENT_TARGET "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=arm64-apple-darwin" "-mmacosx-version-min=15.0" "-I" "src" "-Wall" "-Wextra" "-std=c++11" "-stdlib=libc++" "-o" "/Users/macbook-XXX/screenpipe/target/release/build/esaxx-rs-4cb1d1e722e0f490/out/2e40c9e35e9506f4-esaxx.o" "-c" "src/esaxx.cpp" with args c++ did not execute successfully (status code exit status: 1).

warning: build failed, waiting for other jobs to finish...

**Comment by louis030195** [comment]
<img width="588" alt="image" src="https://github.com/user-attachments/assets/63a055f2-d2c1-41bc-935e-d4898911b4fd">

**Comment by rff-hso** [comment]
Thx for your quick reply. Xcode was installed. Softwareupdate ran successfull. Env variables were set. C++ compiler set to clang++ (vers 18.1.8) 

Now installation fails at building libsqlite... With too many errors.
It seems there is something completely broken with my setup


The following warnings were emitted during compilation:

warning: objc_exception@0.1.2: extern/exception.m:1:10: fatal error: 'objc/objc.h' file not found
warning: objc_exception@0.1.2:     1 | #include <objc/objc.h>
warning: objc_exception@0.1.2:       |          ^~~~~~~~~~~~~
warning: objc_exception@0.1.2: 1 error generated.

error: failed to run custom build command for `objc_exception v0.1.2`

Caused by:
  process didn't exit successfully: `/Users/macbook-XXX/screenpipe/target/release/build/objc_exception-94f3f8e206ea581e/build-script-build` (exit status: 1)
  --- stdout
  OUT_DIR = Some(/Users/macbook-XXX/screenpipe/target/release/build/objc_exception-b4da3613b84e6d04/out)
  TARGET = Some(aarch64-apple-darwin)
  OPT_LEVEL = Some(3)
  HOST = Some(aarch64-apple-darwin)
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some(/opt/clang+llvm/clang+llvm-18.1.8/bin/clang)
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
  MACOSX_DEPLOYMENT_TARGET = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:warning=extern/exception.m:1:10: fatal error: 'objc/objc.h' file not found
  cargo:warning=    1 | #include <objc/objc.h>
  cargo:warning=      |          ^~~~~~~~~~~~~
  cargo:warning=1 error generated.

  --- stderr


  error occurred: Command env -u IPHONEOS_DEPLOYMENT_TARGET "/opt/clang+llvm/clang+llvm-18.1.8/bin/clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=arm64-apple-darwin" "-mmacosx-version-min=15.0" "-Wall" "-Wextra" "-o" "/Users/macbook-XXX/screenpipe/target/release/build/objc_exception-b4da3613b84e6d04/out/cd802d741d7fdd7c-exception.o" "-c" "extern/exception.m" with args clang did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: webrtc-vad@0.4.0: In file included from resources/libfvad/src/signal_processing/division_operations.c:20:
warning: webrtc-vad@0.4.0: In file included from resources/libfvad/src/signal_processing/signal_processing_library.h:21:
warning: webrtc-vad@0.4.0: resources/libfvad/src/signal_processing/../common.h:14:10: fatal error: 'stdlib.h' file not found
warning: webrtc-vad@0.4.0:    14 | #include <stdlib.h>
warning: webrtc-vad@0.4.0:       |          ^~~~~~~~~~
warning: webrtc-vad@0.4.0: 1 error generated.


Plus many more warnings...

**Comment by louis030195** [comment]
<img width="1148" alt="image" src="https://github.com/user-attachments/assets/a0742abf-379b-4cac-82f3-5d8160f0bab5">

**Comment by rff-hso** [comment]
Thx
Reinstalling xcode cmdline tools did the trick, finally

**Comment by rff-hso** [comment]
Which model did you use for your answers, btw?
