### ISSUE TITLE
[question] Why don't you commit Cargo.lock

### ISSUE THREAD

**Issue by happysalada** [mediar-ai/screenpipe#542]
**your question**
Why are you not committing the Cargo.lock, is it because you mean to have screenpipe as a library rather than a standalone app ?

**context**
Having a Cargo.lock committed would make it much easier to build from source.

**Comment by louis030195** [comment]
> **your question** Why are you not committing the Cargo.lock, is it because you mean to have screenpipe as a library rather than a standalone app ?
> 
> **context** Having a Cargo.lock committed would make it much easier to build from source.

"Having a Cargo.lock committed would make it much easier to build from source" why?

**Comment by happysalada** [comment]
I was looking at updating the dependency from nixpkgs. The way nix builds things it needs a lock file to determine exactly what is going to be built, it tries as much as possible to be deterministic.
Being able to pull it from source is a standard process. Otherwise it needs to be manually generated and copied over to nixpkgs.
