### ISSUE TITLE
windows install screenpipe didnt work

### ISSUE THREAD

**Issue by mtylovesqs** [mediar-ai/screenpipe#573]
Hi,bro. I can't get it normally

**Comment by louis030195** [comment]
@mtylovesqs i cannot help if you don't provide any information:

- what did you do/try
- what is the error (share logs)
- what is your hardware/software details

**Comment by mtylovesqs** [comment]
bro，I installed the PC locally, but it doesn't work, it's not in green status, it's always in red. Because my skills are not very strong, I have no way to start.

I tried to obtain the new PC software by sharing on social media, but I haven't received it yet. My attempts are currently at a standstill.



---- Replied Message ----
| From | Louis ***@***.***> |
| Date | 10/23/2024 23:54 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [mediar-ai/screenpipe] windows install screenpipe didnt work (Issue #573) |

@mtylovesqs i cannot help if you don't provide any information:

what did you do/try
what is the error (share logs)
what is your hardware/software details
