### ISSUE TITLE
[bug] Screenpipe updates fail when trying to access onnxruntime.dll while screenpipe.exe in background

### ISSUE THREAD

**Issue by mathjons** [mediar-ai/screenpipe#575]
**describe the bug**
When Screenpipe updates it does not terminate the background process screenpipe.exe which is using onnxruntime.dll, which causes an error.

**to reproduce**
1. When launcher "screenpipe Setup" starts on update while screenpipe.exe is running.

**expected behavior**
Screenpipe updater should terminate screenpipe.exe before attempting to access onnxruntime.dll, then it should apply the update without errors.

**system info**
- os: Windows 11
- screenpipe version: latest

**additional context**
Fix: Open task manager > terminate screenpipe.exe > press Retry > installer completes without errors.
![image](https://github.com/user-attachments/assets/a0488663-2c14-4c46-b9ab-45da538edaea)

**Comment by louis030195** [comment]
@mathjons thx for reporting

i'm not on windows, we use

`tasklist /FI PID eq <pid of screenpipe>` to see if the app has been stopped and if so to stop automatically the recording 

i'm not sure how to get process PID on windows but would appreciate any confirmation this command works, i think this feature was working few weeks ago not sure what changed



https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-server/src/auto_destruct.rs

**Comment by louis030195** [comment]
@tribhuwan-kumar any chance you can help on this issue?

basically when update is started on windows it should properly close both screenpipe sidecar and LLM sidecar otherwise it prevents updates on windows

(no need to change on macos, idk for linux)

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar any chance you can help on this issue?
> 
> basically when update is started on windows it should properly close both screenpipe sidecar and LLM sidecar otherwise it prevents updates on windows
> 
> (no need to change on macos, idk for linux)

on it!
