### ISSUE TITLE
[bounty] nextjs loom replacement pipe

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#583]
/bounty 100 

definition of done:
- at the end of the day i can go to screenpipe and ask for a loom of a specific time range 
- it should be a nextjs pipe 
- minimum version is taking a time range and stitching together mp4 files (video and audio) and giving me back the video with audio

bonus:
- highlights, good UX like loom (somehow)

check this nextjs pipe https://github.com/mediar-ai/screenpipe/tree/main/examples/typescript/pipe-simple-nextjs

also be aware nextjs does have some issue with deno sometimes - for example openai streaming failed for me once idk why (we're thinking in switching to bun soon)

related #582 

more context: https://github.com/mediar-ai/screenpipe/blob/cf2b374a65252734f840fc6430e8221d6c5a4bda/screenpipe-server/src/server.rs#L967

we have endpoint to merge video but might need some changes, e.g. this task might involve a little bit of rust

my use case:

<img width="901" alt="image" src="https://github.com/user-attachments/assets/deccc5ad-07de-4ced-bf35-35dbcce08b04">

PLEASE say the UX you think of and how you're going to implement this before starting the task plz

**Comment by tribhuwan-kumar** [comment]
@louis030195 
i'm thinking to implement something like this, there will a time & date option, user can select a time interval for loom, then it'll merge those specific time ranged videos and audio in one video and send back to the user. there will also an option for quick share, so user can directly share that video on whatsapp, x, etc. i might take some inspiration from loom

(extra feature in this pipe could be a quick summary of that time interval and summary of that video, also it'd be great if user can interact with this pipe)

**Comment by tribhuwan-kumar** [comment]
> pretty much the same way with the @tribhuwan-kumar.
> 
> there will be a time & date component and when users select the time range for a loom video it'll create the video and send back to the user.

the searching and merging are done, i'm currently working on ux, if you have any suggestion for ux we can collaborate!

**Comment by volfcan** [comment]
> > pretty much the same way with the @tribhuwan-kumar.
> > there will be a time & date component and when users select the time range for a loom video it'll create the video and send back to the user.
> 
> the searching and merging are done, i'm currently working on ux, if you have any suggestion for ux we can collaborate!

check your twitter dms

**Comment by tribhuwan-kumar** [comment]
> check your twitter dms

there's nothing

**Comment by louis030195** [comment]
sounds good 

> @louis030195 i'm thinking to implement something like this, there will a time & date option, user can select a time interval for loom, then it'll merge those specific time ranged videos and audio in one video and send back to the user. there will also an option for quick share, so user can directly share that video on whatsapp, x, etc. i might take some inspiration from loom
> 
> (extra feature in this pipe could be a quick summary of that time interval and summary of that video, also it'd be great if user can interact with this pipe)

**Comment by tribhuwan-kumar** [comment]
@louis030195 
is this ui is okay ?
it will open a dialog of merged video and audio

![image](https://github.com/user-attachments/assets/fbceb127-7ba5-4e25-bf06-443802593dd1)

**Comment by tribhuwan-kumar** [comment]
there was a 500 internal problem with merge frame route, i fixed that. but i noticed some strange behavior while merging videos, imagine this situation, i kill the screenpipe while processing some videos. after killing the screenpipe the video remains uncompleted. and these uncompleted videos are causing errors while merging large amount of videos. maybe i need to add some checks before merging those videos

**Comment by louis030195** [comment]
@tribhuwan-kumar 

nice

video should have audio too at least

i'm actually shipping an endpoint that allows you to stream frames through SSE at high speed for #343 

https://github.com/mediar-ai/screenpipe/tree/timeline-ui

i think you might wait i merge this and i'm likely going to do some hacks to stream the audio too so it might solve your problem

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar
> 
> nice
> 
> video should have audio too at least

right now, i'm able to merge video to video and audio to audio, (merged video and merged audio are separate)  
i tried to merge video to audio but the problem i'm getting is order correction, some audio have only beep sound, some have sound but how can i merge those audio with their corresponding video frame. 

> 
> i'm actually shipping an endpoint that allows you to stream frames through SSE at high speed for #343
> 
> https://github.com/mediar-ai/screenpipe/tree/timeline-ui
> 
> i think you might wait i merge this and i'm likely going to do some hacks to stream the audio too so it might solve your problem

for now, i fixed those corrupt video error, by [filtering out](https://github.com/tribhuwan-kumar/screenpipe/blob/f566d605c5fc722759ab0f81c2a8b9e44f6eaf0b/screenpipe-server/src/video_utils.rs#L74) those video. it prevents corrupt videos getting in `input_list.txt`, this can be slow bcz it adds an extra check before merging them

**Comment by tribhuwan-kumar** [comment]
@louis030195 
a working beta version:

https://github.com/user-attachments/assets/44f985bd-172d-4595-b140-e4d30fbe7f77

**Comment by louis030195** [comment]
> @louis030195 a working beta version:
> 
>  a.mp4

thats cool

is there audio in it?

**Comment by tribhuwan-kumar** [comment]
>> > @louis030195 a working beta version:
> > 
> >  a.mp4
> 
> thats cool
> 
> is there audio in it?

no, that merged video doesn't have audio, it's just a series of video concatenated by ffmpeg, it doesn't have embedded audio. I tried to embedded video with audio but I'm facing issues of order correction :(

**Comment by louis030195** [comment]
> > > > @louis030195 a working beta version:
> > > 
> > > 
> > > a.mp4
> > 
> > 
> > thats cool
> > is there audio in it?
> 
> no, that merged video doesn't have audio, it's just a series of video concatenated by ffmpeg, it doesn't have embedded audio. I tried to embed video with audio but I'm facing issues of order synchronizing :(

are you using database metadata?

you can fetch all the things and order by time

i guess it's possible to have 1-3 seconds of audio desync because we capture timestamp not right sync 

also if you try to create a loom over too long range things that i expect to happen:
- say i closed my lid (screen capture stop but mic keeps going i think) -> will have weird desync with audio
-

**Comment by tribhuwan-kumar** [comment]
> are you using database metadata?
>
> you can fetch all the things and order by time
> 
> i guess it's possible to have 1-3 seconds of audio desync because we capture timestamp not right sync
> 
> also if you try to create a loom over too long range things that i expect to happen:
> 
> * say i closed my lid (screen capture stop but mic keeps going i think) -> will have weird desync with audio
> 
> 
> although this should be only for short times
> 
> i guess a version 10.0 of this would be to feed this to a voice LLM and fix all the things automatically and comment on the video haha

then i've to create an another route for embedding audio in video bcz [this](https://github.com/tribhuwan-kumar/screenpipe/blob/e4d8312ff7505c2b3d8b30084e0d910db9fe41ad/screenpipe-server/src/video_utils.rs#L130) can only concatenate the videos and audios. & thanks for the  metadata it would be helpful for embedding :)
