### ISSUE TITLE
[docs] Documentation Website Layout and Design Issues

### ISSUE THREAD

**Issue by krushnarout** [mediar-ai/screenpipe#605]
**describe the issue or improvement**

I've noticed that the documentation page at https://docs.screenpi.pe/ appears broken, with a messy layout and oversized icons. The overall design is not user-friendly, making it difficult to navigate and read the content.

https://github.com/user-attachments/assets/b8c1c82f-6b36-4bc7-a02a-71063538ed33

**suggested changes**

I would like to work on this issue to improve the layout and design of the documentation page.

**additional context**
add any other context about the documentation issue here.

**Comment by krushnarout** [comment]
I want to work on this.

**Comment by louis030195** [comment]
thx i just fixed the missing <Head> 

feel free to send any contributions for something missing or to improve in docs!
