### ISSUE TITLE
[bug] Meeting and Conversation History Does Not Work

### ISSUE THREAD

**Issue by DmacMcgreg** [mediar-ai/screenpipe#608]
**describe the bug**
When I open the Meeting and Conversation History, it is blank. I've had screenpipe running and status is good for over a day, yet no meetings were detected.

**to reproduce**
1. Open screenpipe, check status is green
2. have a few meetings
3. Come back, open meetings tab.

**expected behavior**
Right now, I'm finding the screenpipe app a little too "versatile" and unfocused in that it does not organize the information coherently, and making it very hard to use.
If I were to use this as a daily app, I would expect a few things:
1. Meetings should plug into my calendar, and get the attendees, and meeting title.
2. It should remind me of an upcoming meeting, and give me a summary of the description of the meeting, along with the history of the last time I had a meeting with these individuals on a related topic.
3. Automatically provide me with a summary of the meeting with action items. This can plug into apps like Linear using linear.new links, or whatever other tool using a pipe store perhaps.
4. Should present an accurate transcript of the meeting.

If you want to see a great implementation of this, check of Spellar AI. It's what I'm using every day to transcribe my meetings. But it would be even more killer to have the context of the screen, which screenpipe does.

**system info**
- os: macos 14.6
- screenpipe version: Version 0.7.6 (20241025.162038)

**additional context**
![CleanShot 2024-10-30 at 11 14 06@2x](https://github.com/user-attachments/assets/46f6b0f8-1ab2-4fe0-8a33-32896d43cfd7)

**Comment by louis030195** [comment]
@DmacMcgreg does transcription work for you now? we did some changes on audio processing (not the UI)

**Comment by DmacMcgreg** [comment]
@louis030195 

![CleanShot 2024-11-13 at 15 15 22@2x](https://github.com/user-attachments/assets/cfc9dc7a-479b-4e3f-b17e-6b4d31e6aff7)

Both status are green

**Comment by DmacMcgreg** [comment]
@louis030195  not sure why it wasn't working then, it seems to be good now.
I'm reviewing my home page, as well as the meeting page, and its mostly still gibberish. 
I would say that the only way meeting recording makes sense is semi-manual, otherwise the meeting page is filled with garbage non-meetings.

The way spellar AI does it is pretty much ideal. Hooks into your Calendar, then detects an upcoming meeting and asks you to join. Its able to detect all the participants, the meeting details, and then you end the meeting manually by clicking a floating button. Then it will automatically transcribe and provide a summary.
