### ISSUE TITLE
timeline ui

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#609]
#607 
![image](https://github.com/user-attachments/assets/fdd9d4fe-2d08-4239-9538-43e3071e7c9c)

https://screenmemory.app/
https://www.rewind.ai/

#343 

definition of done:
- simple scrollable timeline UI that shows up when pressing a shortcut (definable in settings like #552 )
- should show the apps
- (optional) can search 

additional details:
- i'd just use the search API and paginate as user scrolls, use the API to merge mp4 files into a single one either on the fly in a temporary dir or always have it ready somehow (to make things faster)
- should be able to show on top of existing app using the shortcut like we do currently, but implement another page for this timeline
- also i think we could do additional nice UX things since we have a local LLM but focus on the main things

**Comment by louis030195** [comment]
i'm going to design and implement and release it today myself any feedback/idea appreciated

**Comment by louis030195** [comment]
the thing that excite me about this feature is to do AI features with the app embedded local LLM (llama3.2) to classify stuff etc

**Comment by louis030195** [comment]
<img width="1512" alt="Screenshot 2024-10-30 at 1 16 46 PM" src="https://github.com/user-attachments/assets/5f571b1b-9a09-4bff-8921-9e7bb92d8c09">

ugly as hell v0 that works

**Comment by louis030195** [comment]
<img width="1512" alt="Screenshot 2024-10-30 at 1 27 20 PM" src="https://github.com/user-attachments/assets/61f30f4d-5541-496f-99de-95bdfc072101">

**Comment by louis030195** [comment]
@DmacMcgreg

i did a simple & fast frame streaming API

you can test an very early version:
```bash
brew tap mediar-ai/screenpipe https://github.com/mediar-ai/screenpipe.git
brew install screenpipe
screenpipe
```

then 

```bash
open screenpipe-server/examples/timeline_ui/index.html # or open manually in your browser
```

this will open a rewind.ai alike timeline powered by a single html file :) that you can tweak around!


working on the desktop version and also adding audio to it

**Comment by Glavin001** [comment]
Awesome progress! 🎉  I'll test this weekend.

**Comment by volfcan** [comment]
@louis030195 we can still attempt this bounty? it looks like you're making it yourself. why did you open a bounty for this then?

**Comment by DmacMcgreg** [comment]
@louis030195  i've been testing it out with some of the updates.
At least on my machine, the scroll feature is not working. I'm scrolling, and i see the top stats change, but not the frame itself.

**Comment by DmacMcgreg** [comment]
I'm also getting extremely high CPU usage,  and also running into a few issues. 
1. Sometimes it gets stuck on "Loading frames"
2. Sometimes I get client side application error.

**Comment by DmacMcgreg** [comment]
I did manage to test the drag-time function, and it honestly seems to work REALLY well. If we can fix some of those issues, this will be killer.

**Comment by louis030195** [comment]
@DmacMcgreg thx a lot for the feedback!

https://github.com/user-attachments/assets/5cceba78-fe1a-429e-9eb4-5134e11e4d4f

<img width="446" alt="image" src="https://github.com/user-attachments/assets/60205956-4e8b-4bec-8ff3-8c36441d60cf">

i've been optimising a lot the performance but there is still room for it, also need to make sure it does not increase storage

basically i turn mp4 + database data into a timeseries with some caching on disk to reduce cpu usage 

atm biggest issues:
- some weird scroll because of the way i process videos - can be fixed but might take few hours, work for now 
- i did a cursor-like cmd+k to ask questions about the timeline or run custom "agents" the reason for agents is context limit is easily reached 
- better UX in general
- still some fundamental issues with transcription #610 on some macos versions (working on it)
- anything else i missed?

**Comment by DmacMcgreg** [comment]
![CleanShot 2024-11-04 at 16 22 15@2x](https://github.com/user-attachments/assets/07856b08-40fa-4c50-9852-42bbd6c1f6d9)
![CleanShot 2024-11-04 at 16 22 42@2x](https://github.com/user-attachments/assets/aa8b2042-4905-4571-99dd-e2530dec3e0f)


Seems to be working for you in your video. For me, the scroll simply is not working. Happy to provide logs if you let me know what you need.

**Comment by louis030195** [comment]
> ![CleanShot 2024-11-04 at 16 22 15@2x](https://private-user-images.githubusercontent.com/3266023/382922066-07856b08-40fa-4c50-9852-42bbd6c1f6d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NTg1MTUsIm5iZiI6MTczMDc1ODIxNSwicGF0aCI6Ii8zMjY2MDIzLzM4MjkyMjA2Ni0wNzg1NmIwOC00MGZhLTRjNTAtOTg1Mi00MmJiZDZjMWY2ZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMjIxMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQyMjljOGM3MzM0YTZiZDhiNmEwNjI3YTg2NzI1YzBmNjM3ZmM3MDIzZjA4MTQzNjM4ZmVlYjZhOTg3NjYzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tSdTQhdxuZdTa1KOU-qrXpVv1ur4tKbMnwpBJ9XuNpI) ![CleanShot 2024-11-04 at 16 22 42@2x](https://private-user-images.githubusercontent.com/3266023/382922077-aa8b2042-4905-4571-99dd-e2530dec3e0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NTg1MTUsIm5iZiI6MTczMDc1ODIxNSwicGF0aCI6Ii8zMjY2MDIzLzM4MjkyMjA3Ny1hYThiMjA0Mi00OTA1LTQ1NzEtOTlkZC1lMjUzMGRlYzNlMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMjIxMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmY3OWU0NGMwNTYxOWM1NjQ1ZTRjMDA3N2ViZGY3YTE5NTI4OGM5NDdiZWRhYzRkOWU1MDUxMmY4MWE4ODZmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3T2fTtP6Pc2-L3M7pHWPzruqzZcSr9Bv4u8LCLluT6I)
> 
> Seems to be working for you in your video. For me, the scroll simply is not working. Happy to provide logs if you let me know what you need.
> 
> Also whenever I hit reload frames button, it loads a random frame from any point during the day.

did you scroll vertically?

maybe you can check this:

right click somewhere (not image) and click inspect then console logs

will work on CPU usage and the bug you said

**Comment by DmacMcgreg** [comment]
@louis030195 
1. yes I scroll vertically, i can see the app stats along the top changing on every scroll, but the video frame does nothing
2. there are no console logs or network calls
3. once every 10 seconds


Would also be important to have a day selector so I can view previous days.

The app stats on the Timeline are also honestly pretty great, something to think about.

![CleanShot 2024-11-05 at 09 36 52@2x](https://github.com/user-attachments/assets/3ba20ac1-3c70-429a-86c9-fc41c3972ab3)

**Comment by louis030195** [comment]
<img width="443" alt="image" src="https://github.com/user-attachments/assets/9120763b-3e27-4da4-b78a-e858a40fe21a">

didnt expect that it was so easy 😂, going to put it in the timeline

**Comment by louis030195** [comment]
<img width="1312" alt="Screenshot 2024-11-05 at 11 52 33 AM" src="https://github.com/user-attachments/assets/c4ab4c46-6852-451c-8652-c2958fa5a126">


still a a few things to finish up

**Comment by DmacMcgreg** [comment]
So some additional info that might help: I'm using an external 4k monitor.

Here you can see the call to frames is going super high. Its now sitting at over 12GB.

![CleanShot 2024-11-05 at 14 57 36@2x](https://github.com/user-attachments/assets/1e4db800-9841-4a10-bd36-576f6cf33f4e)

So thats perhaps why i'm not able to scroll...


Here you can see the error in the console when first starting up:

![CleanShot 2024-11-05 at 14 56 33@2x](https://github.com/user-attachments/assets/d42b6209-e5f1-460c-bb57-7eb14ba91cc8)

**Comment by louis030195** [comment]
thx - but you don't have the latest version, i have bunch of changes not released on main and also more locally still fixing things

**Comment by DmacMcgreg** [comment]
@louis030195  just updated and the scrolling is now working!

**Comment by louis030195** [comment]
<img width="1312" alt="Screenshot 2024-11-06 at 1 24 00 PM" src="https://github.com/user-attachments/assets/842feb12-42eb-4385-ad91-16a028f25229">

added finally some colors & icons to main (had issues with performance), icons only works on macos #643 for now 



i'm wondering how audio could work

ideally user can go back in the day and re-listen conversations with captions, ask AI questions relative to it, etc. 

not sure how to do the UX yet

**Comment by DmacMcgreg** [comment]
@louis030195 
This is awesome and will really step this tool up to the next level. I'm here to help test if you need!

Should we have a place to mark down all the possible ideas for the timeline ui?

**Comment by louis030195** [comment]
> @louis030195 This is awesome and will really step this tool up to the next level. I'm here to help test if you need!
> 
> Should we have a place to mark down all the possible ideas for the timeline ui?

just share anything here for now :)

**Comment by louis030195** [comment]
<img width="1312" alt="Screenshot 2024-11-06 at 2 49 51 PM" src="https://github.com/user-attachments/assets/9728814e-1ea9-4a83-ab69-50f28d8181f4">

**Comment by DmacMcgreg** [comment]
I think this is where search is going to be killer. Allowing search across transcripts and screen data. Later, AI contextual search. So for example if youre really searching for the word "aims" or "goals" or "accomplishments" yet the document you worked on was actually called "achievements" then you can still find it. 

Can't tell you how much time I've wasted searching for documents I had open months ago but forget the exact name of, but would be easily findable with some sort of contextual search. The AI can tokenize a bunch of data to get the "gist" or "summary" out of it, in the background, and then allow a RAG-type search across multiple days, weeks, months. That for me would be a killer feature I haven't seen anywhere before.

**Comment by DmacMcgreg** [comment]
Maybe you could sell licenses to schools so that students can prove they are actually doing an assignment themselves and not getting AI help. It would analyze all the websites they visited, the sources, then analyze the document they wrote and give a score to see if they cheated or not.

**Comment by craftyshaun** [comment]
> I think this is where search is going to be killer. Allowing search across transcripts and screen data.

The search -> RAG -> AI is the most used feature of Reclaim I use. I work in Technical Management Consulting and one of my favourite 'Ask Reclaim' prompts is 

> _"Yesterday I did some things in VS Code & Slack between 10:00 and 14:00. Summarise this into 5 sentences focusing on outcomes achieved"_ 

This goes into my timesheets/billing. Building a pipe myself so I can hook it into my tooling and it 'drafts a timesheet' would be a nightmare.

**Comment by louis030195** [comment]
> > I think this is where search is going to be killer. Allowing search across transcripts and screen data.
> 
> The search -> RAG -> AI is the most used feature of Reclaim I use. I work in Technical Management Consulting and one of my favourite 'Ask Reclaim' prompts is
> 
> > _"Yesterday I did some things in VS Code & Slack between 10:00 and 14:00. Summarise this into 5 sentences focusing on outcomes achieved"_
> 
> This goes into my timesheets/billing. Building a pipe myself so I can hook it into my tooling and it 'drafts a timesheet' would be a nightmare.

interesting

yeah we're trying to make a good low-code version of pipe with powerful abstractions so AI can write the pipes automatically, think of it like Zapier or Gumloop but based on your screen & mic (and does not require to share your very sensitive auth keys to them)

did a recursive summarization agent for long time range (here with llama3.2 that runs on my computer, embedded AI feature of screenpipe)

https://github.com/user-attachments/assets/b4cedb59-a891-45b3-addc-014228fb57e4

i was thinking if we could allow people to create these agents/automation that works w the timeline or other parts of the app (both low code and no code) that'd be interesting

**Comment by craftyshaun** [comment]
> did a recursive summarization agent for long time range (here with llama3.2 that runs on my computer, embedded AI feature of screenpipe)

This type of thing would be cool, I was going to play with some of the sources and build some pipes. Espically since now we have the time line to see what/why the AI said that.

> i was thinking if we could allow people to create these agents/automation that works w the timeline or other parts of the app (both low code and no code) that'd be interesting.

Long term, that would be amazing and open your user base up! 

In the short term, a decent SDK would be sweet. As a dev I'm happy to spend the time writing my tooling to do the above. Also means I can integrate with my own LLM etc.

I'm planning to play this weekend with the new timeline, etc., now that there is a nice, simple homebrew package.

Side note for development: have you seen Devbox. by Jetify?

It is akin to `NPM`/`pip` but for dev environments. You'd commit a devbox.json, then anyone who clones goes `devbox shell`, and all the rust/npm tooling is ready to rumble. [Here](https://www.jetify.com/docs/devbox/devbox_examples/languages/rust/) Is there a rust example?

**Comment by louis030195** [comment]
@craftyshaun lmk how it went!


next things i want to do with the timeline:
- be able to scroll over 100% of your data
- see more clearly when there is audio on the timeline 
- shortcut to show the UI on top of your app (and feels more native like rewind)
- probably other things

**Comment by craftyshaun** [comment]
> @craftyshaun lmk how it went!

Will do, as I'm running the MacOS beta I was having issues compiling the crate for the audio SDK. I'll try again when I'm bored again.

**Comment by DmacMcgreg** [comment]
app display is a little off. Its only picking up Bartender and something else:
![CleanShot 2024-11-12 at 10 22 21@2x](https://github.com/user-attachments/assets/173f38a2-c8a8-48e0-913d-0ac8cacf4602)
![screenpipe 2024-11-12 10 22 12](https://github.com/user-attachments/assets/f796bced-d1eb-44de-b860-d9254ac2bcfb)
