### ISSUE TITLE
[bounty] iphone & microphone transcription does not work on some macos

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#610]
it's really hard to reproduce, basically on my computer iphone & microphone does not transcribe (100% speech frames but noisy for some reason)

display works 

on matt computer and other users all works

/bounty 100

i already tried to remove different part of the audio pipeline without any change, somehow to speech frames are messed up - probably something in the audio processing pipeline 

more or less accurate schema:

![image](https://github.com/user-attachments/assets/83fa1b54-1e86-4487-b3bd-fc9c4c7fac8d)

cc @EzraEllette @m13v

**Comment by EzraEllette** [comment]
It wasn't working for me until I updated from the betas to the official releases on both my iPhone and MacBook.

```
Oct 30, 2024 at 07:43:58 PM EDT [you] Testing. I'm testing the transcription of my iPhone using ScreenPipe. It is Wednesday, October 30th, 7:43 PM, Eastern Daylight Time. Sitting on the couch and staring at the UI and my cell phone. Only I've said enough words to trigger the transcript.
```

**Comment by louis030195** [comment]
@EzraEllette you mean apple version? i never use beta it breaks all

15.0.1 macos 

18.1 iphone it seems (not sure if its beta)

**Comment by louis030195** [comment]
<img width="1253" alt="Screenshot 2024-10-31 at 4 06 04 PM" src="https://github.com/user-attachments/assets/0fbe036a-6254-4a7b-93f0-8cbbab3fb70e">

upgraded to 15.1
