### ISSUE TITLE
[bounty] release screenpipe to official brew

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#614]
https://github.com/Homebrew/homebrew-core

/bounty 50

also if you can update docs here without the tap once its done

**Comment by Neptune650** [comment]
@louis030195 Hello, since it's a prebuild binary, I think we will need to make a cask for it. What do you think about using a cask instead?

Building screenpipe on the user side isn't feasible.

**Comment by krushnarout** [comment]
@louis030195 I've added the Screenpipe formula to https://github.com/Homebrew/homebrew-core locally, and when I test it, it works perfectly.

<img width="1059" alt="Screenshot 2024-11-01 at 11 37 41 AM" src="https://github.com/user-attachments/assets/ecb10870-53f7-49e9-8c39-ac4ce7611849">

**Comment by krushnarout** [comment]
@louis030195 I've added the Screenpipe formula to https://github.com/Homebrew/homebrew-core locally, and when I test it, it works perfectly.

<img width="1059" alt="Screenshot 2024-11-01 at 11 37 41 AM" src="https://github.com/user-attachments/assets/ecb10870-53f7-49e9-8c39-ac4ce7611849">

**Comment by Neptune650** [comment]
> @louis030195 I've added the Screenpipe formula to https://github.com/Homebrew/homebrew-core locally, and when I test it, it works perfectly.
> 

@krushnarout That's not exactly the goal, we need to get it actually merged to the repository so it's available for everyone

**Comment by krushnarout** [comment]
> > @louis030195 I've added the Screenpipe formula to https://github.com/Homebrew/homebrew-core locally, and when I test it, it works perfectly.
> 
> @krushnarout That's not exactly the goal, we need to get it actually merged to the repository so it's available for everyone

I understand, I'm just waiting for him to confirm their requirements before proceeding. Once I have clarity, I'll ensure it’s ready for merging into the repository for everyone’s access.

**Comment by louis030195** [comment]
> @louis030195 Hello, since it's a prebuild binary, I think we will need to make a cask for it. What do you think about using a cask instead?
> 
> Building screenpipe on the user side isn't feasible.
> 
> Homebrew doesn't accept formulas that install pre-built apps.

not sure how it works

i thought it was just a PR on their repo referencing screenpipe?

anything that works, and let me know if you need me to click on things to validate

**Comment by Neptune650** [comment]
@louis030195 Here is an initial PR https://github.com/Homebrew/homebrew-cask/pull/190662

**Comment by louis030195** [comment]
> @louis030195 Here is an initial PR [Homebrew/homebrew-cask#190662](https://github.com/Homebrew/homebrew-cask/pull/190662)

anything i need to do?

**Comment by Neptune650** [comment]
> > @louis030195 Here is an initial PR [Homebrew/homebrew-cask#190662](https://github.com/Homebrew/homebrew-cask/pull/190662)
> 
> anything i need to do?

@louis030195 I don't think so, maybe just giving your approval in a comment.
