### ISSUE TITLE
[bounty] fix small issues on windows

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#620]
/bounty 100 

#574 <- need to make sure the process and all subprocess are closed when doing updates

issue with button to open logs on windows, maybe some issue with slashes?

<img width="878" alt="Screenshot 2024-11-01 at 10 09 00 AM" src="https://github.com/user-attachments/assets/13c937c2-0d20-4f33-b5eb-780cfc847ecb">

bonus: 

- #543 - to reproduce: open task manager and start screenpipe, does it crashes? any simple fix appreciated 
- #376 

@Neptune650 maybe you can help? or anyone else

**Comment by tribhuwan-kumar** [comment]
> * [[bug] ignore admin windows in windows #543](https://github.com/mediar-ai/screenpipe/issues/543) - to reproduce: open task manager and start screenpipe, does it crashes? any simple fix appreciated

@louis030195 
opening task manager isn't crashing screenpipe, [log.log](https://github.com/user-attachments/files/17604539/log.log)


https://github.com/user-attachments/assets/df53e32e-7e60-4256-8378-ebd73fcae0f0

**Comment by tribhuwan-kumar** [comment]
> issue with button to open logs on windows, maybe some issue with slashes?
> <img alt="Screenshot 2024-11-01 at 10 09 00 AM" width="200" src="https://private-user-images.githubusercontent.com/25003283/382352533-13c937c2-0d20-4f33-b5eb-780cfc847ecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1Mjc0NTQsIm5iZiI6MTczMDUyNzE1NCwicGF0aCI6Ii8yNTAwMzI4My8zODIzNTI1MzMtMTNjOTM3YzItMGQyMC00ZjMzLWI1ZWItNzgwY2ZjODQ3ZWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDA1NTkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ODk3YTJkMjZkZDhkMzU4MWNiOWVlOTU3ZWYxNmFiNjFjYmQxNDFlZjdmMGE1MTI4MDUxNjliYmMwNTM3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tdaKHqdUsBdFKBMPibJctjWw2EwNtF0TwvZCGCPwX6k">
> 

can't reproduce it, maybe there isn't even error, i think user might had deleted his log file, idk what the issue

<video width="400" src="https://github.com/user-attachments/assets/5d759b2a-9bd4-4a92-8337-62eda2ada212">
<video/>

**Comment by Neptune650** [comment]
> /bounty 100 
> 
> #574 <- need to make sure the process and all subprocess are closed when doing updates
> 
> issue with button to open logs on windows, maybe some issue with slashes?
> 
> <img width="878" alt="Screenshot 2024-11-01 at 10 09 00 AM" src="https://github.com/user-attachments/assets/13c937c2-0d20-4f33-b5eb-780cfc847ecb">
> 
> 
> 
> bonus: 
> 
> - #543 - to reproduce: open task manager and start screenpipe, does it crashes? any simple fix appreciated 
> - #376 
> 
> 
> 
> @Neptune650 maybe you can help? or anyone else
> 
> 

@louis030195 Much like @tribhuwan-kumar, I'm actually unable to reproduce most of the issues you listed.
