### ISSUE TITLE
[question] error: failed to run custom build command for `mac-notification-sys v0.6.1`

### ISSUE THREAD

**Issue by anirudhkannan9** [mediar-ai/screenpipe#626]
I'm following the steps under "macos installation" in the docs: https://docs.screenpi.pe/docs/getting-started. Specifically, I'm trying to build the Desktop app from source. 

Everything until and including `bun scripts/pre_build.js` seems to go fine. 

`bun tauri build` returns the following (I can't fit the entire message body here due to character count limitations, so I'm just adding the part where it fails + the part directly before it fails):

`error: failed to run custom build command for `mac-notification-sys v0.6.1`

Caused by:
  process didn't exit successfully: `/Users/kannana1/Developer/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/mac-notification-sys-bbb1ec8d24cd3978/build-script-build` (exit status: 1)
  --- stdout
  OUT_DIR = Some(/Users/kannana1/Developer/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/mac-notification-sys-2ab65e2c6d36e6a5/out)
  TARGET = Some(aarch64-apple-darwin)
  OPT_LEVEL = Some(3)
  HOST = Some(aarch64-apple-darwin)
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
  MACOSX_DEPLOYMENT_TARGET = Some(10.13)
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/module.modulemap:13:8: error: redefinition of module 'SwiftBridging'
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/bridging.modulemap:13:8: note: previously defined here
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'Foundation' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
  cargo:warning=While building module 'CoreServices' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:15:
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/module.modulemap:13:8: error: redefinition of module 'SwiftBridging'
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/bridging.modulemap:13:8: note: previously defined here
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'Foundation' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
  cargo:warning=In file included from <module-includes>:1:
  cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:95:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:15:9: fatal error: could not build module 'CoreServices'
  cargo:warning=#import <CoreServices/CoreServices.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=In file included from <module-includes>:1:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:9: fatal error: could not build module 'Foundation'
  cargo:warning=#import <Foundation/Foundation.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=In file included from <module-includes>:1:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:10:9: fatal error: could not build module 'Foundation'
  cargo:warning=#import <Foundation/Foundation.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'ApplicationServices' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:10:
  cargo:warning=In file included from <module-includes>:1:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:10: fatal error: could not build module 'CoreServices'
  cargo:warning=#include <CoreServices/CoreServices.h>
  cargo:warning= ~~~~~~~~^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'ApplicationServices' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:10:
  cargo:warning=While building module 'CoreText' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Headers/SFNTLayoutTypes.h:16:
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/module.modulemap:13:8: error: redefinition of module 'SwiftBridging'
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/bridging.modulemap:13:8: note: previously defined here
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'ApplicationServices' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:10:
  cargo:warning=While building module 'ImageIO' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:47:
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/module.modulemap:13:8: error: redefinition of module 'SwiftBridging'
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/bridging.modulemap:13:8: note: previously defined here
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'CoreData' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSKeyValueBinding.h:12:
  cargo:warning=In file included from <module-includes>:1:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreData.framework/Headers/CoreData.h:8:9: fatal error: could not build module 'Foundation'
  cargo:warning=#import <Foundation/Foundation.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'CoreData' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSKeyValueBinding.h:12:
  cargo:warning=While building module 'CloudKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreData.framework/Headers/NSPersistentCloudKitContainerOptions.h:12:
  cargo:warning=In file included from <module-includes>:1:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CloudKit.framework/Headers/CloudKit.h:8:9: fatal error: could not build module 'Foundation'
  cargo:warning=#import <Foundation/Foundation.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'CoreData' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSKeyValueBinding.h:12:
  cargo:warning=While building module 'CloudKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreData.framework/Headers/NSPersistentCloudKitContainerOptions.h:12:
  cargo:warning=While building module 'CoreLocation' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CloudKit.framework/Headers/CKRecord.h:14:
  cargo:warning=In file included from <module-includes>:1:
  cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CoreLocation.h:18:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLErrorDomain.h:10:9: fatal error: could not build module 'Foundation'
  cargo:warning=#import <Foundation/Foundation.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'CoreImage' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSColor.h:51:
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/module.modulemap:13:8: error: redefinition of module 'SwiftBridging'
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/bridging.modulemap:13:8: note: previously defined here
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'CoreImage' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSColor.h:51:
  cargo:warning=In file included from <module-includes>:1:
  cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CoreImage.h:9:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CoreImageDefines.h:19:9: fatal error: could not build module 'Foundation'
  cargo:warning=#import <Foundation/Foundation.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'CoreImage' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSColor.h:51:
  cargo:warning=While building module 'CoreVideo' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CIImage.h:15:
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/module.modulemap:13:8: error: redefinition of module 'SwiftBridging'
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/bridging.modulemap:13:8: note: previously defined here
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'CoreImage' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSColor.h:51:
  cargo:warning=While building module 'CoreVideo' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CIImage.h:15:
  cargo:warning=In file included from <module-includes>:1:
  cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CoreVideo.h:29:
  cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVPixelBuffer.h:23:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVImageBuffer.h:29:10: fatal error: could not build module 'ApplicationServices'
  cargo:warning=#include <ApplicationServices/ApplicationServices.h>
  cargo:warning= ~~~~~~~~^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'CoreImage' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSColor.h:51:
  cargo:warning=While building module 'CoreVideo' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CIImage.h:15:
  cargo:warning=While building module 'IOSurface' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVPixelBufferIOSurface.h:31:
  cargo:warning=In file included from <module-includes>:4:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/IOSurface.framework/Headers/IOSurfaceObjC.h:15:9: fatal error: could not build module 'Foundation'
  cargo:warning=#import <Foundation/Foundation.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'CoreImage' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSColor.h:51:
  cargo:warning=While building module 'CoreVideo' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CIImage.h:15:
  cargo:warning=While building module 'Metal' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVMetalTextureCache.h:41:
  cargo:warning=In file included from <module-includes>:1:
  cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Metal.framework/Headers/Metal.h:9:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLTypes.h:8:9: fatal error: could not build module 'Foundation'
  cargo:warning=#import <Foundation/Foundation.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'Symbols' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSImageView.h:12:
  cargo:warning=In file included from <module-includes>:1:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Symbols.framework/Headers/Symbols.h:8:9: fatal error: could not build module 'Foundation'
  cargo:warning=#import <Foundation/Foundation.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'QuartzCore' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGLLayer.h:11:
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/module.modulemap:13:8: error: redefinition of module 'SwiftBridging'
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=/Library/Developer/CommandLineTools/usr/include/swift/bridging.modulemap:13:8: note: previously defined here
  cargo:warning=module SwiftBridging {
  cargo:warning=       ^
  cargo:warning=While building module 'Cocoa' imported from objc/notify.h:1:
  cargo:warning=While building module 'AppKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
  cargo:warning=While building module 'QuartzCore' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGLLayer.h:11:
  cargo:warning=In file included from <module-includes>:1:
  cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/QuartzCore.h:16:
  cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CoreAnimation.h:10:
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CATransform3D.h:12:9: fatal error: could not build module 'Foundation'
  cargo:warning=#import <Foundation/NSValue.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=In file included from objc/notify.m:1:
  cargo:warning=objc/notify.h:1:9: fatal error: could not build module 'Cocoa'
  cargo:warning=#import <Cocoa/Cocoa.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=21 errors generated.

  --- stderr

  error occurred: Command env -u IPHONEOS_DEPLOYMENT_TARGET "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=arm64-apple-darwin" "-mmacosx-version-min=10.13" "-Wall" "-Wextra" "-fmodules" "-Wno-deprecated-declarations" "-mmacos-version-min=10.13" "-o" "/Users/kannana1/Developer/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/mac-notification-sys-2ab65e2c6d36e6a5/out/307ac93856b42bcb-notify.o" "-c" "objc/notify.m" with args cc did not execute successfully (status code exit status: 1).

warning: build failed, waiting for other jobs to finish...
failed to build app: failed to build app
    Error failed to build app: failed to build app
error: script "tauri" exited with code 1`

**Comment by louis030195** [comment]
@anirudhkannan9 can you share details on your OS version, architecture etc.?

maybe you need to run the xcode update, not sure

**Comment by anirudhkannan9** [comment]
My OS version is 15.0.1 (Sequoia), and my architecture is arm64.

**Comment by anirudhkannan9** [comment]
My OS version is 15.0.1 (Sequoia), and my architecture is arm64.

**Comment by louis030195** [comment]
maybe it helps:

Let me analyze this error systematically. Here are 30 potential reasons for the `mac-notification-sys` build failure in a Tauri app:

### Development Environment Issues
1. **xcode command line tools** outdated or corrupted
2. **swift modules conflict** (evident from SwiftBridging redefinition errors)
3. **macos sdk** version mismatch with MacOS 15.0.1
4. **incomplete xcode installation**
5. **multiple xcode versions** causing conflicts

### System Configuration
6. **incorrect MACOSX_DEPLOYMENT_TARGET** (currently set to 10.13)
7. **architecture mismatch** in build settings
8. **path environment variables** not properly set
9. **system headers corruption**
10. **conflicting system frameworks**

### Build Configuration
11. **rust toolchain** version incompatibility
12. **cargo dependencies** version conflicts
13. **incorrect target architecture** settings
14. **missing build prerequisites**
15. **incompatible build flags**

### Framework Issues
16. **foundation framework** import failures
17. **cocoa framework** dependency issues
18. **core services** module build failures
19. **application services** import problems
20. **cloud kit** dependency resolution failures

### Permission/Access Issues
21. **insufficient permissions** for build directories
22. **locked system files**
23. **read-only system volume**
24. **security settings** blocking framework access
25. **sandbox restrictions**

### Tauri Specific
26. **incompatible tauri version** with macos version
27. **tauri build configuration** issues
28. **tauri dependencies** version mismatch
29. **sidecar configuration** problems
30. **notification system plugin** compatibility issues

### Most Likely Solutions:
1. Run `xcode-select --install`
2. Update Xcode to latest version
3. Clean build cache and rebuild
4. Check system integrity with `sfc /scannow`
5. Verify all required frameworks are properly installed

#rust #macos #tauri #debugging

**Comment by louis030195** [comment]
@anirudhkannan9 did you try these?
