### ISSUE TITLE
[bounty] impl icon fetch on windows (& linux)

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#643]
https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-app-tauri/src-tauri/src/icons.rs

also remove this if

https://github.com/mediar-ai/screenpipe/blob/d83d787b1554819beb817c4e9b90de00e77da3a2/screenpipe-app-tauri/components/timeline/timeline-dock.tsx#L236

and check this properly show on timeline 

/bounty 50 

if possible check it does not create memory leaks or stuff dealing w low level code

**Comment by naaa760** [comment]
I think, the code fetches app icons on all three platforms: macOS, Windows, and Linux. For Windows, it extracts icons from `.exe` files using system APIs. For Linux, it searches in standard directories like `/usr/share/icons`, and for macOS, it uses Cocoa APIs. The icons are converted to PNG and encoded in Base64 for consistent results across all platforms.

**Comment by louis030195** [comment]
@tribhuwan-kumar wanna try?

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar wanna try?

sure!

**Comment by tribhuwan-kumar** [comment]
@louis030195 
the real pain is getting the exe path of application by their name, cz the only valid parameter got pass is `appName`. the `appPath` is optional so it won't getting pass in `get_app_icon` func & without exe path its not possible to extract icon.

also windows is so inconsistent that there isn't a single package database which contains all the info about installed app or packages,even if i iterate over registry keys i will not get the exact exe path of all application. for system apps like terminal & file manager i've to use different approach and if the app is installed from microsoft store then that's an another case!

any better solution you can suggest?

**Comment by louis030195** [comment]
> @louis030195 the real pain is getting the exe path of application by their name, cz the only valid parameter got pass is `appName`. the `appPath` is optional so it won't getting pass in `get_app_icon` func & without exe path its not possible to extract icon.
> 
> also windows is so inconsistent that there isn't a single package database which contains all the info about installed app or packages,even if i iterate over registry keys i will not get the exact exe path of all application. for system apps like terminal & file manager i've to use different approach and if the app is installed from microsoft store then that's an another case!
> 
> any better solution you can suggest?

IDK anything about windows, chatgpt will be smarter than me here

**Comment by tribhuwan-kumar** [comment]
@louis030195 
the alpha version seems working :)

![image](https://github.com/user-attachments/assets/a6fe925b-c348-418d-a922-c9d5183bcd1c)
![image](https://github.com/user-attachments/assets/eebbc128-4e71-48ea-806b-c6bf40f9cbf7)

**Comment by tribhuwan-kumar** [comment]
![image](https://github.com/user-attachments/assets/c326f897-5e17-4a8c-a547-7ad134031587)

what if exe doesn't have icon, as an eg. whatsapp exe doesn't contain whatspp icon it just a blank icon

**Comment by tribhuwan-kumar** [comment]
![image](https://github.com/user-attachments/assets/d4542a3b-9b99-4ef3-80b3-6154d4fea616)

got most of icons but there is icon size issue!
