### ISSUE TITLE
[bug] timeline UX issue

### ISSUE THREAD

**Issue by ianmiell** [mediar-ai/screenpipe#664]
**describe the bug**

Repeated errors like this seen in the logs:

```
2024-11-10T13:16:57.297542Z ERROR screenpipe_server::server: frame cache not initialized    
2024-11-10T13:16:57.556187Z  INFO screenpipe_server::resource_monitor: Runtime: 81s, Total Memory: 0% (0 GB / 16 GB), Total CPU: 3%, NPU: N/A
2024-11-10T13:17:00.432084Z  INFO screenpipe_server::server: streaming frames from 2024-11-10 00:01:00 UTC to 2024-11-10 13:13:36.571 UTC    
```

resulting in state:

```
screen recording status: stale, last update: 10/11/2024, 12:53:12
audio recording status: ok, last update: 10/11/2024, 13:18:51
```

**to reproduce**
1. Start up screenpipe

**expected behavior**
Should start in green

**system info**
- MacOS 14.3.1 (23D60)

**additional context**
Happens regularly/often but not 100% of the time. Seems to happen after a whiel of screenpipe being up also.

**Comment by louis030195** [comment]
@ianmiell i think this is because you tried to use the timeline feature without having enabled it (somehow)

i can figure out how to make this more intuitive 

you can try to disable timeline in settings and click update and restart to fix this (or not opening the timeline window without enabling the feature)

**Comment by louis030195** [comment]
> @ianmiell i think this is because you tried to use the timeline feature without having enabled it (somehow)
> 
> i can figure out how to make this more intuitive
> 
> you can try to disable timeline in settings and click update and restart to fix this (or not opening the timeline window without enabling the feature)

update: the error shouldnt cause any issues "frame cache not initialized"

**Comment by louis030195** [comment]
there was an issue with ffmpeg that we fixed, does it work for you now?

**Comment by ianmiell** [comment]
I no longer see that error in the logs, thanks.
