### ISSUE TITLE
[bounty] enable x265 on macos

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#666]
please see https://github.com/mediar-ai/screenpipe/pull/580

h265 does not render in app ui:
<img width="1312" alt="Screenshot 2024-11-13 at 9 29 51 AM" src="https://github.com/user-attachments/assets/89902fa3-905a-4197-85da-b0faa6eb6a14">

https://github.com/mediar-ai/screenpipe/blob/e70445b15f3973563dc3997489553a6ac6a3e9f3/screenpipe-server/src/video.rs#L171

/bounty 100

**Comment by developerfred** [comment]
/attempt #666 I will add support to the video.rs

**Comment by louis030195** [comment]
@ologbonowiwi does not work fyi

**Comment by ologbonowiwi** [comment]
I was OOO for the weekend. I want to get this working but search pipe is not working here, (likely #1001)

**Comment by louis030195** [comment]
what do you mean is not working?

windows
<img width="1512" alt="Screenshot 2024-12-18 at 7 43 47 AM" src="https://github.com/user-attachments/assets/f05f3c4c-8af2-4258-aeca-89d7556cfc39" />

macos

<img width="1512" alt="Screenshot 2024-12-18 at 7 44 34 AM" src="https://github.com/user-attachments/assets/304a3a47-9cb8-465a-8be3-114079071faa" />


#1001 is UX problem - user don't understand you cannot see video being written

**Comment by ologbonowiwi** [comment]
did you considered open source alternatives to h265 such as av1 or vp9?

the original app/tauri browser is webkit based thus it supports h265, chromium pays royalties to have it on Windows, and Firefox does not support at all. using h265 videos would not work on Firefox, and can probabky work on Chrome but I'm not sure how yet. but let me know if you would consider av1 or vp9 instead, as they are open source and free we'd have more wide support. let me know your thoughts on it.
