### ISSUE TITLE
[bounty] obsidian pipe (markdown file)

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#676]
same than 

https://github.com/mediar-ai/screenpipe/tree/main/examples/typescript/pipe-phi3.5-engineering-team-logs

but instead of writing to notion it would add to a markdown file on disk

definition of done:
- user can select the location of logs in pipe settings 
- user can provide custom prompt 
- use pipe.schedule API 
- works with openai or ollama using vercel/ai lib (user can choose)
- any other settings to customise experience
- i think it would write logs in a file with current day (obsidian timestamp like thing) and append for the same day then create new note for each new day 

(i'd be user of this)

/bounty 70

bonus if you do a cool video (less than 2 min) launching this and sharing on obsidian forum :)

**Comment by Csaba8472** [comment]
/attempt #676

Hello I'm also a obsidian user, I've started implementing similar solution, which goes through on my day and summary what I've done and calculate how many hours I've spent.
