### ISSUE TITLE
[bounty] speaker identification (next steps)

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#695]
WIP

also i'm curious how we could associate frames to specific person (speaker) somehow (and thus screen text) but this is lower priority

/bounty 300

(TBD what is exactly the things to do)

**Comment by louis030195** [comment]
<img width="1512" alt="Screenshot 2024-11-18 at 1 33 07 PM" src="https://github.com/user-attachments/assets/b74033be-b745-44db-b643-8752da2ce0f1">
kinda tihkning about google photo ui 

i think we need similar for speaker identification over long ranges, eg "listen to this voice, is it john? can you tell me the name?"

**Comment by louis030195** [comment]
@EzraEllette what do you mean by "Attempt to use LLM for identification through meeting context"

we already do this in meeting page

**Comment by EzraEllette** [comment]
> @EzraEllette what do you mean by "Attempt to use LLM for identification through meeting context"
> 
> we already do this in meeting page

When this function is called, It should now be able to update speaker information in the database with user permission.

**Comment by NicodemPL** [comment]
Limitless uses emails/names from calendar events. Might be good idea to implement calendar to meetings at this stage.

Other idea - OCR from meeting frames to find and confirm names. We already have this data (OCR)

**Comment by louis030195** [comment]
@EzraEllette fyi build is down because of sqlite extension i feel like

https://github.com/mediar-ai/screenpipe/actions/runs/11904908266/job/33174510422
https://github.com/mediar-ai/screenpipe/actions/runs/11904908266/job/33174511134

**Comment by EzraEllette** [comment]
> @EzraEllette fyi build is down because of sqlite extension i feel like
> 
> 
> 
> https://github.com/mediar-ai/screenpipe/actions/runs/11904908266/job/33174510422
> 
> https://github.com/mediar-ai/screenpipe/actions/runs/11904908266/job/33174511134

It looks like knfc. I will debug when I get a chance
