### ISSUE TITLE
[bug] audio transcription broke

### ISSUE THREAD

**Issue by m13v** [mediar-ai/screenpipe#701]
the database audio transcription records are overwritten, sometimes even left empty, see video.
Potentially, it has to do with the overlap logic and the way we update the transcription records
@EzraEllette 
https://github.com/user-attachments/assets/cb0f10b6-1574-4a1e-89bd-ffb545acbfd1

**Comment by EzraEllette** [comment]
Thanks for sharing this. I'll look into the issue today.
