### ISSUE TITLE
[bounty] fix build

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#719]
fix this build https://github.com/mediar-ai/screenpipe/actions/runs/11939682888

/bounty 50

**Comment by tribhuwan-kumar** [comment]
@louis030195 yesterday, i tried to fix this issue, the problem is with 

```
   Compiling ***-server v0.1.98 (C:\actions-runner\_work\***\***\***-server)
warning: `***-audio` (lib) generated 1 warning
error: linking with `link.exe` failed: exit code: 1120
```
the problem is mismatching library 

```
  = note: libesaxx_rs-5f8759179c2bdae5.rlib(2e40c9e35e9506f4-esaxx.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in libknf_rs_sys-513cae2b40755cb4.rlib(knfc.obj)␍
 ```
 
 maybe this could fix from here
 
 https://github.com/mediar-ai/screenpipe/blob/28726fcbca0153d84e006ee048f4ac0d81e1e4e8/.cargo/config.toml#L1
