### ISSUE TITLE
[bounty] move as much as possible code from pre_build.js to build.rs

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#720]
atm we have lot of pre build thing in pre_build.js script used for the app but we want to make it easy to use the CLI

installation of screenpipe as a CLI or app should be dead simple in less than 2 minutes from install to run and work on most OSes

for example onnxruntime dll stuff for windows should be in build.rs of screenpipe audio so can use CLI without app and more rust native 

/bounty 100

will add bonus if you do more than the onnxruntime thing

**Comment by Neptune650** [comment]
@louis030195 Do you suggest that pre_build.js should only have stuff used in the app? How do you feel about moving the ollama sidecar too then
