### ISSUE TITLE
[bug] Run cargo build --release on window have error 

### ISSUE THREAD

**Issue by RainSoloVN** [mediar-ai/screenpipe#724]
**describe the bug**
brief description of the bug.

**to reproduce**
1. install all library
2. to step, "cargo build --release"
3. error occur

**expected behavior**
what should happen?
When I run command "cargo build --release" on Window 11, I receive the error: " mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in libknf_rs_sys-18676f0b7014dd73.rlib(knfc.obj)"

**system info**
- os: windows 11
- screenpipe version: 0.1.98

**additional context**
add any other context, screenshots, or error logs here.
![image](https://github.com/user-attachments/assets/1ca13b1e-920c-46ea-9224-e8b11d852c3e)
"note: libesaxx_rs-1319760f5c75a303.rlib(2e40c9e35e9506f4-esaxx.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in libknf_rs_sys-18676f0b7014dd73.rlib(knfc.obj)␍
             Creating library C\screenpipe_audio.lib and object \screenpipe_audio.exp␍
          screenpipe_audio.exe : fatal error LNK1319: 1 mismatches detected␍"

**Comment by tribhuwan-kumar** [comment]
@RainSoloVN 
this issue is causing since this commit https://github.com/mediar-ai/screenpipe/commit/478fb051e7aa1d36537a08afe5443407e8e54646,
i'm fixing it, till now you can switch git node to https://github.com/mediar-ai/screenpipe/commit/d96d28d8, by this command

```bash
git reset --hard d96d28d8
```

**Comment by RainSoloVN** [comment]
@tribhuwan-kumar Thank you for your answer. I built successfully. I hope you fix it soon.
