### ISSUE TITLE
[bounty] automate brew linux

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#728]
automate brew linux

/bounty 50

**Comment by louis030195** [comment]
@krushnarout if you want

**Comment by krushnarout** [comment]
> @krushnarout if you want

sure

**Comment by krushnarout** [comment]
@louis030195 I don't think there's any need to set up anything to automate `brew update` for Linux.

Here's an example:  
https://github.com/Homebrew/homebrew-core/pull/198796  

When a new release is made and a pull request is created using the `brew bump-formula-pr` method, it updates the URL and `sha256`.  

https://github.com/Homebrew/homebrew-core/pull/198796/commits/1771d76c5b5c5cb2fe8a31477fc8002cf615f08a

<img width="1033" alt="Screenshot 2024-11-24 at 11 13 05 PM" src="https://github.com/user-attachments/assets/e78929f5-363f-474d-9816-e1b8d93efa0c">

After a maintainer approves the changes, the BrewTestBot automatically commits updates, including changes to all bottle `sha256` values, even for Linux.  

https://github.com/Homebrew/homebrew-core/pull/198796/commits/a97ee35eae4b325a505ab37eb9a94556abf4617c

<img width="1169" alt="Screenshot 2024-11-24 at 11 13 40 PM" src="https://github.com/user-attachments/assets/261c0508-028e-4f09-9465-eedebce1eac9">

So, only #743 needs to be merged, and the Linux version will be updated as well.
