### ISSUE TITLE
[question] use PRs for new features

### ISSUE THREAD

**Issue by thewh1teagle** [mediar-ai/screenpipe#746]
Please use PRs for new commits in main instead of pushing directly to main
And squash the commits from the PR so it won't merge multiple commits from the PR but instead single commit

**context**
It's hard to keep track of the new changes in in screenpipe (In PRs we should get notification) and also the main branch history has too many irrelevant commits

Personally I also like to push directly to main :) but I big projects it's worth not do that at all and in worst case just create PRs such as `patch-1` or `patch-2` etc.

btw with github cli it's easy as 

```console
gh pr create
gh pr merge
```

**Comment by louis030195** [comment]
thx, will try to be more careful
