### ISSUE TITLE
How to get Frree-Community version?

### ISSUE THREAD

**Issue by xteam777** [mediar-ai/screenpipe#748]
After submitting the form for the Free-version, nothing came to the mail
ask your question here. be as specific as possible.

https://screenpi.pe/onboarding/free-community

**Comment by volfcan** [comment]
you can build it from source

**Comment by xteam777** [comment]
I compiled it and ran it. Screenpipe.exe listens to my microphone. How do I give it voice commands?

**Comment by xteam777** [comment]
screenpipe.exe is running on CUDA. Listens to the microphone. Displays what I say, like “open calculator”. But it doesn't do anything. How do I get it to work?

**Comment by louis030195** [comment]
@xteam777 can you explain with more details plz? 

screenpipe is free now: https://screenpi.pe/
