### ISSUE TITLE
[bug] pre_build.js error on windows

### ISSUE THREAD

**Issue by winic57** [mediar-ai/screenpipe#752]
**describe the bug**
build windows clinet,ShellError: Failed with exit code 1

**to reproduce**
1. steps to install on windows
2. cd screenpipe-app-tauri
bun install
bun scripts\pre_build.js # (you might wget not retriving error, if so use '-O' flag) <- this is important to copy the CLI into the app

**expected behavior**
what should happen?
![image](https://github.com/user-attachments/assets/ecf4e4d1-0d24-45db-a864-9b8881cfa3be)

**system info**
- os: [e.g.  windows 11]
- screenpipe version: [0.1.98]

**additional context**
here is a hard code which assgin vcpkg.exe path

**Comment by louis030195** [comment]
@winic57 can you try again now? changed code

**Comment by pomazanbohdan** [comment]
I launch and no this error.
But 

`Commands to build 🔨:
bun install
$env:FFMPEG_DIR = "C:\_temp\screenpipe\screenpipe-app-tauri\src-tauri\ffmpeg"
$env:OPENBLAS_PATH = "undefined"
$env:LIBCLANG_PATH = "C:\Program Files\LLVM\bin"
$env:PATH += "C:\Program Files\CMake\bin"
bun tauri build
checking bun binary for tauri...
86 |    console.log('checking bun binary for tauri...');
87 |
88 |    let bunSrc, bunDest1, bunDest2;
89 |    if (platform === 'windows') {
90 |            // Get and log npm global prefix
91 |            const npmGlobalPrefix = (await $`npm config get prefix`.text()).trim();
                    ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at C:\_temp\screenpipe\screenpipe-app-tauri\scripts\pre_build.js:91:34
      at copyBunBinary (C:\_temp\screenpipe\screenpipe-app-tauri\scripts\pre_build.js:85:29)
      at C:\_temp\screenpipe\screenpipe-app-tauri\scripts\pre_build.js:598:7

Bun v1.1.38 (Windows x64)`

**Comment by pomazanbohdan** [comment]
https://github.com/oven-sh/bun/issues/6987
https://github.com/oven-sh/bun/discussions/11897

**Comment by pomazanbohdan** [comment]
I install nodejs, and script run, but nodejs owerhead else use bun, and doc does not contain info nodejs need install

**Comment by louis030195** [comment]
what command did you run exactly?

don't understand the issue
