### ISSUE TITLE
[bounty] $150 build windows CLI and make it installable & usable in less than 60 seconds

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#757]
definition of done:
- windows CLI is being built somewhere convenient in the CI/CD (`release-cli` along linux and mac brew stuff) and uploaded build somewhere (like releases)
- docs is updated, clear
- dependencies are packaged with the CLI somehow 

/bounty 150

**Comment by varshith257** [comment]
Will give it a shot!
/attempt #757

**Comment by louis030195** [comment]
done
