### ISSUE TITLE
[question] pipe-obsidian-time-logs doesn't work?

### ISSUE THREAD

**Issue by bystritskiy** [mediar-ai/screenpipe#761]
## Problem with [pipe-obsidian-time-logs](https://github.com/mediar-ai/screenpipe/tree/419a1fbbbef8c44da8303d47fdb34e0948e8c45b/examples/typescript/pipe-obsidian-time-logs)

When running the pipe-obsidian-time-logs pipeline, an error occurs in the work log stream. Logs indicate an issue with making an API call to http://localhost:11434/api/chat. The server specified in the ollamaApiUrl field appears to be unavailable or returning a “Not Found” error.

## Logs
```
➜  ~ screenpipe --debug  2>&1 | grep "pipe-obsidian-time-logs" 

2024-11-25T21:19:21.907616Z DEBUG screenpipe: pipe: "pipe-obsidian-time-logs"
2024-11-25T21:19:21.907735Z DEBUG screenpipe_server::pipe_manager: Updating config for pipe: pipe-obsidian-time-logs
2024-11-25T21:19:21.908875Z DEBUG screenpipe: enabling pipe: pipe-obsidian-time-logs
2024-11-25T21:19:21.909203Z DEBUG screenpipe_server::pipe_manager: Updating config for pipe: pipe-obsidian-time-logs
2024-11-25T21:19:21.909289Z  INFO screenpipe_core::pipes::pipes: executing pipe: "/Users/user/.screenpipe/pipes/pipe-obsidian-time-logs/pipe.ts"
2024-11-25T21:19:22.001431Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs] starting work logs stream
2024-11-25T21:19:22.001581Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs] loaded config: {
2024-11-25T21:19:22.001586Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs]   "interval": 60,
2024-11-25T21:19:22.001588Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs]   "obsidianPath": "",
2024-11-25T21:19:22.001590Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs]   "customPrompt": "",
2024-11-25T21:19:22.001592Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs]   "gptModel": "gpt-4o",
2024-11-25T21:19:22.001594Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs]   "openaiApiKey": "",
2024-11-25T21:19:22.001595Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs]   "ollamaApiUrl": "http://localhost:11434/api",
2024-11-25T21:19:22.001597Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs]   "ollamaModel": "llama3.2:3b-instruct-q4_K_M",
2024-11-25T21:19:22.001600Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs]   "pageSize": 100
2024-11-25T21:19:22.001602Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs] }
2024-11-25T21:19:22.014115Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs] action server listening on port 55149
2024-11-25T21:19:22.015110Z  INFO screenpipe_core::pipes::pipes: [pipe][info][pipe-obsidian-time-logs] action server listening on port 55149
2024-11-25T21:20:00.154164Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs] error in work log pipeline: 57 |   constructor({
2024-11-25T21:20:00.154180Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs] 58 |     name: name14,
2024-11-25T21:20:00.154182Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs] 59 |     message,
2024-11-25T21:20:00.154185Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs] 60 |     cause
2024-11-25T21:20:00.154187Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs] 61 |   }) {
2024-11-25T21:20:00.154209Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs] 62 |     super(message);
2024-11-25T21:20:00.154213Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs]          ^
2024-11-25T21:20:00.154215Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs] AI_APICallError: Not Found
2024-11-25T21:20:00.154218Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs]  url: "http://localhost:11434/api/chat"
2024-11-25T21:20:00.154220Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs] 
2024-11-25T21:20:00.154223Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs]       at new _AISDKError (/Users/.bun/install/cache/@ai-sdk/provider@1.0.1@@@1/dist/index.js:62:5)
2024-11-25T21:20:00.154226Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs]       at new APICallError (/Users/.bun/install/cache/@ai-sdk/provider@1.0.1@@@1/dist/index.js:129:5)
2024-11-25T21:20:00.154228Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs]       at /Users/user/.bun/install/cache/@ai-sdk/provider-utils@2.0.2@@@1/dist/index.js:514:35
2024-11-25T21:20:00.154231Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs]       at processTicksAndRejections (native:7:39)
2024-11-25T21:20:00.154233Z ERROR screenpipe_core::pipes::pipes: [pipe][error][pipe-obsidian-time-logs] 
```

**Comment by louis030195** [comment]
@bystritskiy hey make sure to run ollama beforehand or screenpipe embedded AI feature
<img width="1312" alt="Screenshot 2024-11-26 at 11 04 46 AM" src="https://github.com/user-attachments/assets/d23a8fe4-d685-4055-adb6-05ba5aaf1cf0">

**Comment by louis030195** [comment]
<img width="1512" alt="Screenshot 2024-11-26 at 11 05 11 AM" src="https://github.com/user-attachments/assets/e7487356-da2d-4c0b-b214-74d20f8db29a">

**Comment by Charghoul** [comment]
I have the exact same issue, despite the correct model being loaded in the embedded ai and changing the llm port to 11434 like in the plugin required, as changing the port in the plugin doesn't have an effect.

**Comment by louis030195** [comment]
> I have the exact same issue, despite the correct model being loaded in the embedded ai and changing the llm port to 11434 like in the plugin required, as changing the port in the plugin doesn't have an effect.
> 
> ```
> [2m2024-12-02T10:17:00.912103Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs] error in work log pipeline: 57 |   constructor({
> �[2m2024-12-02T10:17:00.912108Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs] 58 |     name: name14,
> �[2m2024-12-02T10:17:00.912111Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs] 59 |     message,
> �[2m2024-12-02T10:17:00.912113Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs] 60 |     cause
> �[2m2024-12-02T10:17:00.912116Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs] 61 |   }) {
> �[2m2024-12-02T10:17:00.912118Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs] 62 |     super(message);
> �[2m2024-12-02T10:17:00.912121Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs]          ^
> �[2m2024-12-02T10:17:00.912123Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs] AI_APICallError: Not Found
> �[2m2024-12-02T10:17:00.912126Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs]  url: "http://localhost:11434/api/chat"
> �[2m2024-12-02T10:17:00.912128Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs] 
> �[2m2024-12-02T10:17:00.912131Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs]       at new _AISDKError (/Users/jan.eisenbarth/.bun/install/cache/@ai-sdk/provider@1.0.1@@@1/dist/index.js:62:5)
> �[2m2024-12-02T10:17:00.912133Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs]       at new APICallError (/Users/jan.eisenbarth/.bun/install/cache/@ai-sdk/provider@1.0.1@@@1/dist/index.js:102:5)
> �[2m2024-12-02T10:17:00.912135Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs]       at /Users/jan.eisenbarth/.bun/install/cache/@ai-sdk/provider-utils@2.0.2@@@1/dist/index.js:514:35
> �[2m2024-12-02T10:17:00.912137Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs] 
> ```
> 
> <img alt="image" width="873" src="https://private-user-images.githubusercontent.com/16914541/391503069-4a8911ee-5b95-43b9-8027-113c8b8cb922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTc3MzAsIm5iZiI6MTczMzE1NzQzMCwicGF0aCI6Ii8xNjkxNDU0MS8zOTE1MDMwNjktNGE4OTExZWUtNWI5NS00M2I5LTgwMjctMTEzYzhiOGNiOTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE2MzcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDAwNWQ5YTliOTRiNDJhM2RhOWEyMjg5ZGY0ZGYzMWM0NjE3M2M5MGZkZTdlNWExY2M1Y2RlZWVlNWNmNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3vawpdNCe96AriPc2Kkp6phfWKb6HVYrh8ZmFuRH0z4"> <img alt="image" width="619" src="https://private-user-images.githubusercontent.com/16914541/391503205-8643557e-48a0-4837-9427-848d6be167a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTc3MzAsIm5iZiI6MTczMzE1NzQzMCwicGF0aCI6Ii8xNjkxNDU0MS8zOTE1MDMyMDUtODY0MzU1N2UtNDhhMC00ODM3LTk0MjctODQ4ZDZiZTE2N2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE2MzcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNDY2OTczNzdjMjcwOTM4Yjg3MmY3YzU1OTNjMDc2MzA3MzM0ODRmMjk3YjYzOTNlOGFhNTY3ODAxMTg2NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OJP_1StGTkxiYrup2h9Y9qQAGmB8jQlHa2hCcJb5Los">

actually i started having this issue recently

i have used this pipe 24/7 for like 1 week++ and now this happen without code change so i suspect something change in dependency

https://github.com/ollama/ollama/blob/main/docs/openai.md

```
curl http://localhost:11434/v1/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "llama3.2",
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "Hello!"
            }
        ]
    }'
```

<img width="948" alt="image" src="https://github.com/user-attachments/assets/20c29bdf-aed2-4a3a-bf76-4b4b3dde818a">


https://github.com/sgomez/ollama-ai-provider

<img width="800" alt="image" src="https://github.com/user-attachments/assets/818a1d8f-7741-4942-8b1e-bd053a5569b0">


@sgomez would appreciate any idea why this happen? why is ollama provider not using the right path? and somehow it worked with the wrong path before 🤔🤔🤔

**Comment by hirowa** [comment]
@louis030195 

Obsidian Pipe also not working for me at the moment.
`[2m2024-12-03T02:58:01.898251Z[0m [31mERROR[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m [pipe-obsidian-time-logs] error: Cannot find package "ai" from "C:\Users\user\.screenpipe\pipes\pipe-obsidian-time-logs\pipe.ts"`

Do we need to install dependencies manually?

**Comment by louis030195** [comment]
> @louis030195
> 
> Obsidian Pipe also not working for me at the moment. `�[2m2024-12-03T02:58:01.898251Z�[0m �[31mERROR�[0m �[2mscreenpipe_core::pipes::pipes�[0m�[2m:�[0m [pipe-obsidian-time-logs] error: Cannot find package "ai" from "C:\Users\user\.screenpipe\pipes\pipe-obsidian-time-logs\pipe.ts"`
> 
> Do we need to install dependencies manually?

it should work in next release - thanks to this

https://github.com/mediar-ai/screenpipe/pull/826

**Comment by hirowa** [comment]
@louis030195 

I deleted the pipe and re-added it and it still has the same error.
I'll wait for the realease :)

Oh and btw, when checking #826 the obsidian pipe is not included in the list of pipes, don't know if that is intentional.

**Comment by louis030195** [comment]
/bounty 100

@sgomez can you help?

**Comment by sgomez** [comment]
The base URL is `schema://server:11434/api`, I guess you set `schema://server:11434/api/chat`.

Review your baseURL parameter and remove anything after `/api`.

**Comment by bystritskiy** [comment]
> The base URL is `schema://server:11434/api`, I guess you set `schema://server:11434/api/chat`.
> 
> Review your baseURL parameter and remove anything after `/api`.

<img width="1051" alt="Screenshot 2024-12-06 at 16 52 52" src="https://github.com/user-attachments/assets/df4651aa-a076-4dd3-b0b9-ad95b7841490">

That's how it was. Still doesn't work.

**Comment by sgomez** [comment]
Seems like a problem with bun and not related with my provider.

https://github.com/vercel/ai/issues/3278

@louis030195 which bun version are u using?

**Comment by louis030195** [comment]
> Seems like a problem with bun and not related with my provider.
> 
> [vercel/ai#3278](https://github.com/vercel/ai/issues/3278)
> 
> @louis030195 which bun version are u using?

@sgomez 1.1.38 i believe, sad

**Comment by louis030195** [comment]
i dont know why, it seems to work now

**Comment by sgomez** [comment]
The issue was solved in 1.1.34

Do you have traces about when you updated bun? Just to be sure that was the problem. Probably because it's a problem with the ai-sdk request layer. My provider is just using it, so anyway there are nothing else I can do just to trace the problem.

**Comment by hirowa** [comment]
Hey, I'm still getting this error og package "ai" not found.
Same thing for Notion. Is there something I'm doing wrong?


```
[2m2024-12-12T19:03:13.052845Z[0m [32m INFO[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m executing pipe: "C:\\Users\\HiroWa\\.screenpipe\\pipes\\pipe-obsidian-time-logs\\pipe.ts"
[2m2024-12-12T19:03:13.052871Z[0m [32m INFO[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m executing pipe: "C:\\Users\\HiroWa\\.screenpipe\\pipes\\pipe-notion-table-logs\\pipe.ts"
[2m2024-12-12T19:03:13.056450Z[0m [32m INFO[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m pipe execution completed successfully
[2m2024-12-12T19:03:13.056468Z[0m [32m INFO[0m [2mscreenpipe_server::pipe_manager[0m[2m:[0m started pipe: pipe-obsidian-time-logs with pid 30092
[2m2024-12-12T19:03:13.059925Z[0m [32m INFO[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m pipe execution completed successfully
[2m2024-12-12T19:03:13.059936Z[0m [32m INFO[0m [2mscreenpipe_server::pipe_manager[0m[2m:[0m started pipe: pipe-notion-table-logs with pid 31460
[2m2024-12-12T19:03:13.121983Z[0m [31mERROR[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m [pipe-notion-table-logs] error: Cannot find module "@notionhq/client" from "C:\Users\HiroWa\.screenpipe\pipes\pipe-notion-table-logs\pipe.ts"
[2m2024-12-12T19:03:13.130913Z[0m [31mERROR[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m [pipe-obsidian-time-logs] error: Cannot find package "ai" from "C:\Users\HiroWa\.screenpipe\pipes\pipe-obsidian-time-logs\pipe.ts"
[2m2024-12-12T19:03:13.343593Z[0m [32m INFO[0m [2mscreenpipe_server::video[0m[2m:[0m Starting FFmpeg process for file: C:\Users\HiroWa\.screenpipe\data\monitor_131073_2024-12-12_19-03-13.mp4    
[2m2024-12-12T19:03:13.436192Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-12-12 06:01:00 UTC to 2024-12-12 18:46:06.749 UTC    
[2m2024-12-12T19:03:19.076727Z[0m [32m INFO[0m [2mscreenpipe_audio::vad_engine[0m[2m:[0m Initializing SileroVad...
[2m2024-12-12T19:03:19.076832Z[0m [32m INFO[0m [2mscreenpipe_audio::vad_engine[0m[2m:[0m SileroVad Model downloaded to: "C:\\Users\\HiroWa\\AppData\\Local\\screenpipe\\vad\\silero_vad.onnx"
[2m2024-12-12T19:03:23.580900Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 10s, Total Memory: 0% (0.38 GB / 130.91 GB), Total CPU: 36%
[2m2024-12-12T19:03:28.089078Z[0m [32m INFO[0m [2mscreenpipe_audio::core[0m[2m:[0m starting continuous recording for Microphone (2- HyperX QuadCast S) (input) (30s segments)    
[2m2024-12-12T19:03:28.089214Z[0m [32m INFO[0m [2mscreenpipe_audio::core[0m[2m:[0m starting continuous recording for Speakers (Realtek USB Audio) (output) (30s segments)    
[2m2024-12-12T19:03:33.615493Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 20s, Total Memory: 0% (0.42 GB / 130.91 GB), Total CPU: 15%
[2m2024-12-12T19:03:43.660830Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 30s, Total Memory: 0% (0.44 GB / 130.91 GB), Total CPU: 16%
[2m2024-12-12T19:03:54.046965Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 41s, Total Memory: 0% (0.46 GB / 130.91 GB), Total CPU: 15%
[2m2024-12-12T19:03:58.164246Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (2- HyperX QuadCast S) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 479636, speech_frames: 0    
[2m2024-12-12T19:04:04.078481Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 51s, Total Memory: 0% (0.44 GB / 130.91 GB), Total CPU: 17%
[2m2024-12-12T19:04:14.122996Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 61s, Total Memory: 0% (0.55 GB / 130.91 GB), Total CPU: 28%
[2m2024-12-12T19:04:16.480053Z[0m [32m INFO[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m Processing pipe from source: https://github.com/mediar-ai/screenpipe/tree/main/pipes/pipe-obsidian-time-logs
[2m2024-12-12T19:04:16.480894Z[0m [32m INFO[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m Attempting to get raw GitHub URL for: https://github.com/mediar-ai/screenpipe/tree/main/pipes/pipe-obsidian-time-logs
[2m2024-12-12T19:04:16.480905Z[0m [32m INFO[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m Converted to GitHub API URL: https://api.github.com/repos/mediar-ai/screenpipe/contents/pipes/pipe-obsidian-time-logs?ref=main
[2m2024-12-12T19:04:18.955284Z[0m [32m INFO[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m pipe copied successfully to: "C:\\Users\\HiroWa\\.screenpipe\\pipes\\pipe-obsidian-time-logs"
[2m2024-12-12T19:04:18.962209Z[0m [32m INFO[0m [2mscreenpipe_server::pipe_manager[0m[2m:[0m pipe pipe-obsidian-time-logs downloaded
[2m2024-12-12T19:04:24.161746Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 71s, Total Memory: 0% (0.62 GB / 130.91 GB), Total CPU: 31%
[2m2024-12-12T19:04:26.048531Z[0m [32m INFO[0m [2mscreenpipe_server::pipe_manager[0m[2m:[0m pipe pipe-obsidian-time-logs restarted
[2m2024-12-12T19:04:26.050224Z[0m [32m INFO[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m executing pipe: "C:\\Users\\HiroWa\\.screenpipe\\pipes\\pipe-obsidian-time-logs\\pipe.ts"
[2m2024-12-12T19:04:26.051506Z[0m [32m INFO[0m [2mscreenpipe_server::pipe_manager[0m[2m:[0m pipe pipe-obsidian-time-logs restarted
[2m2024-12-12T19:04:26.052470Z[0m [32m INFO[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m executing pipe: "C:\\Users\\HiroWa\\.screenpipe\\pipes\\pipe-obsidian-time-logs\\pipe.ts"
[2m2024-12-12T19:04:26.053546Z[0m [32m INFO[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m pipe execution completed successfully
[2m2024-12-12T19:04:26.053558Z[0m [32m INFO[0m [2mscreenpipe_server::pipe_manager[0m[2m:[0m started pipe: pipe-obsidian-time-logs with pid 45792
[2m2024-12-12T19:04:26.056194Z[0m [32m INFO[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m pipe execution completed successfully
[2m2024-12-12T19:04:26.056206Z[0m [32m INFO[0m [2mscreenpipe_server::pipe_manager[0m[2m:[0m started pipe: pipe-obsidian-time-logs with pid 35632
[2m2024-12-12T19:04:26.088392Z[0m [31mERROR[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m [pipe-obsidian-time-logs] error: Cannot find package "ai" from "C:\Users\HiroWa\.screenpipe\pipes\pipe-obsidian-time-logs\pipe.ts"
[2m2024-12-12T19:04:26.088881Z[0m [31mERROR[0m [2mscreenpipe_core::pipes::pipes[0m[2m:[0m [pipe-obsidian-time-logs] error: Cannot find package "ai" from "C:\Users\HiroWa\.screenpipe\pipes\pipe-obsidian-time-logs\pipe.ts"
```

**Comment by louis030195** [comment]
@hirowa can you try deleting and re-downloading these? trash icon

**Comment by hirowa** [comment]
It works now, thanks @louis030195

**Comment by louis030195** [comment]
i'll release a v2 of this pipe with a UI soon, should be much better
