### ISSUE TITLE
windows install screenpipe didnt work

### ISSUE THREAD

**Issue by ChenYujie666** [mediar-ai/screenpipe#785]
error: failed to run custom build command for `libsamplerate-sys v0.1.12`

**Comment by louis030195** [comment]
@ChenYujie666 what did you do ?

**Comment by pomazanbohdan** [comment]
> [MED-344 windows install screenpipe didnt work](https://linear.app/mediar/issue/MED-344/windows-install-screenpipe-didnt-work)

You don't have access to this workspace.
Please contact the workspace admin to gain access.

**Comment by pomazanbohdan** [comment]
My case is like this, the command line starts, and nothing else appears.
```
PS C:\Users\pomaz> screenpipe
2024-12-08T11:11:44.465931Z  INFO screenpipe: screenpipe already in PATH at: C:\Users\pomaz\screenpipe\bin\screenpipe.exe
2024-12-08T11:11:44.466165Z  INFO screenpipe: screenpipe is available and properly set in the PATH
```
