### ISSUE TITLE
[bounty] $100-$300 pipe drop in replacement of granola app

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#786]
definition of done:
- copy 100% granola UI/UX, without the calendar/auth thing 

/bounty 100 

adding $200 if it match granola UI/UX

https://www.granola.ai/

**Comment by sibrash4** [comment]
### Implementation Plan

- Understand the granola app UI/UX: Familiarize yourself with the granola app's user interface and user experience. This includes understanding the layout, design elements, and user interactions.
- Set up the development environment: Ensure that you have all the necessary tools and dependencies installed. This includes setting up the development server as mentioned in the  content/docs/README.md
- Create a new branch: Create a new branch in your repository to work on the granola app replacement.
- Develop the UI components: Start developing the UI components that match the granola app's UI/UX. Use the existing components in the 
- screenpipe-app-tauri
 - directory as a reference.
- Implement the functionality: Implement the necessary functionality to ensure that the new app works as expected. This includes handling user interactions, data fetching, and state management.
- Test the app: Thoroughly test the app to ensure that it matches the granola app's UI/UX and works as expected. This includes testing on different devices and browsers.
- Review and refine: Review the code and make any necessary refinements to ensure that the app is of high quality.
- Submit a pull request: Once the app is complete, submit a pull request for review.

### Some Question:

- Should the new UI be focused on the new meeting sections, or affect or include the rest of the app as well?
- For the bonus part: I saw that the UI has to match granola but I noticed that the rest of the main page does not match the granola?

**Comment by louis030195** [comment]
this is wrong

**Comment by tribhuwan-kumar** [comment]
this granola ai, enhances the written meetings text in a predefined format which are called "templates"
![{9E7BDC84-156F-4A4C-850E-43E003CDAF87}](https://github.com/user-attachments/assets/19a90848-3dc1-4e27-b9f3-f466e43a9b54)

so this pipe have to listen every meeting or user have to start this pipe whenever he wants to attend meetings. 
in a notepad ui user can write any stuff he wants. 
a enhance button will make those written text in format, according to the meeting context and user prompts (have to define ai rules)
enhancing text should be in a template format
ui must be match to granola ai
share option of that note as pdf maybe??

@louis030195 
i haven't used this granola ai, maybe i'm missing something. please let me know!

**Comment by louis030195** [comment]
can you finish #804 first?

**Comment by oliverqx** [comment]
my attempt at #810 is nearly done, just need confirmation on design for onboarding flow.

in the meantime i thought i'd start working on design proposal for this pipe

**Comment by louis030195** [comment]
#1062 

more precise

**Comment by xiajixi76-beep** [comment]
Hi! I've built a Granola-like notes pipe for screenpipe as requested in this bounty.

## ?? Repository
https://github.com/xiajixi76-beep/screenpipe-granola-notes

## ? Features

? **Quick note input** - Type brief notes during meetings
? **AI enhancement** - Automatically enhances notes with details from audio transcripts
? **Meeting detection** - Detects when you're in Zoom/Teams/Google Meet
? **Local-first** - Works with Ollama (local) or OpenAI
? **Persistent storage** - Notes saved in localStorage
? **Markdown export** - Download all notes as Markdown
? **Clean UI** - React + Next.js + Tailwind CSS

## ?? How It Works

Just like Granola:
1. **You type a quick note:** "Discussed compensation"
2. **The pipe queries screenpipe** for audio transcripts around that time (5-minute window)
3. **AI enhances your note:** "Discussed compensation package - specifically $120K base salary plus $30K in RSUs vesting over 4 years, with a $10K signing bonus"
4. **Save and search** all your enhanced notes

## ??? Technical Implementation

- **Frontend:** React, Next.js 14, Tailwind CSS
- **Screenpipe Integration:** REST API client (localhost:3030)
- **AI:** Supports both Ollama (local) and OpenAI
- **Architecture:** Modular TypeScript codebase

## ?? Installation

```bash
npm install
npm run build
# Or: npm run dev
```

Full guide: [INSTALLATION.md](https://github.com/xiajixi76-beep/screenpipe-granola-notes/blob/main/INSTALLATION.md)

## ?? Improvements Over Granola

1. **24/7 context** - Not just meetings, works anytime
2. **Local-first** - No cloud dependency
3. **Open source** - Fully customizable
4. **No account required** - No Google Workspace needed
5. **Free** - Works with free Ollama models

## ?? Testing

Tested:
- Note input and storage ?
- Screenpipe API integration ?
- AI enhancement with Ollama ?
- Meeting detection ?
- Markdown export ?
- localStorage persistence ?

## ?? Documentation

- [README.md](https://github.com/xiajixi76-beep/screenpipe-granola-notes/blob/main/README.md)
- [INSTALLATION.md](https://github.com/xiajixi76-beep/screenpipe-granola-notes/blob/main/INSTALLATION.md)
- [SUBMISSION.md](https://github.com/xiajixi76-beep/screenpipe-granola-notes/blob/main/SUBMISSION.md)

This is a fully functional pipe ready to use. The code is clean, well-documented, and modular. Happy to make any adjustments based on feedback!

Looking forward to your review! ??
