### ISSUE TITLE
[bug]  Connection lost. retrying

### ISSUE THREAD

**Issue by gamersalpha** [mediar-ai/screenpipe#787]
Hello so i got this version : 

screenpipe_0.14.2_x64-setup.exe

Status loks good : 

![image](https://github.com/user-attachments/assets/6fee0fc1-7c31-46fc-a0eb-9e08d4acb7c8)

but when i try to got in timeline i got this error : 
![image](https://github.com/user-attachments/assets/24363db6-89a8-4834-98c8-7113752ca73b)

and i have nothing to see and the error page : 

but on the folder i can see all video data recorded : 

![image](https://github.com/user-attachments/assets/7863c7b1-2947-4f05-8dbe-888bf5e5f8ee)

what do u think is wrong please ?

**Comment by lorrylockie** [comment]
same here +1

**Comment by xiaoheiit6** [comment]
same here +1

**Comment by louis030195** [comment]
@tribhuwan-kumar can you help?

/bounty 100

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar can you help?
> 
> /bounty 100

sure, I'll update you soon!

**Comment by tribhuwan-kumar** [comment]
> `screenpipe_0.14.2_x64-setup.exe` 

@gamersalpha 
can you update to latest version?
i just checked it and its working fine

**Comment by xiaoheiit6** [comment]
> i feel like facing this issue randomly on windows

I've seen this problem on macOS as well, maybe it's a compilation issue?

**Comment by louis030195** [comment]
something related to react state i believe

**Comment by tribhuwan-kumar** [comment]
> something related to react state i believe because usually i right click reload the ui and it works

yes, maybe that's the reason 
also this could possibly occur when the timeline has not enough data to stream frames, if you look into the timeline page the `loading frames` and `connection lost` is overlapping. this could depends on `url` response

```typescript
    const url = `http://localhost:3030/stream/frames?start_time=${startTime.toISOString()}&end_time=${endTime.toISOString()}&order=descending&target_fps=${target_fps}`;

    setLoadedTimeRange({
      start: startTime,
      end: endTime,
    });

    console.log("starting stream:", url);

    const eventSource = new EventSource(url);
    eventSourceRef.current = eventSource;
```

```typescript
    eventSource.onerror = (error) => {
      if (eventSource.readyState === EventSource.CLOSED) {
        console.log("stream ended (expected behavior)", error);
        setIsLoading(false);
        return;
      }

      console.error("eventsource error:", error);
      setError("connection lost. retrying...");
    };
```

**Comment by louis030195** [comment]
> > something related to react state i believe because usually i right click reload the ui and it works
> 
> yes, maybe that's the reason also this could possibly occur when the timeline has not enough data to stream frames, if you look into the timeline page the `loading frames` and `connection lost` is overlapping. this could depends on `url` response
> 
> ```ts
>     const url = `http://localhost:3030/stream/frames?start_time=${startTime.toISOString()}&end_time=${endTime.toISOString()}&order=descending&target_fps=${target_fps}`;
> 
>     setLoadedTimeRange({
>       start: startTime,
>       end: endTime,
>     });
> 
>     console.log("starting stream:", url);
> 
>     const eventSource = new EventSource(url);
>     eventSourceRef.current = eventSource;
> ```
> 
> ```ts
>     eventSource.onerror = (error) => {
>       if (eventSource.readyState === EventSource.CLOSED) {
>         console.log("stream ended (expected behavior)", error);
>         setIsLoading(false);
>         return;
>       }
> 
>       console.error("eventsource error:", error);
>       setError("connection lost. retrying...");
>     };
> ```

can you send a PR? happy to give tip

maybe retry or something, idk

**Comment by tribhuwan-kumar** [comment]
> can you send a PR? 

sure, there are some edge cases to handle
as an example:

![image](https://github.com/user-attachments/assets/f67702c0-2557-4b7e-a694-d312931f1c8f)
