### ISSUE TITLE
windows install screenpipe didnt work

### ISSUE THREAD

**Issue by FarmhouseNetworking** [mediar-ai/screenpipe#789]
![Screenshot 2024-11-27 104207](https://github.com/user-attachments/assets/8eb29f86-4805-44eb-a244-e53e058c5374)

Unable to setup AI setting with local Ollama as provider. Get API error.

**Comment by louis030195** [comment]
it seems like you are trying to use ollama but did not run it

can you run ollama before?

or did you try to use the embedded AI feature?
