### ISSUE TITLE
[bounty] The given version [19] is not supported, only version 1 to 10 is supported in this build

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#794]
<img width="1512" alt="Screenshot 2024-11-28 at 8 08 53 AM" src="https://github.com/user-attachments/assets/e2b6e5e3-14cc-499a-8772-a82de729993a">

/bounty 50

**Comment by louis030195** [comment]
maybe its related to nvidia gpu + ort (its running on rtx4060)

**Comment by Neptune650** [comment]
> maybe its related to nvidia gpu + ort (its running on rtx4060)

@louis030195 It's not related to the Nvidia GPU but rather the way that Windows handles dynamic libraries.

It's loading an older version of onnxruntime.dll at C:\Windows\System32

While it should be running the one that's packaged with Screenpipe. The DLL has to be in the same place as screenpipe.exe so Windows runs it first.

**Comment by louis030195** [comment]
well if you know how to fix and want to send a PR!

**Comment by Neptune650** [comment]
> well if you know how to fix and want to send a PR!

@louis030195 The thing is that currently this doesn't happen with users, did you use Tauri in your build environment and are you sure there's an onnxruntime.dll where your screenpipe.exe is.
