### ISSUE TITLE
[bounty] $100 prevent double screenpipe backend running at once

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#795]
/bounty 100

definition of done:
- app always avoid having two screenpipe backend running at once

**Comment by louis030195** [comment]
adding a bit more context:

keep seeing windows users having issues with double screenpipe running or stuff like this 

i rarely have this issue on mac

the auto destruct flag in CLI make the CLI kill itself when the app is gone - although windows is such hard to predict OS haha


also other context:

i sometimes have double screenpipe running intentionally because i run a production screenpipe and then i run another dev screenpipe on a different port and data dir - i should still be able to do that

**Comment by ologbonowiwi** [comment]
used a check to see wether the port is available to be used or not, in this way you'll still be able to run multiple screenpipe instance @louis030195.

let me know what you think

**Comment by m13v** [comment]
let's move the check if the port is taken earlier, so we immediately return it to the user before kicking of any other CLI processes, this way we can get a cleaner error output, which will help new users

**Comment by ologbonowiwi** [comment]
@m13v on #836 the check is already on the beginning of the method. still waiting for approval though

**Comment by ologbonowiwi** [comment]
or you mean add even before that function? If so I'll make the chance.

**Comment by m13v** [comment]
just trying to get this error log to be the first one when you start CLI so
users don't get bogged down by details of the logs
