### ISSUE TITLE
[bounty] implement apple native OCR in pure rust 

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#805]
/bounty 250 

definition of done
- apple native OCR in pure rust
- no memory leaks
- no worse performance or accuracy

maybe using https://github.com/yury/cidre

**Comment by Gmin2** [comment]
Hey @louis030195 i am trying to implement this but i am not in macos, can you give me ideas on how i can test this on ci/cd or any other ways i can test it
Thanks

**Comment by louis030195** [comment]
@Gmin2 maybe https://github.com/sickcodes/Docker-OSX

idk
