### ISSUE TITLE
[bug] Failed to generate AI response. 

### ISSUE THREAD

**Issue by blackcat-meow** [mediar-ai/screenpipe#807]
**describe the bug**
I successfully ran llama 3.2:3b-direct-q4_K_M using ollama on a Windows system, but encountered this error while using AI.
![image](https://github.com/user-attachments/assets/322d7078-0c13-46f6-9080-7994742c8a5f)

**expected behavior**
Obtain AI response

**system info**
windows 10
- screenpipe version:0.2.4

**Comment by louis030195** [comment]
@blackcat-meow can you right click inspect in the background of the app and share the logs?

**Comment by blackcat-meow** [comment]
@louis030195 The model I am using is llama3.2:3b-direct-q4_K_M, and this is the error I encountered：
![image](https://github.com/user-attachments/assets/f0ace699-7b2d-4295-ba2d-b74fef720258)
It is possible to have normal conversations in cmd：
![image](https://github.com/user-attachments/assets/497358ee-49a1-48b0-b33d-96478c074ace)

**Comment by blackcat-meow** [comment]
This is my test result in Postman：
![image](https://github.com/user-attachments/assets/e4f2c9c9-75de-42ae-b717-bc81b1b7e1dc)

**Comment by louis030195** [comment]
<img width="981" alt="image" src="https://github.com/user-attachments/assets/8a23d655-8095-46b9-a202-d7bef507fd2c">


did you set the environment variable?

this is because ollama blocks tauri
