### ISSUE TITLE
[bug] my screen recording not work

### ISSUE THREAD

**Issue by furllmm** [mediar-ai/screenpipe#808]
![image](https://github.com/user-attachments/assets/eec6a797-dda0-472d-b5ec-2d2288d59b94)

**Comment by tribhuwan-kumar** [comment]
> ![image](https://github.com/user-attachments/assets/eec6a797-dda0-472d-b5ec-2d2288d59b94)
> 

this happensw hen your query response includes a processing video, means that video you're trying to see is being processed by ffmpeg in background.
you can try searching again after few minutes. you won't get this issue. 

another case can be that video got corrupted (rare condition)

**Comment by furllmm** [comment]
@tribhuwan-kumar  ok 
what i do before shutdown my pc after i close screenpipe

**Comment by louis030195** [comment]
yeah could be more intuitive

we should change the video rendering component to say "still processing" or smthing like this

**Comment by furllmm** [comment]
@louis030195  is this like software, a memory assistant software
i wonder the genre of this like software and want to download one of app of that genre forr android

**Comment by louis030195** [comment]
there is https://github.com/cparish312/HindsightMobile

**Comment by furllmm** [comment]
@louis030195  i mean as screen video
