### ISSUE TITLE
[bug] $50 bounty to make screenpipe shortcut optional

### ISSUE THREAD

**Issue by anirudhkannan9** [mediar-ai/screenpipe#814]
**describe the bug**
Until yesterday, I used cmd + shift + s to open/close the sidebar in Apple Notes. As of today, cmd + shift + s puts the screenpipe window at the front of all windows. Not sure why. I didn't change any settings.

**to reproduce**
Unsure, I didn't change any settings. Cmd + shift + s suddenly puts screenpipe in focus.

**expected behavior**
Depends on the application. In Apple Notes, cmd + shift + s should toggle sidebar.

**system info**
- os: 15.0.1 (24A348)
- screenpipe version: Version 0.14.7 (20241129.174523)

**additional context**

**Comment by louis030195** [comment]
you can change shortcut setting in screenpipe settings

**Comment by anirudhkannan9** [comment]
Thank you, is there an option to disable the shortcut? I just set it to something else for now

**Comment by louis030195** [comment]
/bounty 50 

make shortcut optional
