### ISSUE TITLE
[question] AI search question can not be run in windows 11？

### ISSUE THREAD

**Issue by realamd** [mediar-ai/screenpipe#818]
[screenpipe-app.2024-12-02.log](https://github.com/user-attachments/files/17974935/screenpipe-app.2024-12-02.log)
[screenpipe.2024-12-02.log](https://github.com/user-attachments/files/17974941/screenpipe.2024-12-02.log)

Dear，I build screenpipe app on windows11 from the source. I can starup screepipe app and collect data sucessfully. But when I ask question by AI，I got an error message "Fail to generate AI question, please try again". I use ollama(local) and Qwen 2.5b model.

I try to find the cause fom logfile, but I can not find any error emssage. 

So I want to know how to solve the problem, thanks.

**Comment by louis030195** [comment]
did you set 

`OLLAMA_ORIGINS` with value `*` in environment variable and set the model name in app ui settings?

**Comment by louis030195** [comment]
@realamd ?
