### ISSUE TITLE
[bug] some user reported timeline crash on windows 

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#820]
some user reported timeline crash on windows 

@tribhuwan-kumar do you have this issue too?

**Comment by tribhuwan-kumar** [comment]
> some user reported timeline crash on windows

@louis030195 
can i get the log of that user?
this can be only possible if user hasn't updated his screenpipe

> @tribhuwan-kumar do you have this issue too?

no, i'm not getting this issue, [here](https://drive.google.com/file/d/1hbCRy621gqnts7MGjYpv8dbIjFTaMARE/view?usp=sharing) is a build. you can quick test it!

**Comment by louis030195** [comment]
i had to disable it :(

during a call with a user it was crashing, maybe some windows have different context/api

**Comment by hirowa** [comment]
@tribhuwan-kumar @louis030195 
I think it was me...
Earlier today there was no update and it crashed after trying to open the timeline.
After today's update it seems the timline works! :)
Thanks for having a look!

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar @louis030195 I think it was me... Earlier today there was no update and it crashed after trying to open the timeline. After today's update it seems the timline works! :) Thanks for having a look!

in the latest version of screenpipe @louis030195 has disabled the timeline icon for winodows that's why it isn't crashing.

also if its possible, can you share your log of screenpipe app?
& which version of powershell are you using? you can get version information of powershell by this command `$PSVersionTable`

**Comment by tribhuwan-kumar** [comment]
the timeline is crashing because windows don't give read permission of `C:\Program Files\WindowsApps\` by default
https://priv.au/search?q=permission%20to%20get%20into%20%60C%3A%5CProgram%20Files%5CWindowsApps%60

**Comment by tribhuwan-kumar** [comment]
> the timeline is crashing because windows don't give read permission of `C:\Program Files\WindowsApps\` by default
> 
> https://github.com/mediar-ai/screenpipe/blob/c51c540ca425d8a6f8c604508c8dd357c1c0b67a/screenpipe-app-tauri/src-tauri/src/icons.rs#L254
> 
> https://priv.au/search?q=permission%20to%20get%20into%20%60C%3A%5CProgram%20Files%5CWindowsApps%60

even though it shouldn't crash entire timeline page. it should just failed to load icons with error!

**Comment by hirowa** [comment]
@tribhuwan-kumar 
Here are my logs for yesterday and my PowerShell version is: 
[screenpipe.2024-12-02.log](https://github.com/user-attachments/files/17996505/screenpipe.2024-12-02.log)

PSVersion                      5.1.22621.4391
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.4391
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by tribhuwan-kumar** [comment]
@hirowa thank you for the log and powershell version info, and seeing through the log there is not any specific errors about timeline. that's weird!
 if you could explain what was the exact behavior maybe i'd investigate further

**Comment by hirowa** [comment]
@tribhuwan-kumar 
The exact behaviour was:

**Louis**: Is timeline working for you?
**Me**: No, it gets stuck in loading, and last week before update after I enabled it, it kept crashing, only thing that saved the app from crashing was the update modal/popup.
**Louis**: Can you try hitting the refresh button on the top right corner?

And right after clicking the refresh icon the app got closed. Then trying to open it again it just opens for 1 or 2 sec. and it closes itself. Closing it manually, from the task bar or by restarting the device, doesn't fix the problem.

And after yesterdays update popup, it began to work again! Clicking the icon no longer crashes the app.

Now it seems the app stops working after some time and need to manually restart it.
I attach the logs for today here: [screenpipe.2024-12-03.log](https://github.com/user-attachments/files/18000693/screenpipe.2024-12-03.log)

```
there might be an issue with screen recording and audio recording

screen recording status: error, last update: n/a
audio recording status: error, last update: n/a
```

**Comment by tribhuwan-kumar** [comment]
@hirowa 
sorry for this catastrophic experience, 
i did few changes in timeline with covering some edge cases.
i requested to test this [build](https://drive.google.com/file/d/1Vb-KxmNVxsNTzWH-hddqNIlN_5i3pKPJ/view?usp=sharing) and share the experience, & make sure to uninstall the previously installed screenpipe before installing this build!

**Comment by tribhuwan-kumar** [comment]
> Edit 2: After all the installation process and the onboarding, after clicking the "+" icon on the top left, no other button works for me after that. Need to restart the app.

thanks for the testing the build, i really appreciate that. so there is also issue related with button? i mean that you're not able to click any buttons, right? have you tried opening timeline?

**Comment by hirowa** [comment]
Timeline works fine :)
After clicking the "+" icon on the top left the other buttons get disabled somehow.
But just after the update I just installed it got fixed. Crazy things happening lol

**Comment by tribhuwan-kumar** [comment]
> Timeline works fine :) After clicking the "+" icon on the top left the other buttons get disabled somehow. But just after the update I just installed it got fixed. Crazy things happening lol

are you seeing app icons on timeline? 
small app icons right underneath the timeline images?

**Comment by hirowa** [comment]
This is what I see
![image](https://github.com/user-attachments/assets/3ca3ec8d-80b0-4236-9623-4a0034f9bc82)

**Comment by tribhuwan-kumar** [comment]
its because you updated the app, the build i gave to you was not meant to be updated, in the main version of screenpipe has timeline icons disabled.
