### ISSUE TITLE
[question] why screen records not record correctly

### ISSUE THREAD

**Issue by furllmm** [mediar-ai/screenpipe#821]
![image](https://github.com/user-attachments/assets/1a7f523b-12b7-4ccf-a180-c85d316dafd4)

**Comment by louis030195** [comment]
whats your config?

likely your computer is too slow

**Comment by furllmm** [comment]
pc spec?
![image](https://github.com/user-attachments/assets/fbb4a929-5ef1-4b01-8df9-2c476f682d5b)
or settings?
![image](https://github.com/user-attachments/assets/9aca3441-c0a1-4d89-be62-f31770df6446)
![image](https://github.com/user-attachments/assets/c3772bc6-1b58-4539-bfa8-abb8088789ea)
