### ISSUE TITLE
[bounty] $200 clerk integration

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#822]
https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-app-tauri/app/layout.tsx

the problem is that clerk refuse my live key pk_live_Y2xlcmsuc2NyZWVucGkucGUk

if you are able to make this work with production key with app built (bun tauri build)

and send PR - will do $200

/bounty 200

**Comment by louis030195** [comment]
Tauri is client-side nextjs only fyi

**Comment by mehulmathur16** [comment]
Hi @louis030195, clerk production env. keys will not work on local due to the restrictions on origin. Prod key will only work if the request origin is `https://screenpi.pe/`

I have shared a working curl for the prod key over discord.

Reference: https://www.reddit.com/r/nextjs/comments/164xfye/using_clerk_auth_in_production_why/

**Comment by louis030195** [comment]
https://github.com/GameGlass/clerk-electron-login/blob/main/src/renderer/lib/clerk.ts

maybe this can help

**Comment by mikey0000** [comment]
Our solution likely will work for Tauri as well. I'm not going to write it for you but can help if you tell me what errors your getting. BTW our actual app is in production with Clerk so it does work already.

**Comment by louis030195** [comment]
@mikey0000 this is the issue:
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/5407e99a-90f3-46f6-9f27-58acfbfad7fd">

```
{
    "errors": [
        {
            "message": "Invalid HTTP Origin header",
            "long_message": "The Request HTTP Origin header must be equal to or a subdomain of the requesting URL.",
            "code": "origin_invalid"
        }
    ],
    "clerk_trace_id": "12b8b2225cec6eb7c89359288a21906b"
}
```

using default clerk react getting started

is there a workaround without having to write 500 lines of code? otherwise will just switch to supabase or something like this

**Comment by louis030195** [comment]
fixed
