### ISSUE TITLE
[bug] error: failed to run custom build command for `screenpipe-app v0.14.13 

### ISSUE THREAD

**Issue by volfcan** [mediar-ai/screenpipe#833]
**describe the bug**

on screenpipe-app-tauri build. 

`bun install` was successful

and then 
________________________

`bun scripts/pre_build.js`  command was successful but only threw

> Setting up screenpipe bin for arm64...
> No suitable arm64 screenpipe binary found
> screenpipe for arm64 set up successfully.
> Setting up screenpipe bin for x86_64...
> No suitable x86_64 screenpipe binary found

and then
____________________________________

`bun tauri build` command on returned the following error

> [!CAUTION]
> error: failed to run custom build command for `screenpipe-app v0.14.13 (/Users/volfcan/Downloads/screenpipe/screenpipe-app-tauri/src-tauri)`
> 
> Caused by:
>   process didn't exit successfully: `/Users/volfcan/Downloads/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-518d252cc0a8a105/build-script-build` (exit status: 1)
>   --- stdout
>   cargo:rerun-if-env-changed=TAURI_CONFIG
>   cargo:rerun-if-changed=tauri.conf.json
>   cargo:rustc-check-cfg=cfg(desktop)
>   cargo:rustc-cfg=desktop
>   cargo:rustc-check-cfg=cfg(mobile)
>   cargo:rerun-if-changed=/Users/volfcan/Downloads/screenpipe/screenpipe-app-tauri/src-tauri/tauri.macos.conf.json
>   cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_APP_NAME=pe
>   cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_PREFIX=screenpi
>   cargo:rustc-check-cfg=cfg(dev)
>   cargo:PERMISSION_FILES_PATH=/Users/volfcan/Downloads/screenpipe/screenpipe-app-tauri/src-tauri/target/release/build/screenpipe-app-656208eae2b48ae9/out/app-manifest/__app__-permission-files
>   cargo:rerun-if-changed=capabilities
>   cargo:rustc-env=TAURI_ENV_TARGET_TRIPLE=aarch64-apple-darwin
>   resource path `screenpipe-aarch64-apple-darwin` doesn't exist
> warning: build failed, waiting for other jobs to finish...
> failed to build app: failed to build app
>     Error failed to build app: failed to build app
> error: script "tauri" exited with code 1

**system info**
- screenpipe version: [v0.14.13]

**Comment by louis030195** [comment]
you need to do `cargo build --release --features metal` in the root directory before the script and building the app

as written here https://docs.screenpi.pe/docs/getting-started#option-1-build-from-source-for-advanced-users

**Comment by getong** [comment]
> you need to do `cargo build --release --features metal` in the root directory before the script and building the app
> 
> as written here https://docs.screenpi.pe/docs/getting-started#option-1-build-from-source-for-advanced-users
> 
> because it will build the CLI and then the script copy it into app files

I do run `cargo build --release --features metal` , but it occurs the same bug in macos arm .

**Comment by volfcan** [comment]
Now its throwing me this error on `cargo build --release --features metal` command:

```bash

error: failed to run custom build command for `cidre v0.4.0 (https://github.com/yury/cidre.git?rev=f05c428#f05c4288)`

Caused by:
  process didn't exit successfully: `/Users/volfcan/ZedProjects/screenpipe/target/release/build/cidre-8ac4d4f28ab57629/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=clang_rt.osx
  cargo:rustc-link-search=/Library/Developer/CommandLineTools/usr/lib/clang/16/lib/darwin
  cargo:rustc-link-search=framework=/System/Library/PrivateFrameworks
  cargo:rustc-link-search=framework=/Library/Apple/System/Library/PrivateFrameworks
  cargo:rustc-link-search=native=/Users/volfcan/ZedProjects/screenpipe/target/release/build/cidre-81cb7dd75b41d1b2/out/Release

  --- stderr
  xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
  thread 'main' panicked at /Users/volfcan/.cargo/git/checkouts/cidre-e660120dbd7e907a/f05c428/cidre/build.rs:145:5:
  assertion failed: status.success()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

```

@louis030195
