### ISSUE TITLE
[bug] when trying to download the link sent via email, get "site can't be reached"

### ISSUE THREAD

**Issue by rvjosh** [mediar-ai/screenpipe#842]
When I try to visit https://cdn.crabnebula.app/download/mediar/screenpipe/latest/platform/dmg-aarch64 I get "site can't be reached" - have tried it on multiple computers and can't get to it

**Comment by louis030195** [comment]
> When I try to visit https://cdn.crabnebula.app/download/mediar/screenpipe/latest/platform/dmg-aarch64 I get "site can't be reached" - have tried it on multiple computers and can't get to it

do you have firewall or vpn or live in china?
