### ISSUE TITLE
[bug] Failed to insert audio transcription: table has no speaker_id

### ISSUE THREAD

**Issue by twilwa** [mediar-ai/screenpipe#847]
**describe the bug**
brief description of the bug.
[2m2024-12-05T08:20:10.935309Z[0m [32m INFO[0m [2mscreenpipe_server::core[0m[2m:[0m device MacBook Pro Microphone (input) inserting audio chunk: "/Users/anon/.screenpipe/data/MacBook Pro Microphone (input)_2024-12-05_08-20-10.mp4"    
[2m2024-12-05T08:20:10.935976Z[0m [31mERROR[0m [2mscreenpipe_server::core[0m[2m:[0m Failed to insert audio transcription for device MacBook Pro Microphone (input): error returned from database: (code: 1) table audio_transcriptions has no column named speaker_id    

**system info**
- os: [e.g. macos 10.15.7, windows 10, ubuntu 20.04]
macos sequoia 15.1.1
- screenpipe version: [e.g. 1.2.3]
0.14.23
**additional context**
add any other context, screenshots, or error logs here.

- you can find logs in `~/.screenpipe` on macOS/Linux, and `%APPDATA%\.screenpipe` on Windows.
- you can get app logs by right clicking in the app background and clicking the console tab.

**Comment by louis030195** [comment]
@EzraEllette feel like a few people have this #791 should resolve right?

**Comment by m13v** [comment]
encountered the same problem on my VM, and also on use device yestserday

**Comment by louis030195** [comment]
@m13v which version

**Comment by twilwa** [comment]
Note that just creating the column on the table in the db manually via sql
query is an effective workaround, at least in my case

**Comment by Nowaker** [comment]
> @EzraEllette feel like a few people have this https://github.com/mediar-ai/screenpipe/pull/791 should resolve right?

It's half a year later and it's still broken.

```
% screenpipe --version
screenpipe 0.2.13
```
