### ISSUE TITLE
Feedback for “Examples”

### ISSUE THREAD

**Issue by pleabargain** [mediar-ai/screenpipe#861]
workflow:
screen capture: screenpipe continuously monitors your screen activity.
ai analysis: an ai model analyzes the captured screen data in real-time.
crm enrichment: based on the ai analysis, relevant information is automatically added to your crm (e.g., salesforce, notion).
data organization: the ai categorizes and organizes the information within your crm for easy access and retrieval.
benefits:
save time on manual data entry.
ensure your crm is always up-to-date with the latest customer interactions.
improve the accuracy and completeness of your customer data.

It is NOT clear if screenpipe needs API access in order to work its CRM magic.

please advise

**Comment by m13v** [comment]
it's using user sessions so it doesn't require API or credentials if that's the question. happy to chat about it more
