### ISSUE TITLE
[bug] timeline chat context kinda broken sometimes and no option to start new chat 

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#873]
idk why sometimes context not properly added to the cmdk prompt in timeline

also no option to start new chat

also should be more cursorlike ux ofc, easy to edit previous messages, etc.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the AI Panel component to include a 'New Chat' button, improve message editing, and enhance the overall user experience. Added cursor-like UX for easier message editing and ensured proper context addition to the cmdk prompt.

You can review changes in this commit: https://github.com/mnmnk43434/mediar-ai-screenpipe-873/commit/283452822a52e39105f2fb784146c942bd3048ba.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
