### ISSUE TITLE
[bounty] error: ENOENT while resolving package

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#919]
`error: ENOENT while resolving package 'zod' from '/Users/louisbeaumont/.screenpipe/pipes/pipe-obsidian-time-logs/pipe.ts'`

/bounty 50

i have no idea why this happen sometimes when using pipes - seems non deterministic, maybe something with lock file idk

**Comment by tribhuwan-kumar** [comment]
fixing it. this can be fix by in `bun i` in pipe directory with core
