### ISSUE TITLE
[bug] speaker filter does not properly filter out ocr and ui

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#937]
<img width="1312" alt="Screenshot 2024-12-11 at 4 42 45 PM" src="https://github.com/user-attachments/assets/5b529717-295a-44b4-9e5b-6dfc5c915a5a" />

@EzraEllette fyi

**Comment by louis030195** [comment]
(i added louis as speaker in screenshot)

i guess something in db.rs

**Comment by louis030195** [comment]
also considering in the future we could associate audio to screen stuff based on timestamp but not sure yet about the DX

**Comment by EzraEllette** [comment]
Can you please tell me what the expected behavior is? Also, if you would just like audio results you can check the audio box.

**Comment by louis030195** [comment]
are the ocr result related to the speaker?

**Comment by EzraEllette** [comment]
An option could be to limit ocr results by the timestamps of the speakers, but for now I can make a PR to only enable speaker search when audio only is selected in search. I'll also add a tooltip to explain that audio must be selected to use the feature.

**Comment by louis030195** [comment]
maybe quick hack for now is just toggle speech in the ui when user use speaker
