### ISSUE TITLE
[bounty] make cursor not laggy

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#950]
atm i have to restart cursor 10 times a day for some reason - no idea why, keeps crashing 

i think it's indexing too many things 

for example when i run `bun tauri dev` and change cloudflare backend stuff (unrelated) it would re-trigger the build, shouldn't 

for the context i have `apple macbook pro m4 max 128 gb ram` so it should not happen 

maybe it's something with tweaking some .vscode/settings.json or something else idk - maybe rust indexing too much stuff

<img width="1512" alt="Screenshot 2024-12-12 at 9 21 39 AM" src="https://github.com/user-attachments/assets/eaf8df5c-d22a-4a05-a35f-774f8d8d8b0d" />

/bounty 60

**Comment by louis030195** [comment]
update:

i turned off all extensions except rust-analyzer and it seemed to have fixed the issue, will investigate more

**Comment by Neptune650** [comment]
> update:
> 
> i turned off all extensions except rust-analyzer and it seemed to have fixed the issue, will investigate more

@louis030195 let me know which ones causes issues to fix in the config.json
