### ISSUE TITLE
[bug] v.17 video not starting

### ISSUE THREAD

**Issue by pleabargain** [mediar-ai/screenpipe#966]
**describe the bug**
[2m2024-12-14T05:26:52.317571Z[0m [33m WARN[0m [2mscreenpipe[0m[2m:[0m screenpipe PATH check failed: the PATH is too long to persist using 'setx'. please shorten the PATH.
[2m2024-12-14T05:26:52.317594Z[0m [33m WARN[0m [2mscreenpipe[0m[2m:[0m please ensure screenpipe is installed correctly and is in your PATH

**system info**
win11
![image](https://github.com/user-attachments/assets/ae850bd3-a7f5-40ef-abb1-7354d511b3fe)

**additional context**
![image](https://github.com/user-attachments/assets/c9b8be31-3e0e-456b-98ee-1a7e126f0ac5)
video not starting even after pressing start
![image](https://github.com/user-attachments/assets/e0e7e15d-45ec-45e4-8670-9e8286f3c467)

**Comment by louis030195** [comment]
please share more logs this is not helpful
