### ISSUE TITLE
[bug] Broken GitHub Actions self-hosted service

### ISSUE THREAD

**Issue by Neptune650** [mediar-ai/screenpipe#976]
**describe the bug**
The way the GitHub Actions service is broken with relation to permissions
This is why the Actions doesn't work.

**system info**
- os: NA
- screenpipe version: NA

**additional context**
Source:
- https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#windows
- https://github.com/actions/setup-python/issues/600

**Comment by louis030195** [comment]
so what?

**Comment by louis030195** [comment]
1153149889

can you request access - atm using https://anydesk.com/
