### ISSUE TITLE
[bug] no screenshots in any of the search results

### ISSUE THREAD

**Issue by pleabargain** [mediar-ai/screenpipe#978]
**describe the bug**
 no screenshots in any of the search results

process:

1. search for word
2. results returned
3. plenty of text
4. screenshot is empty in ALL results

![image](https://github.com/user-attachments/assets/f3905936-dee9-4f36-84fa-d9eab7b70d23)
and another example
![image](https://github.com/user-attachments/assets/111f22c5-f229-4c70-bb0e-05765748d9fc)

**system info**
win 11
![image](https://github.com/user-attachments/assets/9ee8909c-411c-4ae7-ad99-12d9cfa77961)

**additional context**
this is a persistent bug and has been reported before

**Comment by louis030195** [comment]
when did you search (time) 

again, video does not render if the video is being written

**Comment by pleabargain** [comment]
> when did you search (time)
> 
> again, video does not render if the video is being written

Time stamp is included in the screenshot. I specifically chose screenshots from the past.

here's another from 2024 dec 13. 3 days ago
![image](https://github.com/user-attachments/assets/d470ac88-4b21-453d-9a89-19aba98b2cb2)



I see that the installer(?) is using a string PATH that is too long?
there are other warnings as well in the logs. 

and screen recording is not working again  :(
![image](https://github.com/user-attachments/assets/09aed72e-89b9-4753-9cad-54c4d888ba36)



here's the log
[2m2024-12-16T03:41:30.891454Z[0m [33m WARN[0m [2mscreenpipe[0m[2m:[0m screenpipe PATH check failed: the PATH is too long to persist using 'setx'. please shorten the PATH.
[2m2024-12-16T03:41:30.891483Z[0m [33m WARN[0m [2mscreenpipe[0m[2m:[0m please ensure screenpipe is installed correctly and is in your PATH
[2m2024-12-16T03:41:31.063926Z[0m [32m INFO[0m [2mscreenpipe_server::db[0m[2m:[0m running migrations
[2m2024-12-16T03:41:31.064298Z[0m [32m INFO[0m [2mscreenpipe_server::db[0m[2m:[0m migrations executed successfully.
[2m2024-12-16T03:41:31.066207Z[0m [32m INFO[0m [2mscreenpipe_audio::whisper[0m[2m:[0m device = Cpu    
[2m2024-12-16T03:41:31.069216Z[0m [32m INFO[0m [2mscreenpipe[0m[2m:[0m starting pipes
[2m2024-12-16T03:41:31.069741Z[0m [32m INFO[0m [2mscreenpipe[0m[2m:[0m watching pid 3896 for auto-destruction
[2m2024-12-16T03:41:31.177929Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m Server starting on 127.0.0.1:3030    
[2m2024-12-16T03:41:31.518484Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m received search request: query='', content_type=Audio, limit=1000, offset=0, start_time=Some(2024-12-09T03:41:28.875Z), end_time=None, app_name=None, window_name=None, min_length=None, max_length=None, speaker_ids=None    
[2m2024-12-16T03:41:31.653823Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m search completed: found 1541 results    
[2m2024-12-16T03:41:34.059726Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-12-15 20:01:00 UTC to 2024-12-16 03:39:28.661 UTC    
[2m2024-12-16T03:41:39.604386Z[0m [32m INFO[0m [2mscreenpipe_audio::vad_engine[0m[2m:[0m Initializing SileroVad...
[2m2024-12-16T03:41:39.604586Z[0m [32m INFO[0m [2mscreenpipe_audio::vad_engine[0m[2m:[0m SileroVad Model downloaded to: "C:\\Users\\denni\\AppData\\Local\\screenpipe\\vad\\silero_vad.onnx"
[2m2024-12-16T03:41:41.497040Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 10s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 52%
[2m2024-12-16T03:41:46.073346Z[0m [32m INFO[0m [2mscreenpipe_audio::core[0m[2m:[0m starting continuous recording for Microphone (HD Pro Webcam C920) (input) (30s segments)    
[2m2024-12-16T03:41:46.073440Z[0m [32m INFO[0m [2mscreenpipe_audio::core[0m[2m:[0m starting continuous recording for SAMSUNG (NVIDIA High Definition Audio) (output) (30s segments)    
[2m2024-12-16T03:41:51.513490Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 20s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 1%
[2m2024-12-16T03:42:01.532517Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 30s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 1%
[2m2024-12-16T03:42:11.553136Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 40s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 1%
[2m2024-12-16T03:42:16.253920Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 478720, speech_frames: 0    
[2m2024-12-16T03:42:21.574528Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 50s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:42:31.603524Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 60s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 1%
[2m2024-12-16T03:42:41.628544Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 70s, Total Memory: 5% (3.26 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:42:46.238423Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:42:51.644923Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 80s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:42:55.840149Z[0m [33m WARN[0m [2mscreenpipe_audio::core[0m[2m:[0m audio device SAMSUNG (NVIDIA High Definition Audio) (output) disconnected. stopping recording.    
[2m2024-12-16T03:42:55.840191Z[0m [32m INFO[0m [2mscreenpipe_audio::core[0m[2m:[0m stopped recording audio stream    
[2m2024-12-16T03:43:01.667108Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 90s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 5%
[2m2024-12-16T03:43:11.683157Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 100s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:43:16.226028Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:43:16.241407Z[0m [32m INFO[0m [2mscreenpipe_audio::core[0m[2m:[0m stopped recording for SAMSUNG (NVIDIA High Definition Audio) (output)    
[2m2024-12-16T03:43:16.243354Z[0m [33m WARN[0m [2mscreenpipe_server::core[0m[2m:[0m Audio device not found: SAMSUNG (NVIDIA High Definition Audio)    
[2m2024-12-16T03:43:21.816374Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 110s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:43:31.833432Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 120s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:43:41.852357Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 130s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 5%
[2m2024-12-16T03:43:46.254458Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:43:51.871256Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 140s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:44:01.889192Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 150s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:44:11.913722Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 160s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 1%
[2m2024-12-16T03:44:16.231443Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:44:21.934589Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 170s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:44:31.954860Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 180s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:44:41.973307Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 190s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:44:46.245850Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:44:51.987996Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 200s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:45:02.009700Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 211s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:45:12.031582Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 221s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:45:16.242613Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:45:22.050262Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 231s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:45:32.071945Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 241s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:45:42.096830Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 251s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 1%
[2m2024-12-16T03:45:46.260187Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:45:52.120478Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 261s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:46:02.148675Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 271s, Total Memory: 5% (3.26 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:46:12.165114Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 281s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 5%
[2m2024-12-16T03:46:16.282123Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:46:22.180190Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 291s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 6%
[2m2024-12-16T03:46:32.205240Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 301s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:46:42.232225Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 311s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:46:46.281499Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:46:52.338838Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 321s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:47:02.362722Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 331s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:47:12.389963Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 341s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:47:16.276338Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:47:22.420278Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 351s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 5%
[2m2024-12-16T03:47:32.460642Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 361s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:47:42.494913Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 371s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:47:46.308732Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:47:52.543123Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 381s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 5%
[2m2024-12-16T03:48:02.577847Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 391s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 5%
[2m2024-12-16T03:48:12.608000Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 401s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:48:16.320539Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:48:22.628072Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 411s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:48:32.671392Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 421s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:48:42.698394Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 431s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:48:46.334502Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:48:52.717070Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 441s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 6%
[2m2024-12-16T03:49:02.760455Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 451s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 5%
[2m2024-12-16T03:49:12.791602Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 461s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 5%
[2m2024-12-16T03:49:16.314368Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:49:22.054431Z[0m [32m INFO[0m [2mscreenpipe_audio::core[0m[2m:[0m starting continuous recording for SAMSUNG (NVIDIA High Definition Audio) (output) (30s segments)    
[2m2024-12-16T03:49:22.816843Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 471s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 6%
[2m2024-12-16T03:49:32.845399Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 481s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:49:42.860109Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 491s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:49:46.336540Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0.0062305294, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 2    
[2m2024-12-16T03:49:52.877033Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 501s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:50:02.902242Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 511s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:50:12.920408Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 521s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:50:16.446343Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:50:22.942749Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 531s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:50:32.964203Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 541s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:50:42.991464Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 551s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:50:46.389102Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:50:53.047115Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 562s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:51:03.072437Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 572s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:51:13.102989Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 582s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 1%
[2m2024-12-16T03:51:16.374807Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:51:23.125894Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 592s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:51:33.174809Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 602s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:51:43.191595Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 612s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:51:46.367954Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:51:53.215318Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 622s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 5%
[2m2024-12-16T03:52:03.261072Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 632s, Total Memory: 5% (3.24 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:52:13.281899Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 642s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:52:16.380925Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0.0062305294, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 2    
[2m2024-12-16T03:52:23.301094Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 652s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:52:33.501172Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 662s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:52:43.524974Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 672s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:52:46.399467Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:52:53.545436Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 682s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 5%
[2m2024-12-16T03:53:03.568278Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 692s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:53:13.598505Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 702s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:53:16.409405Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512000, speech_frames: 0    
[2m2024-12-16T03:53:23.616609Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 712s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:53:33.646996Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 722s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 3%
[2m2024-12-16T03:53:43.674225Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 732s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:53:46.415021Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0.018691588, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 6    
[2m2024-12-16T03:53:53.700307Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 742s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:54:03.717931Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 752s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 1%
[2m2024-12-16T03:54:13.747072Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 762s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:54:16.439908Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Microphone (HD Pro Webcam C920) (input), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 512160, speech_frames: 0    
[2m2024-12-16T03:54:23.765988Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 772s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 4%
[2m2024-12-16T03:54:33.797941Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 782s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 2%
[2m2024-12-16T03:54:43.811726Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 792s, Total Memory: 5% (3.25 GB / 65.36 GB), Total CPU: 1%


thank you

**Comment by tribhuwan-kumar** [comment]
@louis030195, this issue is reported by multiple users,
the potential solution i can think that. if we'd use this function to filter out invalid video files from query or just an api GET request to validate video before rendering in app ui.

https://github.com/mediar-ai/screenpipe/blob/81d716af197fdd51fb8dbfaa93eadf127266306f/screenpipe-server/src/video_utils.rs#L74

**Comment by louis030195** [comment]
just need to change the video ui component to write "being written" or whatever

**Comment by louis030195** [comment]
@pleabargain can you use CLI with --debug flag? and share logs

**Comment by tribhuwan-kumar** [comment]
![image](https://github.com/user-attachments/assets/94a80203-f22c-4753-902a-8a1fca1ab8f0)
![image](https://github.com/user-attachments/assets/118b5073-dd99-4734-89c3-b7cdbcd4f53a)
![image](https://github.com/user-attachments/assets/b4bd0c0a-a027-41a3-944b-c4f2ddfd93a3)

@louis030195 
I'm talking about something like this!

**Comment by pleabargain** [comment]
Please specify the full path of the command.

thank you

**Comment by louis030195** [comment]
#1002 nice @tribhuwan-kumar lets do it?

**Comment by tribhuwan-kumar** [comment]
> #1002 nice @tribhuwan-kumar lets do it?

sure, let me stash the loom branch!

**Comment by tribhuwan-kumar** [comment]
![image](https://github.com/user-attachments/assets/88bca05d-4d39-4be9-9e8b-99630003fcd0)


@louis030195 
why is it showing port already in use even tho its not running any instance of screenpipe!

**Comment by tribhuwan-kumar** [comment]
![image](https://github.com/user-attachments/assets/88bca05d-4d39-4be9-9e8b-99630003fcd0)

![image](https://github.com/user-attachments/assets/28e64f02-337c-4768-9408-af3c28905637)



@louis030195 
why is it showing port already in use even tho its not running any instance of screenpipe!

**Comment by ologbonowiwi** [comment]
not sure also; maybe there a not-screenpipe thing running?

**Comment by tribhuwan-kumar** [comment]
> not sure also; maybe there a not-screenpipe thing running?

to reproduce, on windows run screenpipe from shell and kill it from task manager and try to run it again!

**Comment by pleabargain** [comment]
I tried 
PS Start-Process -FilePath "C:\Users\denni\AppData\Local\screenpipe\screenpipe.exe
and
PS C:\Users\denni\AppData\Local\screenpipe> .\screenpipe.exe

no joy starting SP

![image](https://github.com/user-attachments/assets/57292ec2-e67a-449a-8127-b57a745081e3)

I'm trying to run SP via PS CLI

SP is not running but complaining 
```Error: port already in use```


please advise
